using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.World.UI;

[GenerateTypedNameReferences]
public sealed partial class FactionColorWindow : FancyWindow
{
    public FactionColorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

