using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RF.World;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map.Components;
using Robust.Shared.Timing;

namespace Content.Client._RF.World.UI;

[GenerateTypedNameReferences]
public sealed partial class WorldMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    public WorldMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var world = _entity.System<SharedRimFortressWorldSystem>();
        var map = _entity.System<MapSystem>();

        ResetCoordsButton.OnPressed += _ =>
        {
            if (WorldMap.MapUid is { } mapUid
                && _entity.TryGetComponent(mapUid, out MapGridComponent? grid)
                && _entity.TryGetComponent(_player.LocalEntity, out TransformComponent? xformForm))
                WorldMap.CenterToCoordinates(map.GetTileRef(mapUid, grid, xformForm.Coordinates).GridIndices);
        };

        FactionColor.OnColorChanged += color =>
        {
            if (_player.LocalEntity is { } uid)
                world.SetPlayerFactionColor(uid, color);
        };

        OnResized += Resize;
        Resize();
    }

    public void Set(EntityUid? mapUid)
    {
        WorldMap.MapUid = mapUid;
        WorldMap.UpdateMap();

        if (_entity.TryGetComponent(_player.LocalEntity, out RimFortressPlayerComponent? player))
            FactionColor.Color = player.FactionColor;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        Coordinates.Text = $"{(Vector2i) WorldMap.MousePos()}";
    }

    protected override void ExitedTree()
    {
        OnResized -= Resize;
        base.ExitedTree();
    }

    private void Resize()
    {
        WorldMap.SetSize = Size - new Vector2(0, 74);
    }
}

