using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.World.UI;

[GenerateTypedNameReferences]
public sealed partial class WorldMapWindow : FancyWindow
{
    public WorldMapWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Set(EntityUid? mapUid)
    {
        WorldMap.MapUid = mapUid;
        WorldMap.UpdateMap();
    }
}

