using Content.Client._RF.Notifications;
using Content.Shared._RF.Notifications;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._RF.UserInterface.Controls.Notifications;

[GenerateTypedNameReferences]
public sealed partial class NotificationButton : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private NotificationsSystem? _notifications;

    private readonly Notification? _notification;
    private bool _setup;
    private TimeSpan _nextUpdate;

    private static readonly TimeSpan UpdateRate = TimeSpan.FromSeconds(1);

    public bool Pressed
    {
        get => Button.Pressed;
        set
        {
            Button.Pressed = value;
            DescContainer.Visible = value;
        }
    }

    public event Action<BaseButton.ButtonEventArgs>? OnPressed;

    public NotificationButton(Notification notification)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _notification = notification;

        Button.OnPressed += args =>
        {
            Pressed = args.Button.Pressed;
            OnPressed?.Invoke(args);
        };

        Button.OnKeyBindUp += args =>
        {
            if (args.Function != EngineKeyFunctions.UseSecondary)
                return;

            if (_player.LocalEntity is not { } uid
                || !_proto.TryIndex(_notification?.ProtoId, out var proto))
                return;

            _notifications?.RemoveNotification(uid, proto);
        };

        Button.TooltipSupplier = SupplyTooltip;
        FocusButton.Visible = notification.TargetCoords != null || notification.Target != null;

        if (_notification.ExpireAt == null)
            return;

        ProgressBar.Visible = true;
        ProgressBar.Texture = Texture.White;
        ProgressBar.ModulateSelfOverride = Color.White.WithAlpha(0.1f);
    }

    public void EnsureSetup()
    {
        if (_setup || _notification == null)
            return;

        _setup = true;
        _notifications = _entity.System<NotificationsSystem>();

        var proto = _proto.Index(_notification.ProtoId);

        NameLabel.Text = Loc.GetString(proto.NameId);
        Desc.Text = _notification.Description;

        if (_notification.Duplications > 0)
            NameLabel.Text = $"{NameLabel.Text} x{_notification.Duplications + 1}";

        if (proto.Style != null)
            Button.AddStyleClass(proto.Style);

        FocusButton.OnPressed += _ =>
        {
            if (_player.LocalEntity is { } uid)
                _notifications.FocusToNotification(uid, _notification);
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_notification?.ExpireAt is { } expireAt)
        {
            var fill = 1f - (float)((expireAt - _timing.CurTime) / (expireAt - _notification.StartedAt));
            ProgressBar.SetWidth = Button.Width * Math.Clamp(fill, 0f, 1f);
        }

        if (_nextUpdate > _timing.CurTime || _notification == null)
            return;

        _nextUpdate = _timing.CurTime + UpdateRate;
        TimeLabel.Text = Loc.GetString("notification-start-time",
            ("time", _timing.CurTime - _notification.StartedAt));
    }

    private Control SupplyTooltip(Control? sender)
    {
        var msg = FormattedMessage.FromMarkupOrThrow(
            Button.ToolTip = $"{NameLabel.Text}\n{Loc.GetString("notification-name-tooltip")}");
        var tooltip = new Tooltip();
        tooltip.SetMessage(msg);
        return tooltip;
    }
}
