using Content.Client._RF.Notifications;
using Content.Client.UserInterface.Controls;
using Content.Shared._RF.Notifications;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.UserInterface.Controls.Notifications;

[GenerateTypedNameReferences]
public sealed partial class NotificationsSettingsWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    private NotificationsSystem _notifications = default!;

    private bool _setup;
    private readonly Dictionary<ProtoId<NotificationPrototype>, Control> _ignoredControls = new();

    public NotificationsSettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _proto.PrototypesReloaded += args =>
        {
            if (args.WasModified<NotificationPrototype>())
                ReloadPrototypes();
        };
    }

    private void ReloadPrototypes()
    {
        Container.RemoveAllChildren();

        foreach (var proto in _proto.EnumeratePrototypes<NotificationPrototype>())
        {
            if (_ignoredControls.ContainsKey(proto))
                continue;

            var button = Button(proto);
            Container.AddChild(button);
            _ignoredControls.Add(proto, button);
        }
    }

    public void EnsureSetup()
    {
        if (_setup)
            return;

        _setup = true;
        _notifications = _entity.System<NotificationsSystem>();
        ReloadPrototypes();
    }

    private BoxContainer Button(NotificationPrototype proto)
    {
        var box = new BoxContainer();
        var checkbox = new CheckBox
        {
            Pressed = !_notifications.Ignored(_player.LocalEntity ?? EntityUid.Invalid, proto),
            Margin = new Thickness(3, 0),
        };

        box.AddChild(checkbox);
        box.AddChild(new Label { Text = Loc.GetString(proto.NameId) });

        checkbox.OnPressed += _ =>
        {
            if (_player.LocalEntity is not { } uid)
                return;

            if (!checkbox.Pressed)
                _notifications.AddIgnored(uid, proto);
            else
                _notifications.RemoveIgnored(uid, proto);
        };

        return box;
    }
}

