- type: npcTask
  id: Build
  name: Build
  parent: BaseConstructionTask
  overlayColor: "#FFFF00"
  verbIcon: /Textures/_RF/Interface/hammer-solid.svg.192dpi.png
  compound: BuildCompound
  targetsQuery: BuildTaskTarget
  startPreconditions:
  - !type:ConstructionFinishedPrecondition
    key: Target
    invert: true
  finishPreconditions:
  - !type:ConstructionFinishedPrecondition
    key: Target

- type: htnCompound
  id: BuildCompound
  branches:
  - preconditions:
    - !type:HasComponentPrecondition
      components:
      - type: ActiveDoAfter
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:SetFloatOperator
        targetKey: Time
        amount: 0.5
    - !type:HTNPrimitiveTask
      operator: !type:WaitOperator
        key: Time

  # Turn off welder
  - preconditions:
    - !type:ActiveHandComponentPrecondition
      components:
      - type: Welder
    - !type:ItemTogglePrecondition
      targetKey: PickUpTarget
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:InteractWithOperator
        targetKey: PickUpTarget

  - preconditions:
    - !type:ActiveHandEntityIsPrecondition
      targetKey: PickUpTarget
      invert: true
    tasks:
    # Find item for construction
    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: Construction
        key: PickUpTarget
    - !type:HTNPrimitiveTask
      operator: !type:ConstructionAmountOperator
        targetKey: Target
    - !type:HTNCompoundTask
      task: PickUpCompound

    # Cleanup
    - !type:HTNPrimitiveTask
      operator: !type:TryOperator
        try: !type:HTNPrimitiveTask
          preconditions:
          - !type:KeyExistsPrecondition
            key: Amount
          - !type:ActiveHandEntityIsPrecondition
            targetKey: PickUpTarget
          operator: !type:RemoveKeyOperator
            key: Amount

  - preconditions:
    - !type:ActiveHandEntityIsPrecondition
      targetKey: PickUpTarget
    tasks:
    # Go to the construction target
    - !type:HTNPrimitiveTask
      operator: !type:EntityCoordinatesOperator
        targetKey: Target
    - !type:HTNPrimitiveTask
      operator: !type:MoveToOperator
        pathfindInPlanning: true
        rangeKey: InteractRange
        removeKeyOnFinish: true

    # Turn on Welder
    - !type:HTNPrimitiveTask
      operator: !type:TryOperator
        try: !type:HTNPrimitiveTask
          preconditions:
          - !type:ActiveHandComponentPrecondition
            components:
              - type: Welder
          - !type:ItemTogglePrecondition
            targetKey: PickUpTarget
            invert: true
          operator: !type:InteractWithOperator
            targetKey: PickUpTarget

    - !type:HTNPrimitiveTask
      operator: !type:InteractWithOperator
        targetKey: Target

# Queries
- type: utilityQuery
  id: BuildTaskTarget
  query:
  - !type:OwnedQuery
  - !type:RfComponentFilter
    components:
      - type: CommonConstructionGhost
        constructionProto: BananiumHorn
      - type: Construction
        graph: FloorBananium
        node: BananiumFloor
    requireAll: false
    invert: true
  - !type:ConstructionFinishedFilter
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance

- type: utilityQuery
  id: Construction
  query:
  - !type:ConstructionQuery
    targetKey: Target
  - !type:InventoryFilter
  - !type:InHandsFilter
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
