- type: npcTask
  id: BaseFarmingTask
  parent: BaseNpcTask
  abstract: true
  maxPerformers: 1
  overlayColor: "#1A9927"
  verbIcon: /Textures/_RF/Interface/VerbIcons/seedling-solid.svg.192dpi.png
  tempKeys:
  - PickUpTarget
  targetWhitelist:
    components:
    - PlantHolder
