- type: npcTask
  id: HarvestPlant
  name: Harvest
  parent: BaseFarmingTask
  compound: PlantInteractCompound
  tempKeys:
  - Seed
  targetsQuery: PlantHarvestTaskTarget
  startPreconditions:
  - !type:PlantDeadPrecondition
    targetKey: Target
    invert: true
  - !type:CanHarvestPrecondition
    targetKey: Target
  finishPreconditions:
  - !type:OrPrecondition
    preconditions:
    - !type:CanHarvestPrecondition
      targetKey: Target
      invert: true
    - !type:PlantDeadPrecondition
      targetKey: Target

- type: utilityQuery
  id: PlantHarvestTaskTarget
  query:
  - !type:RangeComponentQuery
    components:
    - type: PlantHolder
  - !type:HarvestFilter
    invert: true
  considerations:
    - !type:NormTargetDistanceCon
      curve: !type:PresetCurve
        preset: TargetDistance
