- type: npcTask
  id: RemoveWeed
  name: Remove weeds
  parent: BaseFarmingTask
  compound: RemoveWeedCompound
  targetsQuery: RemoveWeedTaskTarget
  startPreconditions:
  - !type:WeedLevelPrecondition
    targetKey: Target
    moreThan: 0
  finishPreconditions:
  - !type:WeedLevelPrecondition
    targetKey: Target
    lessThan: 0.1

- type: htnCompound
  id: RemoveWeedCompound
  branches:
  - preconditions:
    - !type:ActiveHandEntityTagsPrecondition
      tags:
      - Hoe
      invert: true
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: Hoe
        key: PickUpTarget
    - !type:HTNCompoundTask
      task: PickUpCompound

  - tasks:
    - !type:HTNCompoundTask
      task: InteractCompound

# Queries
- type: utilityQuery
  id: RemoveWeedTaskTarget
  query:
  - !type:RangeComponentQuery
    components:
    - type: PlantHolder
  - !type:WeedLevelFilter
    lessThan: 5
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance

- type: utilityQuery
  id: Hoe
  query:
  - !type:OwnedQuery
  - !type:TagFilter
    tags:
    - Hoe
    invert: true
  - !type:InventoryFilter
  - !type:InHandsFilter
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
