- type: npcTask
  id: RemovePlant
  name: Remove plant
  parent: BaseFarmingTask
  compound: PlantInteractCompound
  targetsQuery: PlantRemoveTaskTarget
  startPreconditions:
  - !type:PlantDeadPrecondition
    targetKey: Target
  finishPreconditions:
  - !type:PlantHolderFilledPrecondition
    targetKey: Target
    invert: true

- type: htnCompound
  id: PlantInteractCompound
  branches:
  # Getting seeds instead of harvesting if we don't have them
  - preconditions:
    - !type:PlantDeadPrecondition
      targetKey: Target
      invert: true
    - !type:PlantSampledPrecondition
      targetKey: Target
      invert: true
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:GetHolderSeedOperator
        targetKey: Target
        seedKey: Seed

    - !type:HTNPrimitiveTask
      operator: !type:UtilityCountOperator
        proto: KeySeed
        lessThan: 10

    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: PlantSampleTaker
        key: PickUpTarget
    - !type:HTNCompoundTask
      task: PickUpAndInteractCompound

    - !type:HTNPrimitiveTask
      operator: !type:MarkOwnerInRangeOperator

  - preconditions:
    - !type:NeedSharpForHarvestPrecondition
      targetKey: Target
    - !type:ActiveHandComponentPrecondition
      components:
      - type: Sharp
      invert: true
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: Sharp
        key: PickUpTarget
    - !type:HTNCompoundTask
      task: PickUpCompound

  - preconditions:
    - !type:NeedSharpForHarvestPrecondition
      targetKey: Target
      invert: true
    - !type:ActiveHandEntityPrecondition
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:DropOperator

  - tasks:
    - !type:HTNCompoundTask
      task: InteractCompound
    - !type:HTNPrimitiveTask
      operator: !type:MarkOwnerInRangeOperator

# Queries
- type: utilityQuery
  id: PlantRemoveTaskTarget
  query:
  - !type:RangeComponentQuery
    components:
    - type: PlantHolder
  - !type:PlantDeadFilter
    invert: true
  considerations:
    - !type:NormTargetDistanceCon
      curve: !type:PresetCurve
        preset: TargetDistance

- type: utilityQuery
  id: PlantSampleTaker
  query:
  - !type:OwnedQuery
  - !type:TagFilter
    tags:
    - PlantSampleTaker
    invert: true
  - !type:InventoryFilter
  - !type:InHandsFilter
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance

- type: utilityQuery
  id: KeySeed
  query:
  - !type:OwnedQuery
  - !type:KeySeedFilter
    key: Seed
    invert: true
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance

- type: utilityQuery
  id: Sharp
  query:
  - !type:OwnedQuery
  - !type:ComponentFilter
    components:
    - type: Sharp
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
