- type: npcTask
  id: WaterPlant
  name: Water the plant
  parent: BaseFarmingTask
  compound: PlantWaterCompound
  targetsQuery: PlantWaterTaskTarget
  startPreconditions:
  - !type:RefillableSolutionPrecondition
    targetKey: Target
    reagent: Water
    lessThan: 50.0
  finishPreconditions:
  - !type:RefillableSolutionPrecondition
    targetKey: Target
    reagent: Water
    moreThan: 100.0

- type: htnCompound
  id: PlantWaterCompound
  branches:
  - preconditions:
    - !type:ActiveHandComponentPrecondition
      components:
        - type: SolutionTransfer
      invert: true
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: Bucket
        key: PickUpTarget
    - !type:HTNCompoundTask
      task: PickUpCompound

  - preconditions:
    - !type:ActiveHandComponentPrecondition
      components:
      - type: SolutionTransfer
    - !type:ActiveHandDrainableSolutionPrecondition
      reagent: Water
      moreThan: 0
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:EntityCoordinatesOperator
        targetKey: Target
    - !type:HTNPrimitiveTask
      operator: !type:MoveToOperator
        pathfindInPlanning: true
        rangeKey: InteractRange
        removeKeyOnFinish: true
    - !type:HTNPrimitiveTask
      operator: !type:InteractWithOperator
        targetKey: Target

  - preconditions:
    - !type:ActiveHandComponentPrecondition
      components:
      - type: SolutionTransfer
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: WaterSource
        key: WaterSourceTarget
    - !type:HTNPrimitiveTask
      operator: !type:EntityCoordinatesOperator
        targetKey: WaterSourceTarget
    - !type:HTNPrimitiveTask
      operator: !type:MoveToOperator
        pathfindInPlanning: true
        rangeKey: InteractRange
        removeKeyOnFinish: true
    - !type:HTNPrimitiveTask
      operator: !type:InteractWithOperator
        targetKey: WaterSourceTarget

# Queries
- type: utilityQuery
  id: PlantWaterTaskTarget
  query:
  - !type:RangeComponentQuery
    components:
    - type: PlantHolder
  - !type:RefillableReagentFilter
    reagent: Water
    moreThan: 15
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance

- type: utilityQuery
  id: Bucket
  query:
  - !type:OwnedQuery
  - !type:ComponentFilter
    components:
    - type: SolutionTransfer
    - type: Item
  - !type:DrainableSolutionFilter
    maxVolumeLessThan: 80.0
  - !type:OrFilter
    filters:
    - !type:DrainableEmptyFilter
    - !type:DrainableOnlyReagentFilter
      reagent: Water
    invert: true
  - !type:InventoryFilter
  - !type:InHandsFilter
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance

- type: utilityQuery
  id: WaterSource
  limit: 1000
  query:
  - !type:RangeComponentQuery
    components:
    - type: DrainableSolution
  - !type:DrainableReagentFilter
    reagent: Water
    moreThan: 80.0
    invert: true
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
