using Content.Client.Construction;
using Content.Shared.Construction.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Placement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Construction.Controls;

[GenerateTypedNameReferences]
public sealed partial class ConstructionButton : Button
{
    [Dependency] private readonly IPlacementManager _placement = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ILocalizationManager _locale = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public ConstructionButton(ConstructionPrototype prototype)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var construction = _entityManager.System<ConstructionSystem>();

        Label.Text = prototype.SetName.HasValue ? Loc.GetString(prototype.SetName) : prototype.Name;

        if (construction.TryGetRecipePrototype(prototype.ID, out var recipe)
            && _prototype.TryIndex(recipe, out var target))
            Texture.SetPrototype(target);

        OnPressed += _ =>
        {
            if (_placement.IsActive)
                _placement.Clear();

            _placement.BeginPlacing(
                new PlacementInformation { IsTile = false, PlacementOption = prototype.PlacementMode },
                new CommonConstructionPlacementHijack(_entityManager.System<CommonConstructionSystem>(), prototype));
        };
    }

    public ConstructionButton(string name, EntityPrototype proto)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Label.Text = _locale.TryGetString(name, out var locName) ? locName : name;
        Texture.SetPrototype(proto);
    }
}

