using Content.Client._Rf.Lobby;
using Content.Shared._RF.CCVar;
using Content.Shared._RF.Skills;
using Content.Shared._RF.Skills.Components;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._RF.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterSkillsTab : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private readonly RfLobbyUIController _controller;

    public event Action<(ProtoId<SkillPrototype> Skill, int Level, int LeftPoints)>? OnSkillUpdate;

    public CharacterSkillsTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _controller = UserInterfaceManager.GetUIController<RfLobbyUIController>();
    }

    public void Refresh(HumanoidCharacterProfile? profile)
    {
        Container.RemoveAllChildren();


        var leftPoints = _controller.LeftPoints();
        LeftPoints.Text = $"{Loc.GetString("character-skills-tab-left-points")}: {leftPoints.ToString()}";

        if (profile == null)
            return;

        var leftLevels = _cfg.GetCVar(RfVars.MaxPrefSkillsLevel) - profile.GetSkillLevels();
        LeftLevels.Text = $"{Loc.GetString("character-skills-tab-left-levels")}: {leftLevels}";

        SkillExpModificatorComponent? comp = null;

        if (_prototype.TryIndex(profile.Species, out var species)
            && _prototype.TryIndex(species.Prototype, out var entProto))
            entProto.TryGetComponent(out comp, _entity.ComponentFactory);

        foreach (var proto in _prototype.EnumeratePrototypes<SkillPrototype>())
        {
            var level = profile.SkillsPreferences.GetValueOrDefault(proto, 0);
            var modifier = comp?.Multipliers.FirstOrNull(x => x.Key == proto)?.Value ?? null;
            var control = new CharacterSkill(proto, level, modifier);

            control.Levels.DisableIncrease = leftLevels <= 0
                                             || leftPoints - proto.LevelPreferencesPoints < 0
                                             || level >= proto.MaxPreferencesLevel;
            control.Levels.OnValueChanged += args =>
            {
                var newPoints = leftPoints - (args.New - args.Old) * proto.LevelPreferencesPoints;

                if (newPoints < 0)
                    control.Levels.SetValue((leftPoints + args.Old * proto.LevelPreferencesPoints) / proto.LevelPreferencesPoints);

                OnSkillUpdate?.Invoke((proto, control.Levels.Value, leftPoints));
            };

            Container.AddChild(control);
        }
    }
}

