using Content.Client._Rf.Lobby;
using Content.Client._RF.Skills;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Lobby.UI;

/// <summary>
/// Holds character data on the side of the setup GUI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RfCharacterPickerButton : ContainerButton
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private EntityUid _previewDummy;

    /// <summary>
    /// Invoked if we should delete the attached character
    /// </summary>
    public event Action? OnDeletePressed;

    public RfCharacterPickerButton(ButtonGroup group, ICharacterProfile profile, bool isSelected)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AddStyleClass(StyleClassButton);
        ToggleMode = true;
        Group = group;
        var description = profile.Name;

        if (profile is not HumanoidCharacterProfile humanoid)
        {
            _previewDummy = _entManager.SpawnEntity(
                _prototype.Index<SpeciesPrototype>(SharedHumanoidAppearanceSystem.DefaultSpecies).DollPrototype,
                MapCoordinates.Nullspace);
        }
        else
        {
            _previewDummy = UserInterfaceManager
                .GetUIController<RfLobbyUIController>()
                .LoadProfileEntity(humanoid, null, true);

            description = $"{description}, \n{_entManager.System<SkillsSystem>().SkillProfession(humanoid.SkillsPreferences)}";
        }

        Pressed = isSelected;
        DeleteButton.Visible = !isSelected;

        View.SetEntity(_previewDummy);
        DescriptionLabel.Text = description;

        DeleteButton.OnPressed += _ =>
        {
            Parent?.RemoveChild(this);
            OnDeletePressed?.Invoke();
        };
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _entManager.DeleteEntity(_previewDummy);
        _previewDummy = default;
    }
}
