using System.Linq;
using Content.Client.Resources;
using Content.Shared._RF.Preferences;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class RfExpeditionEquipmentEditor : Control
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPlayerEquipmentManager _equipment = default!;

    private bool _isDirty;
    private int _pointsUsed;
    private ExpeditionEquipmentPrototype? _selectedCategory;
    private Dictionary<EntProtoId, int> _itemsSelected = new();
    private readonly Dictionary<EntProtoId, int> _costs = new();
    private readonly Dictionary<EntProtoId, ExpeditionItemButton> _buttons = new();

    public bool IsDirty
    {
        get => _isDirty;
        private set
        {
            _isDirty = value;

            SaveButton.Disabled = !value;
            ResetButton.Disabled = !value;
        }
    }

    public RfExpeditionEquipmentEditor()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
        var back = new StyleBoxTexture
        {
            Texture = panelTex,
            Modulate = new Color(37, 37, 42)
        };

        ResetButton.OnPressed += _ => BuildList();
        SaveButton.OnPressed += _ => SaveSettings();
        Search.OnTextChanged += _ => BuildItems();
        ClearSearch.OnPressed += _ => Search.SetText(string.Empty, true);

        back.SetPatchMargin(StyleBox.Margin.All, 10);
        BackgroundPanel.PanelOverride = back;
    }

    public void SaveSettings()
    {
        _equipment.SetPlayerEquipment(_itemsSelected);
        IsDirty = false;
    }

    public void BuildList()
    {
        _costs.Clear();
        _itemsSelected = new(_equipment.Equipment);
        IsDirty = false;
        CategoryBox.RemoveAllChildren();

        var prototypes = _protoManager.EnumeratePrototypes<ExpeditionEquipmentPrototype>().ToList();
        var categoryGroup = new ButtonGroup();

        if (_selectedCategory != null && !prototypes.Contains(_selectedCategory))
            _selectedCategory = null;

        foreach (var proto in prototypes)
        {
            if (proto.Hidden)
                continue;

            foreach (var (entProto, cost) in proto.Items)
            {
                _costs.Add(entProto, cost);
            }

            var categoryButton = new Button
            {
                Group = categoryGroup,
                HorizontalExpand = true,
                Text = $"{proto.Name} ({proto.Items.Count})",
            };

            categoryButton.OnPressed += _ =>
            {
                _selectedCategory = proto;
                BuildItems();
            };

            categoryButton.AddStyleClass("ButtonBig");
            CategoryBox.AddChild(categoryButton);
        }

        BuildItems();
        Recount();
    }

    private void BuildItems()
    {
        ItemBox.RemoveAllChildren();
        _buttons.Clear();

        if (_selectedCategory == null)
            return;

        var maxPoints = _cfg.GetCVar(CCVars.RoundstartEquipmentPoints);

        foreach (var (proto, cost) in _selectedCategory.Items)
        {
            var count = _itemsSelected.GetValueOrDefault(proto, 0);
            var itemButton = new ExpeditionItemButton(proto, cost, count);

            if (!string.IsNullOrEmpty(Search.Text)
                && (itemButton.NameLabel.Text == null
                || !itemButton.NameLabel.Text.Contains(Search.Text)))
                continue;

            itemButton.Plus.Disabled = cost + _pointsUsed > maxPoints;
            itemButton.OnPointsSet += args =>
            {
                var newPoints = _pointsUsed - args.Old + args.New;
                if (newPoints >= maxPoints)
                    itemButton.Count = (maxPoints - (_pointsUsed - args.Old)) / itemButton.Cost;
                else if (newPoints < 0)
                    itemButton.Count = 0;

                _itemsSelected[proto] = itemButton.Count;
                Recount();
                SetDirty();
            };

            _buttons.Add(proto, itemButton);
            ItemBox.AddChild(itemButton);
        }
    }

    private void Recount()
    {
        _pointsUsed = 0;
        var maxPoints = _cfg.GetCVar(CCVars.RoundstartEquipmentPoints);

        foreach (var (proto, count) in _itemsSelected)
        {
            if (!_costs.TryGetValue(proto, out var cost))
                continue;

            _pointsUsed += count * cost;
        }

        foreach (var (proto, button) in _buttons)
        {
            if (!_costs.TryGetValue(proto, out var cost))
                continue;

            button.Plus.Disabled = cost + _pointsUsed > maxPoints;
        }

        PointsLabel.Text =
            $"{Loc.GetString("expedition-equipment-editor-points-left")}: {maxPoints - _pointsUsed}";
    }

    private void SetDirty()
    {
        foreach (var (proto, count) in _itemsSelected)
        {
            if (_equipment.Equipment.TryGetValue(proto, out var value) && value == count)
                continue;

            if (count == 0 && !_equipment.Equipment.ContainsKey(proto))
                continue;

            IsDirty = true;
            return;
        }

        IsDirty = false;
    }
}

