using System.Linq;
using Content.Client._Rf.Lobby;
using Content.Shared._RF.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class RfExpeditionEquipmentEditor : Control
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IPlayerEquipmentManager _equipment = default!;

    private readonly RfLobbyUIController _lobby;

    private bool _isDirty;
    private int _leftPoints;
    private ExpeditionEquipmentPrototype? _selectedCategory;
    private Dictionary<EntProtoId, int> _itemsSelected = new();
    private readonly Dictionary<EntProtoId, int> _costs = new();
    private readonly Dictionary<EntProtoId, ExpeditionItemButton> _buttons = new();

    public bool IsDirty
    {
        get => _isDirty;
        private set
        {
            _isDirty = value;

            SaveButton.Disabled = !value;
            ResetButton.Disabled = !value;
        }
    }

    public RfExpeditionEquipmentEditor()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _lobby = UserInterfaceManager.GetUIController<RfLobbyUIController>();

        ResetButton.OnPressed += _ => BuildList();
        SaveButton.OnPressed += _ => SaveSettings();
        Search.OnTextChanged += _ => BuildItems();
        ClearSearch.OnPressed += _ => Search.SetText(string.Empty, true);
    }

    public void SaveSettings()
    {
        _equipment.SetPlayerEquipment(_itemsSelected);
        IsDirty = false;
        BuildList();
    }

    public void BuildList()
    {
        _costs.Clear();
        _itemsSelected = new(_equipment.Equipment);
        IsDirty = false;
        CategoryBox.RemoveAllChildren();

        var prototypes = _protoManager.EnumeratePrototypes<ExpeditionEquipmentPrototype>().ToList();
        var categoryGroup = new ButtonGroup();

        if (_selectedCategory != null && !prototypes.Contains(_selectedCategory))
            _selectedCategory = null;

        foreach (var proto in prototypes)
        {
            if (proto.Hidden)
                continue;

            foreach (var (entProto, cost) in proto.Items)
            {
                _costs.Add(entProto, cost);
            }

            var categoryButton = new Button
            {
                Group = categoryGroup,
                HorizontalExpand = true,
                Text = CategoryPoints(proto) is var points && points != 0
                    ? $"{proto.Name} ({CategoryPoints(proto)})"
                    : proto.Name,
            };

            categoryButton.OnPressed += _ =>
            {
                _selectedCategory = proto;
                BuildItems();
            };

            categoryButton.AddStyleClass("ButtonBig");
            CategoryBox.AddChild(categoryButton);
        }

        BuildItems();
        Recount();
    }

    private void BuildItems()
    {
        ItemBox.RemoveAllChildren();
        _buttons.Clear();

        if (_selectedCategory == null)
            return;

        foreach (var (proto, cost) in _selectedCategory.Items)
        {
            var count = _itemsSelected.GetValueOrDefault(proto, 0);
            var itemButton = new ExpeditionItemButton(proto, cost, count);

            if (!string.IsNullOrEmpty(Search.Text)
                && (itemButton.NameLabel.Text == null
                || !itemButton.NameLabel.Text.Contains(Search.Text)))
                continue;

            itemButton.Plus.Disabled = cost > _leftPoints;
            itemButton.OnPointsSet += args =>
            {
                if (_leftPoints + args.Old - args.New < 0)
                    itemButton.Count = (_leftPoints + args.Old) / itemButton.Cost;

                _itemsSelected[proto] = itemButton.Count;
                Recount();
                SetDirty();
            };

            _buttons.Add(proto, itemButton);
            ItemBox.AddChild(itemButton);
        }
    }

    private void Recount()
    {
        _leftPoints = _lobby.LeftPoints();

        foreach (var (proto, button) in _buttons)
        {
            if (!_costs.TryGetValue(proto, out var cost))
                continue;

            button.Plus.Disabled = cost > _leftPoints;
        }

        PointsLabel.Text =
            $"{Loc.GetString("expedition-equipment-editor-points-left")}: {_leftPoints}";
    }

    private void SetDirty()
    {
        foreach (var (proto, count) in _itemsSelected)
        {
            if (_equipment.Equipment.TryGetValue(proto, out var value) && value == count)
                continue;

            if (count == 0 && !_equipment.Equipment.ContainsKey(proto))
                continue;

            IsDirty = true;
            return;
        }

        IsDirty = false;
    }

    public int UsedPoints()
    {
        var points = 0;

        foreach (var (proto, count) in _itemsSelected)
        {
            if (!_costs.TryGetValue(proto, out var cost))
                continue;

            points += count * cost;
        }

        return points;
    }

    private int CategoryPoints(ExpeditionEquipmentPrototype prototype)
    {
        var points = 0;

        foreach (var (proto, cost) in prototype.Items)
        {
            if (_itemsSelected.TryGetValue(proto, out var count))
                points += count * cost;
        }

        return points;
    }
}

