using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class RfHighlightedContainer : PanelContainer
{
    public RfHighlightedContainer()
    {
        RobustXamlLoader.Load(this);
    }
}
