- type: npcTask
  id: LeaveSettlement
  name: Leave Settlement
  parent: BaseSoloPerformTask
  compound: LeaveSettlementCompound
  targetsQuery: Self # Stub for the ability to use this task as a passive
  startPreconditions:
  - !type:MoodPrecondition
    lessThan: -80
  - !type:RandomPrecondition
    chance: 0.1 # Adding randomness to the triggering of this task
  finishPreconditions:
  - !type:InRangeFromSettlementsPrecondition
    range: 100
    invert: true

- type: htnCompound
  id: LeaveSettlementCompound
  branches:
  - tasks:
    - !type:HTNPrimitiveTask
      operator: !type:RemoveFromSettlement
    - !type:HTNPrimitiveTask
      operator: !type:SetFloatOperator
        targetKey: Range
        amount: 50
    - !type:HTNPrimitiveTask
      operator: !type:PickAccessibleOperator
        rangeKey: Range
    - !type:HTNPrimitiveTask
      operator: !type:MoveToOperator
        pathfindInPlanning: false
