- type: npcTask
  id: MentalBreakdown
  name: Mental breakdown
  parent: BaseSoloPerformTask
  compound: MentalBreakdownCompound
  targetsQuery: Self # Stub for the ability to use this task as a passive
  startPreconditions:
  - !type:MoodPrecondition
    lessThan: -60
  - !type:RandomPrecondition
    chance: 0.1 # Adding randomness to the triggering of this task
  finishPreconditions:
  - !type:HasMoodEffectPrecondition
    effect: MoodMentalBreakdown
    invert: true

# Compounds
- type: htnCompound
  id: MentalBreakdownCompound
  branches:
  - preconditions:
    - !type:HasMoodEffectPrecondition
      effect: MoodMentalBreakdown
      invert: true
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:AddMoodEffectOperator
        effect: MoodMentalBreakdown

  # With a small chance, the entity will shout out a random phrase
  - preconditions:
    - !type:RandomPrecondition
      chance: 0.1
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:SpeakDatasetOperator
        dataset: MentalBreakdownPhrases

  # Entity will pick up a nearby object and throw it away
  - preconditions:
    - !type:RandomPrecondition
      chance: 0.33
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: NearbyItem
        key: PickUpTarget
    - !type:HTNCompoundTask
      task: MentalBreakdownThrowItemCompound

  # With some chance, we will attack the nearest friendly entity
  - preconditions:
    - !type:RandomPrecondition
      chance: 0.33
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: NearbyFriendlyMeleeTargets
    - !type:HTNCompoundTask
      task: MentalBreakdownAttackCompound

  # With some chance, we will attack the nearest object
  - preconditions:
    - !type:RandomPrecondition
      chance: 0.33
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:UtilityOperator
        proto: NearbyDestructible
    - !type:HTNCompoundTask
      task: MentalBreakdownAttackCompound

  # We go to a random point nearby
  - tasks:
    - !type:HTNPrimitiveTask
      operator: !type:PickAccessibleOperator
        rangeKey: IdleRange
    - !type:HTNPrimitiveTask
      operator: !type:MoveToOperator
        pathfindInPlanning: false

- type: htnCompound
  id: MentalBreakdownAttackCompound
  branches:
  - preconditions:
    - !type:ActiveHandEntityPrecondition
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:DropOperator

  - tasks:
    - !type:HTNPrimitiveTask
      operator: !type:EntityCoordinatesOperator
        targetKey: Target
    - !type:HTNPrimitiveTask
      operator: !type:MoveToOperator
        pathfindInPlanning: true
        rangeKey: MeleeRange
    - !type:HTNPrimitiveTask
      operator: !type:MeleeOperator
        targetKey: Target

- type: htnCompound
  id: MentalBreakdownThrowItemCompound
  branches:
  - tasks:
    - !type:HTNCompoundTask
      task: PickUpCompound
    - !type:HTNPrimitiveTask
      operator: !type:PickAccessibleOperator
        rangeKey: VisionRadius
    - !type:HTNPrimitiveTask
      operator: !type:ThrowAtOperator

# Queries
- type: utilityQuery
  id: NearbyFriendlyMeleeTargets
  query:
  - !type:RangeComponentQuery
    components:
    - type: NpcFactionMember
    range: 10
  - !type:IsFriendlyFilter
    invert: true
  considerations:
  - !type:TargetIsAliveCon
    curve: !type:BoolCurve
  - !type:TargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
  - !type:TargetAccessibleCon
    curve: !type:BoolCurve
  - !type:TargetInLOSOrCurrentCon
    curve: !type:BoolCurve

- type: utilityQuery
  id: NearbyDestructible
  query:
  - !type:RangeComponentQuery
    components:
    - type: Destructible
    range: 10
  considerations:
  - !type:TargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
  - !type:TargetAccessibleCon
    curve: !type:BoolCurve
  - !type:TargetInLOSOrCurrentCon
    curve: !type:BoolCurve

- type: utilityQuery
  id: NearbyItem
  query:
  - !type:RangeComponentQuery
    components:
    - type: Item
    range: 10
  - !type:InventoryFilter
  - !type:InHandsFilter
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
  - !type:TargetAccessibleCon
    curve: !type:BoolCurve
  - !type:TargetInLOSOrCurrentCon
    curve: !type:BoolCurve
