using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.TopInfoPanel;

[GenerateTypedNameReferences]
public sealed partial class InfoPanelCell : Control
{
    public Color IconModulate { set => Icon.ModulateSelfOverride = value; }

    public string TexturePath { set => Icon.TexturePath = value; }

    public string Text { set => Label.Text = value; }

    public InfoPanelCell()
    {
        RobustXamlLoader.Load(this);
    }
}
