using Content.Client._RF.UserInterface.Controllers;
using Content.Shared._RF.World;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RF.UserInterface.Controls.TopInfoPanel;

[GenerateTypedNameReferences]
public sealed partial class TopPanelWidget : UIWidget
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private static readonly TimeSpan UpdateRate = TimeSpan.FromSeconds(1);
    private readonly InfoPanelUiController _controller;

    private TimeSpan _nextUpdate;

    public TopPanelWidget()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _controller = UserInterfaceManager.GetUIController<InfoPanelUiController>();

        _controller.OnWorldTempChanged += UpdateTemperature;

        UpdateTemperature();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_nextUpdate > _timing.CurTime)
            return;

        if (_entity.TryGetComponent(_player.LocalEntity, out RimFortressPlayerComponent? player))
            Population.Text = player.Pops.Count.ToString();

        UpdateDateTime();

        _nextUpdate = _timing.CurTime + UpdateRate;
    }

    private void UpdateDateTime()
    {
        var (time, dayDuration) = _controller.GetTime();

        // We take the length of an in-game day in 24 hours and get the current time
        var gameTimeHours = time.TotalSeconds % dayDuration.TotalSeconds
            / dayDuration.TotalSeconds * 24;

        var hours = (int) gameTimeHours;
        var minutes = (int) ((gameTimeHours - hours) * 60);

        var timeText = $"{hours:00}:{minutes:00}";
        var days = (int) Math.Floor(time / dayDuration) + 1;

        Time.Text = $"{timeText}";
        Date.Text = $"{Loc.GetString("top-info-panel-datetime-day")} {days}";

        Time.TexturePath = gameTimeHours switch
        {
            < 6 => "/Textures/_RF/Interface/moon-solid.svg.192dpi.png",
            < 19 => "/Textures/_RF/Interface/sun-solid.svg.192dpi.png",
            _ => "/Textures/_RF/Interface/moon-solid.svg.192dpi.png",
        };
    }

    private void UpdateTemperature()
    {
        var tempC = _controller.WorldTemp - 273.15f;
        Temperature.Text = $"{tempC:0.0}\u00b0";

        Temperature.TexturePath = tempC switch
        {
            < 10 => "/Textures/_RF/Interface/temperature-low-solid.svg.192dpi.png",
            < 20 => "/Textures/_RF/Interface/temperature-half-solid.svg.192dpi.png",
            < 30 => "/Textures/_RF/Interface/temperature-three-quarters-solid.svg.192dpi.png",
            _ => "/Textures/_RF/Interface/temperature-high-solid.svg.192dpi.png",
        };
    }

    protected override void ExitedTree()
    {
        _controller.OnWorldTempChanged -= UpdateTemperature;

        base.ExitedTree();
    }
}

