using System.Linq;
using Content.Client._RF.NPC;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class NpcJobsSettingsWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private RoutineNpcTasksSystem _routine = default!;

    private readonly HashSet<NpcJobButton> _dirtyButtons = new();
    private readonly HashSet<int> _deleteJobs = new();
    private readonly ButtonGroup _jobButtonGroup = new();

    private int? _selectedJob;

    public NpcJobsSettingsWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SaveButton.OnPressed += _ =>
        {
            foreach (var button in _dirtyButtons)
            {
                if (button.JobId == 0)
                    _routine.CreateJob(button.JobName, button.Tasks ?? new(), button.IconPath);
                else
                    _routine.UpdateJob(button.JobId, button.JobName, button.IconPath, button.Tasks);
            }

            foreach (var id in _deleteJobs)
            {
                if (id != 0)
                    _routine.DeleteJob(id);
            }

            _dirtyButtons.Clear();
            _deleteJobs.Clear();

            SaveButton.Disabled = true;
        };

        CreateRoleButton.OnPressed += _ =>
        {
            var button = new NpcJobButton();
            button.JobName = Loc.GetString("new-npc-job-name");

            var sameCount = _dirtyButtons.Count(x => x.JobName == button.JobName);

            if (sameCount > 0)
                button.JobName = $"{button.JobName} {sameCount + 1}";

            _dirtyButtons.Add(button);
            SaveButton.Disabled = false;
            AddJobButton(button);
        };
    }

    public void EnsureSetup()
    {
        _routine = _entity.System<RoutineNpcTasksSystem>();
        _routine.OnJobChanged += _ => Build();

        Build();
    }

    public void Build()
    {
        JobsContainer.RemoveAllChildren();
        TasksContainer.RemoveAllChildren();

        _dirtyButtons.Clear();
        _deleteJobs.Clear();

        SaveButton.Disabled = true;

        foreach (var (_, data) in _routine.JobsData)
        {
            var button = new NpcJobButton(data);
            AddJobButton(button);
        }
    }

    private void BuildTasks(NpcJobButton button)
    {
        TasksContainer.RemoveAllChildren();

        var jobData = _routine.JobsData.GetValueOrDefault(button.JobId);
        var tasks = button.Tasks ?? jobData?.Tasks ?? new();
        var sortedTasks = _routine.TasksData
            .Select(x => x.Value)
            .OrderBy(x =>
            {
                var hsl = Color.ToHsl(x.Color);
                return hsl.X * 1000000 + hsl.Y * 1000 + hsl.Z;
            })
            .ToList();

        foreach (var task in sortedTasks)
        {
            var taskButton = new NpcTaskButton(task);
            taskButton.CheckBox.Pressed = tasks.Contains(task.TaskId);
            taskButton.CheckBox.Disabled = jobData?.Preset ?? false;

            taskButton.CheckBox.OnPressed += _ =>
            {
                button.Tasks ??= _routine.JobsData.GetValueOrDefault(button.JobId)?.Tasks ?? new();

                if (taskButton.CheckBox.Pressed)
                    button.Tasks.Add(task.TaskId);
                else
                    button.Tasks.Remove(task.TaskId);

                _dirtyButtons.Add(button);
                SaveButton.Disabled = false;
            };

            TasksContainer.AddChild(taskButton);
        }
    }

    private void AddJobButton(NpcJobButton button)
    {
        button.Group = _jobButtonGroup;
        button.Pressed = button.JobId == _selectedJob;

        if (button.Pressed)
            BuildTasks(button);

        button.OnDataChanged += () =>
        {
            _dirtyButtons.Add(button);
            SaveButton.Disabled = false;
        };

        button.OnDeleted += () =>
        {
            _dirtyButtons.Remove(button);
            _deleteJobs.Add(button.JobId);
            SaveButton.Disabled = false;
        };

        button.OnPressed += _ =>
        {
            _selectedJob = button.JobId;
            BuildTasks(button);
        };

        JobsContainer.AddChild(button);
    }
}

