using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class NpcJobsPopCell : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public NpcJobsPopCell()
    {
        RobustXamlLoader.Load(this);
    }

    public NpcJobsPopCell(EntityUid uid)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Icon.SetEntity(uid);

        if (_entity.TryGetComponent(uid, out MetaDataComponent? comp))
            Name.Text = comp.EntityName;
    }
}

