using Content.Shared._RF.NPC;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class NpcJobButton : Button
{
    public event Action? OnDataChanged;
    public event Action? OnDeleted;

    public int JobId { get; }

    public string JobName
    {
        get => NameLabel.Text ?? string.Empty;
        set
        {
            NameLabel.Text = value;
            NameEdit.Text = value;
        }
    }

    public string IconPath => Icon.CurrentTexturePath ?? string.Empty;

    public List<string>? Tasks;

    public NpcJobButton()
    {
        RobustXamlLoader.Load(this);
        EnsureSetup();
    }

    public NpcJobButton(NpcJobData job)
    {
        RobustXamlLoader.Load(this);

        JobId = job.Id;
        JobName = job.Name;

        if (job.IconPath != null)
            Icon.SetTexture(job.IconPath);

        EditNameButton.Visible = !job.Preset;
        DeleteButton.Visible = !job.Preset;
        Icon.Disabled = job.Preset;

        EnsureSetup();
    }

    private void EnsureSetup()
    {
        Icon.OnTextureChanged += _ => OnDataChanged?.Invoke();

        EditNameButton.OnPressed += _ =>
        {
            LabelContainer.Visible = false;
            NameEdit.Visible = true;
            NameEdit.SelectionStart = 0;
            NameEdit.CursorPosition = NameEdit.Text.Length;
        };

        NameEdit.OnTextEntered += _ =>
        {
            LabelContainer.Visible = true;
            NameEdit.Visible = false;
            JobName = NameEdit.Text;
            OnDataChanged?.Invoke();
        };

        DeleteButton.OnPressed += _ =>
        {
            OnDeleted?.Invoke();
            Parent?.RemoveChild(this);
        };
    }
}

