using System.Linq;
using Content.Client._RF.NPC;
using Content.Client.UserInterface.Controls;
using Content.Shared._RF.World;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class NpcJobsPriorityWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private RoutineNpcTasksSystem _routineNpc = default!;

    public NpcJobsPriorityWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        JobSettingsButton.OnPressed += _ => UserInterfaceManager
            .GetUIController<NpcJobsUiController>()
            .ToggleSettingsWindow();
    }

    public void EnsureSetup()
    {
        _routineNpc = _entity.System<RoutineNpcTasksSystem>();

        _routineNpc.OnJobChanged += _ =>
        {
            if (IsOpen)
                BuildTable();
        };

        BuildTable();
    }

    public override void Close()
    {
        Table.ClearAll();
        UserInterfaceManager
            .GetUIController<NpcJobsUiController>()
            .SettingsWindow?.Close();
        base.Close();
    }

    public void BuildTable()
    {
        Table.ClearAll();

        var headers = new List<Control> { new() };
        var orderedData = _routineNpc.JobsData
            .OrderBy(x => x.Value.Name)
            .ToList();

        foreach (var (_, data) in orderedData)
        {
            var label = new Label
            {
                Text = data.Name,
                MinWidth = 30f,
                Align = Label.AlignMode.Center,
                HorizontalExpand = true,
            };

            headers.Add(label);
        }

        Table.CreateRow(headers);

        if (!_entity.TryGetComponent(_player.LocalEntity, out RimFortressPlayerComponent? player))
            return;

        foreach (var uid in player.Pops)
        {
            var cells = new List<Control> { new NpcJobsPopCell(uid) };

            foreach (var (id, _) in orderedData)
            {
                var button = new NpcJobPriorityButton
                {
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    MaxValue = _routineNpc.GetMaxPriority(uid),
                };

                button.Priority = _routineNpc.GetPriority(uid, id);
                button.OnPriorityChanged += value =>
                    _routineNpc.ChangeJobPriority(uid, id, value);

                cells.Add(button);
            }

            Table.CreateRow(cells);
        }

        Table.InvalidateMeasure();
    }
}

