using System.Linq;
using Content.Client._RF.UserInterface.Controllers;
using Content.Client.UserInterface.Controls;
using Content.Shared._RF.NPC.Components;
using Content.Shared._RF.NPC.Systems;
using Content.Shared._RF.World.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class NpcJobsPriorityWindow : FancyWindow
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;

    private NpcJobsSystem _npcJobs = default!;

    public NpcJobsPriorityWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        JobSettingsButton.OnPressed += _ => UserInterfaceManager
            .GetUIController<NpcJobsUiController>()
            .ToggleSettingsWindow();
    }

    public void EnsureSetup()
    {
        _npcJobs = _entity.System<NpcJobsSystem>();
        _npcJobs.OnJobChanged += _ =>
        {
            if (IsOpen)
                BuildTable();
        };

        BuildTable();
    }

    public override void Close()
    {
        Table.ClearAll();
        UserInterfaceManager
            .GetUIController<NpcJobsUiController>()
            .SettingsWindow?.Close();
        base.Close();
    }

    public void BuildTable()
    {
        Table.ClearAll();

        if (!_entity.TryGetComponent(_player.LocalEntity, out RimFortressPlayerComponent? player)
            || !_entity.TryGetComponent(_player.LocalEntity, out NpcJobsComponent? jobs))
            return;

        var headers = new List<Control> { new() };
        var orderedData = jobs.Jobs
            .OrderBy(x => x.Name)
            .ToList();

        foreach (var job in orderedData)
        {
            var label = new Label
            {
                Text = job.Name,
                MinWidth = 30f,
                Align = Label.AlignMode.Center,
                HorizontalExpand = true,
            };

            headers.Add(label);
        }

        Table.CreateRow(headers);

        foreach (var uid in player.Pops)
        {
            var cells = new List<Control> { new NpcJobsPopCell(uid) };

            foreach (var job in orderedData)
            {
                var button = new NpcJobPriorityButton
                {
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    MaxValue = jobs.MaxPriority,
                    Priority = _npcJobs.GetPriority(uid, job.Id),
                };

                button.OnPriorityChanged += value =>
                    _npcJobs.SetJobPriority(uid, job.Id, value);

                cells.Add(button);
            }

            Table.CreateRow(cells);
        }

        Table.InvalidateMeasure();
    }
}

