using Content.Shared._RF.NPC.UtilityAi.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class NpcTaskButton : Control
{
    public NpcTaskButton()
    {
        RobustXamlLoader.Load(this);
    }

    public NpcTaskButton(ProtoId<UtilityAiGoalPrototype> protoId)
    {
        RobustXamlLoader.Load(this);
        var proto = IoCManager.Resolve<IPrototypeManager>().Index(protoId);

        Label.Text = proto.Name;
        Label.ModulateSelfOverride = proto.Color;
    }
}

