using Content.Shared._RF.NPC;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class NpcTaskButton : Control
{
    public NpcTaskButton()
    {
        RobustXamlLoader.Load(this);
    }

    public NpcTaskButton(NpcTaskData task)
    {
        RobustXamlLoader.Load(this);

        ToolTip = task.Description;
        Label.Text = task.TaskName;
        Label.ModulateSelfOverride = task.Color;
    }
}

