using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class TableCell : BoxContainer
{
    private readonly TableControl _table = default!;

    public int Column;
    public int Row;

    public TableCell()
    {
        RobustXamlLoader.Load(this);
    }

    public TableCell(TableControl table, int  column, int row)
    {
        RobustXamlLoader.Load(this);
        _table = table;
        Column = column;
        Row = row;
    }

    protected override void ChildAdded(Control child)
    {
        base.ChildAdded(child);
        _table.MarkLayoutDirty();
    }

    protected override void ChildRemoved(Control child)
    {
        base.ChildRemoved(child);
        _table.MarkLayoutDirty();
    }
}

