using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.NpcJobs;

[GenerateTypedNameReferences]
public sealed partial class TableSeparator : Control
{
    public TableSeparator()
    {
        RobustXamlLoader.Load(this);
    }
}

