using System.Linq;
using System.Numerics;
using Content.Shared._RF.NPC;
using Content.Shared.Input;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RF.NPC.UI;

[Virtual]
[GenerateTypedNameReferences]
public partial class AiDevWindowTab : Control
{
    /// <summary>
    /// The base size of the graph's nodes.
    /// </summary>
    [PublicAPI]
    public Vector2 NodeSize { get; set; } = new(100f);

    /// <summary>
    /// The size of the expanded node (when the middle mouse button is clicked on it).
    /// </summary>
    [PublicAPI]
    public Vector2 ExpandedNodeSize { get; set; } = new(1200, 700);

    /// <summary>
    /// The minimum possible zoom level for the graph.
    /// </summary>
    [PublicAPI]
    public float MinZoom { get; set; } = 0.6f;

    /// <summary>
    /// The maximum possible zoom level for the graph.
    /// </summary>
    [PublicAPI]
    public float MaxZoom { get; set; } = 1.4f;

    /// <summary>
    /// How fast the zoom level will change.
    /// </summary>
    [PublicAPI]
    public float ZoomStep { get; set; } = 0.1f;

    protected readonly Dictionary<int, Control> NodeControls = new();

    protected Control? Expanded;

    protected GraphLayout? Layout;
    protected float Zoom = 1.0f;

    private int? _nextLayoutUpdate;

    public AiDevWindowTab()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = Content.Children;

        LayoutContainer.SetAnchorAndMarginPreset(SearchPanel, LayoutContainer.LayoutPreset.TopRight, margin: 50);

        Search.OnTextChanged += args =>
        {
            var nodes = NodeControls
                .Where(x => x.Value is DebugNodeControl node && node.SearchValid(args.Text))
                .ToList();

            SelectNodes(nodes
                .Select(x => x.Key)
                .ToHashSet());

            CenterOnNodes(nodes.Select(x => x.Value).ToList());
        };
    }

    [PublicAPI]
    public void UpdateLayout()
    {
        if (Layout == null)
            return;

        var layout = Layout.Value.Scaled(Zoom);
        GraphRoot.MinSize = layout.TotalSize;

        foreach (var (id, control) in NodeControls)
        {
            if (!layout.Nodes.TryGetValue(id, out var placement)
                || control == Expanded)
                continue;

            LayoutContainer.SetPosition(control, placement.Position);
            control.SetSize = placement.Size;
        }

        OnUpdateLayout(layout);
    }

    protected virtual void OnUpdateLayout(GraphLayout layout) { }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        if (Layout == null)
        {
            args.Handle();
            return;
        }

        var delta = args.Delta;
        var zoomChange = delta.Y > 0 ? ZoomStep : -ZoomStep;
        var newZoom = Math.Clamp(Zoom + zoomChange, MinZoom, MaxZoom);

        // Cursor position relative to the scroll viewport - not the whole tab, and not its
        // center. This is the exact point that has to stay fixed under the cursor across the
        // zoom change, so it has to be measured relative to the control that actually scrolls.
        var cursorInViewport = args.RelativePosition - ScrollContainer.Position;

        // The content-space point currently under the cursor, at the OLD zoom. Has to be
        // computed before Zoom/UpdateLayout() changes anything.
        var cursorContentPoint = (ScrollContainer.GetScrollValue() + cursorInViewport) / Zoom;

        Zoom = newZoom;
        UpdateLayout();

        // Re-derive the scroll value that puts that same content-space point back under the
        // cursor at the NEW zoom - this is what actually makes the zoom track the cursor
        // instead of the viewport center.
        var newScroll = cursorContentPoint * Zoom - cursorInViewport;
        ScrollContainer.SetScrollValue(newScroll);

        args.Handle();
    }

    protected void SelectNodes(HashSet<int> ids)
    {
        foreach (var (nodeId, control) in NodeControls)
        {
            control.Modulate = ids.Contains(nodeId) ? Color.White : Color.White.WithAlpha(0.30f);
        }
    }

    protected void DeselectNodes()
    {
        foreach (var (_, control) in NodeControls)
        {
            control.Modulate = Color.White;
        }
    }

    protected void ExpandNode(int id)
    {
        if (!NodeControls.TryGetValue(id, out var control))
            return;

        UnExpandNode();
        control.SetSize = ExpandedNodeSize;
        GraphRoot.RemoveChild(control);
        ExpandedContainer.AddChild(control);
        Expanded = control;
    }

    protected void UnExpandNode()
    {
        if (Expanded == null)
            return;

        ExpandedContainer.RemoveChild(Expanded);
        GraphRoot.AddChild(Expanded);
        Expanded.SetSize = NodeSize;
        Expanded = null;
        _nextLayoutUpdate = 2; // I love RT UI
    }

    protected void ToggleExpanded(int id)
    {
        if (Expanded == null)
            ExpandNode(id);
        else
            UnExpandNode();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_nextLayoutUpdate == null)
            return;

        _nextLayoutUpdate--;

        if (_nextLayoutUpdate > 0)
            return;

        _nextLayoutUpdate = null;
        UpdateLayout();
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != ContentKeyFunctions.TextFind)
            return;

        SearchPanel.Expanded = true;
        UserInterfaceManager.GrabKeyboardFocus(Search);
    }

    protected void CenterOnNodes(IReadOnlyCollection<Control> nodes)
    {
        if (nodes.Count == 0)
            return;

        if (nodes.Count == 1)
        {
            CenterOnNode(nodes.First());
            return;
        }

        var graphRootOffset = GraphRoot.Position + ScrollContainer.GetScrollValue();

        var min = new Vector2(float.MaxValue, float.MaxValue);
        var max = new Vector2(float.MinValue, float.MinValue);

        foreach (var node in nodes)
        {
            var topLeft = graphRootOffset + node.Position;
            var bottomRight = topLeft + node.Size;

            min = Vector2.Min(min, topLeft);
            max = Vector2.Max(max, bottomRight);
        }

        var boundsCenter = (min + max) / 2f;
        var targetOffset = boundsCenter - ScrollContainer.Size / 2f;
        ScrollContainer.SetScrollValue(targetOffset);
    }

    protected void CenterOnNode(Control node)
    {
        var graphRootOffset = GraphRoot.Position + ScrollContainer.GetScrollValue();
        var nodeCenter = graphRootOffset + node.Position + node.Size / 2f;
        var targetOffset = nodeCenter - ScrollContainer.Size / 2f;
        ScrollContainer.SetScrollValue(targetOffset);
    }
}

