using Content.Shared._RF.NPC.GOAP.Components;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;
using Robust.Shared.Timing;

namespace Content.Client._RF.NPC.UI;

[GenerateTypedNameReferences]
public sealed partial class AiDevWindow : Control
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    private readonly AiDevWindowUiController _aiController;

    public EntityUid? Target { get; private set; }

    public AiDevWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(GoapDebugTab, "GOAP");
        TabContainer.SetTabTitle(UtilityAiDebugTab, "Utility AI");

        _aiController = UserInterfaceManager.GetUIController<AiDevWindowUiController>();
        _aiController.OnGoapDebugInfo += args =>
        {
            Target = args.Target;
            Refresh.Disabled = false;
            UpdateInfo();
            GoapDebugTab.Update(args.Target, args.Graph, args.Plan);
        };

        _aiController.OnUtilityAiDebugInfo += args =>
        {
            Target = args.Target;
            Refresh.Disabled = false;
            UpdateInfo();
            UtilityAiDebugTab.Update(args.Info);
        };

        Refresh.OnPressed += _ => SetTarget(Target!.Value);
    }

    public void SetTarget(EntityUid target)
    {
        _aiController.RequestGoapDebug(target);
        _aiController.RequestUtilityAiDebug(target);
    }

    private void UpdateInfo()
    {
        TargetLabel.Text = $"Target: {_entity.ToPrettyString(Target)}";
        TimeLabel.Text = $"CurTime: {_timing.CurTime.ToString()}";
        TickLabel.Text = $"CurTick: {_timing.CurTick.Value}";
    }
}

[UsedImplicitly]
internal sealed class AiWindowCommand : LocalizedCommands
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public override string Command => "aidevwindow";

    public override void Execute(IConsoleShell shell, string argStr, string[] args)
    {
        if (args.Length != 1)
        {
            shell.WriteError(Loc.GetString($"shell-need-exactly-one-argument"));
            return;
        }

        if (!_entManager.TryParseNetEntity(args[0], out var uid))
        {
            shell.WriteError(Loc.GetString("shell-entity-uid-must-be-number"));
            return;
        }

        var window = new OSWindow { Title = "AI Debug Window" };
        var control = new AiDevWindow();

        window.AddChild(control);
        window.Show();

        control.SetTarget(uid.Value);
    }

    public override CompletionResult GetCompletion(IConsoleShell shell, string[] args)
    {
        return args.Length != 1
            ? CompletionResult.Empty
            : CompletionResult.FromHintOptions(CompletionHelper.Components<GoapComponent>(args[0]), "NPC uid");
    }
}
