using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.UI;

[Virtual]
[GenerateTypedNameReferences]
public partial class DebugNodeControl : Control
{
    public DebugNodeControl()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = Content.Children;
    }
}

