using Content.Client._RF.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.UI;

[Virtual]
[GenerateTypedNameReferences]
public partial class DebugNodeControl : Control
{
    private bool _selected;

    public DebugNodeControl()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = Content.Children;

        OnMouseEntered += _ => _selected = true;
        OnMouseExited += _ => _selected = false;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        if (_selected)
        {
            var box = UIBox2.FromDimensions(Vector2i.Zero, PixelSize).Scale(1.01f);
            handle.DrawRect(box, StyleFortress.GoldFortress);
        }

        base.Draw(handle);
    }
}

