using System.Linq;
using Content.Client._RF.Stylesheets;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.UI;

[Virtual]
[GenerateTypedNameReferences]
public partial class DebugNodeControl : Control
{
    private bool _selected;

    protected HashSet<string> SearchText = new();

    public DebugNodeControl()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = Content.Children;

        OnMouseEntered += _ => _selected = true;
        OnMouseExited += _ => _selected = false;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        if (_selected)
        {
            var box = UIBox2.FromDimensions(-Vector2i.One, PixelSize + Vector2i.One * 2);
            handle.DrawRect(box, StyleFortress.GoldFortress, filled: false);
        }

        base.Draw(handle);
    }

    [PublicAPI]
    public bool SearchValid(string searchText)
        => SearchText.Any(x => x.Contains(searchText, StringComparison.InvariantCultureIgnoreCase));
}

