- type: npcTask
  id: Drink
  name: Drink
  parent: BaseSoloPerformTask
  compound: DrinkCompound
  targetKey: PickUpTarget
  targetsQuery: Drink
  startPreconditions:
  - !type:ThirstyPrecondition
    minThirstState: Parched
  finishPreconditions:
  - !type:NotPrecondition
    precondition: !type:ThirstyPrecondition
      minThirstState: Parched
