- type: npcTask
  id: Eat
  name: Eat
  parent: BaseSoloPerformTask
  compound: EatCompound
  targetKey: PickUpTarget
  targetsQuery: Food
  startPreconditions:
  - !type:HungryPrecondition
    minHungerState: Starving
  finishPreconditions:
  - !type:NotPrecondition
    precondition: !type:HungryPrecondition
      minHungerState: Starving
