- type: npcTask
  id: PickUp
  name: Take it
  parent: BaseSoloPerformTask
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-solid.svg.192dpi.png
  compound: PickUpCompound
  targetKey: PickUpTarget
  targetWhitelist:
    components:
      - Item
  startPreconditions:
    - !type:ActiveHandEntityIsPrecondition
      targetKey: PickUpTarget
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: PickUpTarget
        - !type:ActiveHandEntityIsPrecondition
          targetKey: PickUpTarget

- type: npcTask
  id: TakeOwnership
  name: Take ownership
  parent: BaseSoloPerformTask
  overlayColor: "#075967"
  verbIcon: /Textures/_RF/Interface/VerbIcons/house-flag-solid-full.svg.192dpi.png
  compound: TakeOwnershipCompound
  passive: true
  targetWhitelist:
    components:
      - Item
  startPreconditions:
    - !type:OwnedPrecondition
      targetKey: Target
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:OwnedPrecondition
          targetKey: Target

- type: npcTask
  id: Pry
  name: Open
  parent: BaseSoloPerformTask
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/left-right-solid.svg.192dpi.png
  compound: PryCompound
  tempKeys:
    - PickUpTarget
    - ToolQuality
  targetWhitelist:
    components:
      - Door
  startPreconditions:
    - !type:DoorStatePrecondition
      key: Target
      state: Closed
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:DoorStatePrecondition
          key: Target
          state: Closed
          invert: true

- type: npcTask
  id: FreeHandInteract
  name: Interact
  parent: BaseSoloPerformTask
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-pointer-solid.svg.192dpi.png
  compound: FreeHandInteractCompound
  targetWhitelist:
    requireAll: false
    components:
      - Strap
      - Door
    tags:
      - HandGatherable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target
