- type: npcTask
  id: FreeHandInteract
  name: Interact
  parent: BaseSoloPerformTask
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-pointer-solid.svg.192dpi.png
  compound: FreeHandInteractCompound
  targetWhitelist:
    requireAll: false
    components:
    - Strap
    - Door
    tags:
    - HandGatherable
  finishPreconditions:
  - !type:OrPrecondition
    preconditions:
    - !type:KeyNotExistsPrecondition
      key: Target
    - !type:EntityDeletedPrecondition
      key: Target

- type: htnCompound
  id: FreeHandInteractCompound
  branches:
  # Drop the item in hand
  - preconditions:
    - !type:ActiveHandEntityPrecondition
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:DropOperator

  - tasks:
    - !type:HTNCompoundTask
      task: InteractCompound
    # Remove the key to signify the completion of the task.
    # I guess that's the normal solution?
    - !type:HTNPrimitiveTask
      operator: !type:RemoveKeyOperator
        key: Target
