- type: npcTask
  id: MoveTo
  name: Go to the target place
  parent: BaseNpcTask
  overlayColor: "#D3D3D3"
  compound: MoveToCompound
  finishPreconditions:
  - !type:CoordinatesInRangePrecondition
    targetKey: TargetCoordinates
    rangeKey: MoveToCloseRange
