- type: npcTask
  id: MentalBreakdown
  name: Mental breakdown
  parent: BaseSoloPerformTask
  compound: MentalBreakdownCompound
  targetsQuery: Self # Stub for the ability to use this task as a passive
  startPreconditions:
  - !type:MoodPrecondition
    lessThan: -60
  - !type:RandomPrecondition
    chance: 0.1 # Adding randomness to the triggering of this task
  finishPreconditions:
  - !type:HasMoodEffectPrecondition
    effect: MoodMentalBreakdown
    invert: true

- type: npcTask
  id: StartConversation
  name: Conversation
  parent: BaseNpcTask
  overlayColor: "#D3D3D3"
  compound: StartConversationCompound
  targetsQuery: Self # Stub for the ability to use this task as a passive
  finishPreconditions:
  - !type:InConversationPrecondition

- type: npcTask
  id: LeaveSettlement
  name: Leave Settlement
  parent: BaseSoloPerformTask
  compound: LeaveSettlementCompound
  targetsQuery: Self # Stub for the ability to use this task as a passive
  startPreconditions:
  - !type:MoodPrecondition
    lessThan: -80
  - !type:RandomPrecondition
    chance: 0.1 # Adding randomness to the triggering of this task
  finishPreconditions:
  - !type:InRangeFromSettlementsPrecondition
    range: 100
    invert: true
