- type: npcTask
  id: Storing
  name: Storing
  maxPerformers: 1
  unionPerformersWith:
    - MoveStoredInContainer
    - FixStoredOffset
    - MoveToSuppliedStock
  overlayColor: "#A16C2B"
  verbIcon: /Textures/_RF/Interface/cubes-solid.svg.192dpi.png
  compound: StoringCompound
  onFinish: RfIdleCompound
  targetKey: PickUpTarget
  tempKeys:
    - Container
    - SupplyingOnly
    - SupplyingStartStock
  targetsQuery: StoringTaskTarget
  targetWhitelist:
    components:
      - Item
      - Pullable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:StoredPrecondition
          targetKey: PickUpTarget
        - !type:EntityDeletedPrecondition
          key: PickUpTarget
    - !type:PulledEntityIsPrecondition
      targetKey: PickUpTarget
      invert: true

- type: npcTask
  id: MoveStoredInContainer
  name: Move stored items into crates
  maxPerformers: 1
  unionPerformersWith:
    - Storing
    - FixStoredOffset
    - MoveToSuppliedStock
  overlayColor: "#A16C2B"
  verbIcon: /Textures/_RF/Interface/cubes-solid.svg.192dpi.png
  compound: MoveStoredInContainerCompound
  onFinish: RfIdleCompound
  targetKey: PickUpTarget
  tempKeys:
    - Container
    - SupplyingOnly
    - SupplyingStartStock
  targetsQuery: MoveStoredInContainerTarget
  targetWhitelist:
    components:
      - Item
  startPreconditions:
    - !type:StockpileFreeContainerPrecondition
      targetKey: PickUpTarget
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: PickUpTarget
        - !type:AndPrecondition
          preconditions:
            - !type:StoredPrecondition
              targetKey: PickUpTarget
            - !type:TargetInContainerPrecondition
              targetKey: PickUpTarget

- type: npcTask
  id: FixStoredOffset
  name: Correct the position of stored
  maxPerformers: 1
  unionPerformersWith:
    - Storing
    - MoveStoredInContainer
    - MoveToSuppliedStock
  overlayColor: "#8d622d"
  verbIcon: /Textures/_RF/Interface/cubes-solid.svg.192dpi.png
  compound: FixStoredOffsetCompound
  onFinish: RfIdleCompound
  targetKey: PickUpTarget
  tempKeys:
    - Container
    - SupplyingOnly
    - SupplyingStartStock
  targetsQuery: FixStoredOffsetTarget
  targetWhitelist:
    components:
      - Item
      - Pullable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: PickUpTarget
        - !type:AndPrecondition
          preconditions:
            - !type:StoredPrecondition
              targetKey: PickUpTarget
            - !type:TileOffsetPrecondition
              targetKey: PickUpTarget
              lessThan: 0.06

- type: npcTask
  id: MoveToSuppliedStock
  name: Move stored between stockpiles
  maxPerformers: 1
  unionPerformersWith:
    - Storing
    - MoveStoredInContainer
    - FixStoredOffset
  overlayColor: "#8d622d"
  verbIcon: /Textures/_RF/Interface/cubes-solid.svg.192dpi.png
  compound: MoveToSuppliedStockCompound
  onFinish: RfIdleCompound
  targetKey: PickUpTarget
  tempKeys:
    - Container
    - SupplyingOnly
    - SupplyingStartStock
  targetsQuery: MoveToSuppliedStockTarget
  targetWhitelist:
    components:
      - Item
      - Pullable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: PickUpTarget
        - !type:AndPrecondition
          preconditions:
            - !type:StoredPrecondition
              targetKey: PickUpTarget
            - !type:CanInsertInSuppliedPrecondition
              targetKey: PickUpTarget
              invert: true
