- type: npcTask
  id: MoveTo
  name: Go here
  overlayColor: "#D3D3D3"
  compound: MoveToCompound
  onFinish: RfIdleCompound
  finishPreconditions:
    - !type:CoordinatesInRangePrecondition
      targetKey: TargetCoordinates
      rangeKey: MoveToCloseRange

- type: npcTask
  id: Attack
  name: Attack
  overlayColor: "#FF0000"
  verbIcon: /Textures/_RF/Interface/VerbIcons/skull-crossbones-solid.svg.192dpi.png
  verbOnly: true
  compound: AttackTargetCompound
  onFinish: RfIdleCompound
  passive: true
  tempKeys:
    - Item
  targetWhitelist:
    components:
      - HTN
  startPreconditions:
    - !type:MobStatePrecondition
      targetKey: Target
      state: Dead
      invert: true
    - !type:IsFriendlyPrecondition
      targetKey: Target
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:MobStatePrecondition
          targetKey: Target
          state: Alive
          invert: true
        - !type:MobStatePrecondition
          targetKey: Owner
          state: Alive
          invert: true
        - !type:IsFriendlyPrecondition
          targetKey: Target

- type: npcTask
  id: PickUp
  name: Take it
  maxPerformers: 1
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-solid.svg.192dpi.png
  compound: PickUpCompound
  onFinish: RfIdleCompound
  targetKey: PickUpTarget
  targetWhitelist:
    components:
      - Item
  startPreconditions:
    - !type:ActiveHandEntityIsPrecondition
      targetKey: PickUpTarget
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: PickUpTarget
        - !type:ActiveHandEntityIsPrecondition
          targetKey: PickUpTarget

- type: npcTask
  id: Pry
  name: Open
  maxPerformers: 1
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/left-right-solid.svg.192dpi.png
  compound: PryCompound
  onFinish: RfIdleCompound
  tempKeys:
    - PickUpTarget
    - ToolQuality
  targetWhitelist:
    components:
      - Door
  startPreconditions:
    - !type:DoorStatePrecondition
      key: Target
      state: Closed
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:DoorStatePrecondition
          key: Target
          state: Closed
          invert: true

- type: npcTask
  id: Build
  name: Build
  maxPerformers: 1
  overlayColor: "#FFFF00"
  verbIcon: /Textures/_RF/Interface/hammer-solid.svg.192dpi.png
  compound: BuildCompound
  onFinish: RfIdleCompound
  tempKeys:
    - ItemEntityTarget
    - MaterialTarget
    - MaterialInsertAmount
    - TagsTarget
    - AllTagsRequired
    - ToolQualityTarget
    - ToolFuelTarget
    - ComponentTarget
  targetWhitelist:
    components:
      - Construction
  startPreconditions:
    - !type:ConstructionFinishedPrecondition
      key: Target
      invert: true
  finishPreconditions:
    - !type:ConstructionFinishedPrecondition
      key: Target

- type: npcTask
  id: Dig
  name: Dig
  maxPerformers: 1
  overlayColor: "#E36414"
  verbIcon: /Textures/_RF/Interface/VerbIcons/person-digging-solid.svg.192dpi.png
  compound: DigCompound
  onFinish: RfIdleCompound
  passive: true
  tempKeys:
    - Tags
    - AllTags
    - PickUpTarget
  targetWhitelist:
    tags:
      - Diggable
  finishPreconditions:
    - !type:EntityDeletedPrecondition
      key: Target

- type: npcTask
  id: FreeHandInteract
  name: Interact
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-pointer-solid.svg.192dpi.png
  compound: FreeHandInteractCompound
  onFinish: RfIdleCompound
  targetWhitelist:
    tags:
      - HandGatherable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target

- type: npcTask
  id: Heal
  name: Heal
  overlayColor: "#16C934"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-holding-medical-solid.svg.192dpi.png
  verbOnly: true
  selfPerform: true
  compound: HealCompound
  onFinish: RfIdleCompound
  tempKeys:
    - PickUpTarget
    - DamageType
    - DamageContainer
  targetWhitelist:
    components:
      - Damageable
      - HTN
  startPreconditions:
    - !type:MobStatePrecondition
      targetKey: Target
      state: Dead
      invert: true
    - !type:OrPrecondition
      preconditions:
        - !type:BleedingPrecondition
          targetKey: Target
        - !type:TotalDamagePrecondition
          targetKey: Target
          moreThan: 5.0
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:AndPrecondition
          preconditions:
            - !type:BleedingPrecondition
              targetKey: Target
              invert: true
            - !type:TotalDamagePrecondition
              targetKey: Target
              lessThan: 10.0
        # Doctor, we've lost him
        - !type:MobStatePrecondition
          targetKey: Target
          state: Dead
