- type: npcTask
  id: BaseNpcTask
  abstract: true
  onFinish: RfIdleCompound

- type: npcTask
  id: BaseSoloPerformTask
  parent: BaseNpcTask
  abstract: true
  maxPerformers: 1

- type: npcTask
  id: MoveTo
  name: Go here
  parent: BaseNpcTask
  overlayColor: "#D3D3D3"
  compound: MoveToCompound
  finishPreconditions:
  - !type:CoordinatesInRangePrecondition
    targetKey: TargetCoordinates
    rangeKey: MoveToCloseRange

- type: npcTask
  id: Attack
  name: Attack
  parent: BaseNpcTask
  overlayColor: "#FF0000"
  verbIcon: /Textures/_RF/Interface/VerbIcons/skull-crossbones-solid.svg.192dpi.png
  verbOnly: true
  compound: AttackTargetCompound
  passive: true
  failAwaitTime: 100
  tempKeys:
  - Item
  targetWhitelist:
    components:
    - HTN
  startPreconditions:
  - !type:MobStatePrecondition
    targetKey: Target
    state: Alive
  - !type:IsFriendlyPrecondition
    targetKey: Target
    invert: true
  finishPreconditions:
  - !type:OrPrecondition
    preconditions:
    - !type:EntityDeletedPrecondition
      key: Target
    - !type:MobStatePrecondition
      targetKey: Target
      state: Alive
      invert: true
    - !type:MobStatePrecondition
      targetKey: Owner
      state: Alive
      invert: true
    - !type:IsFriendlyPrecondition
      targetKey: Target

- type: npcTask
  id: Raid
  name: Raid
  parent: BaseNpcTask
  overlayColor: "#FF0000"
  compound: RaidCompound
  finishPreconditions:
  - !type:MobStatePrecondition
    targetKey: Owner
    state: Alive
    invert: true

- type: npcTask
  id: Dig
  name: Dig
  parent: BaseNpcTask
  maxPerformers: 1
  overlayColor: "#E36414"
  verbIcon: /Textures/_RF/Interface/VerbIcons/person-digging-solid.svg.192dpi.png
  compound: DigCompound
  passive: true
  failAwaitTime: 3
  tempKeys:
  - Tags
  - AllTags
  - PickUpTarget
  targetWhitelist:
    tags:
    - Diggable
  finishPreconditions:
  - !type:EntityDeletedPrecondition
    key: Target

- type: npcTask
  id: Heal
  name: Heal
  parent: BaseNpcTask
  overlayColor: "#16C934"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-holding-medical-solid.svg.192dpi.png
  verbOnly: true
  selfPerform: true
  compound: HealCompound
  tempKeys:
  - PickUpTarget
  - DamageType
  - DamageContainer
  targetWhitelist:
    components:
    - Damageable
    - HTN
  startPreconditions:
  - !type:MobStatePrecondition
    targetKey: Target
    state: Dead
    invert: true
  - !type:OrPrecondition
    preconditions:
    - !type:BleedingPrecondition
      targetKey: Target
    - !type:TotalDamagePrecondition
      targetKey: Target
      moreThan: 5.0
  finishPreconditions:
  - !type:OrPrecondition
    preconditions:
    - !type:EntityDeletedPrecondition
      key: Target
    - !type:AndPrecondition
      preconditions:
      - !type:BleedingPrecondition
        targetKey: Target
        invert: true
      - !type:TotalDamagePrecondition
        targetKey: Target
        lessThan: 5.0
    # Doctor, we've lost him
    - !type:MobStatePrecondition
      targetKey: Target
      state: Dead

- type: npcTask
  id: Chop
  name: Chop down
  parent: BaseNpcTask
  maxPerformers: 1
  overlayColor: "#452615"
  verbIcon: /Textures/_RF/Interface/VerbIcons/tree-solid.svg.192dpi.png
  compound: ChopCompound
  passive: true
  tempKeys:
  - PickUpTarget
  targetWhitelist:
    tags:
    - Tree
  finishPreconditions:
  - !type:EntityDeletedPrecondition
    key: Target
