- type: npcTask
  id: MoveTo
  name: Go here
  overlayColor: "#D3D3D3"
  compound: MoveToCompound
  onFinish: RfIdleCompound
  finishPreconditions:
    - !type:CoordinatesInRangePrecondition
      targetKey: TargetCoordinates
      rangeKey: MoveToCloseRange

- type: npcTask
  id: Attack
  name: Attack
  overlayColor: "#FF0000"
  verbIcon: /Textures/_RF/Interface/VerbIcons/skull-crossbones-solid.svg.192dpi.png
  verbOnly: true
  compound: AttackTargetCompound
  onFinish: RfIdleCompound
  passive: true
  tempKeys:
    - Item
  targetWhitelist:
    components:
      - HTN
  startPreconditions:
    - !type:MobStatePrecondition
      targetKey: Target
      state: Alive
    - !type:IsFriendlyPrecondition
      targetKey: Target
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:MobStatePrecondition
          targetKey: Target
          state: Alive
          invert: true
        - !type:MobStatePrecondition
          targetKey: Owner
          state: Alive
          invert: true
        - !type:IsFriendlyPrecondition
          targetKey: Target

- type: npcTask
  id: PickUp
  name: Take it
  maxPerformers: 1
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-solid.svg.192dpi.png
  compound: PickUpCompound
  onFinish: RfIdleCompound
  targetKey: PickUpTarget
  targetWhitelist:
    components:
      - Item
  startPreconditions:
    - !type:ActiveHandEntityIsPrecondition
      targetKey: PickUpTarget
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: PickUpTarget
        - !type:ActiveHandEntityIsPrecondition
          targetKey: PickUpTarget

- type: npcTask
  id: Pry
  name: Open
  maxPerformers: 1
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/left-right-solid.svg.192dpi.png
  compound: PryCompound
  onFinish: RfIdleCompound
  tempKeys:
    - PickUpTarget
    - ToolQuality
  targetWhitelist:
    components:
      - Door
  startPreconditions:
    - !type:DoorStatePrecondition
      key: Target
      state: Closed
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:DoorStatePrecondition
          key: Target
          state: Closed
          invert: true

- type: npcTask
  id: Build
  name: Build
  maxPerformers: 1
  overlayColor: "#FFFF00"
  verbIcon: /Textures/_RF/Interface/hammer-solid.svg.192dpi.png
  compound: BuildCompound
  onFinish: RfIdleCompound
  tempKeys:
    - PickUpTarget
    - Amount
  targetsQuery: BuildTaskTarget
  targetWhitelist:
    components:
      - Construction
  startPreconditions:
    - !type:ConstructionFinishedPrecondition
      key: Target
      invert: true
  finishPreconditions:
    - !type:ConstructionFinishedPrecondition
      key: Target

# In fact, the only thing this task does is set the path in the graph to disassembly.
# The NPC then automatically switches to the construction task via routine tasks.
# Otherwise we would get NPC conflict for construction
- type: npcTask
  id: Deconstruct
  name: Deconstruct
  maxPerformers: 1
  overlayColor: "#945A1C"
  verbIcon: /Textures/_RF/Interface/VerbIcons/trowel-bricks-solid.svg.192dpi.png
  verbOnly: true
  compound: DeconstructionCompound
  onFinish: RfIdleCompound
  passive: true
  targetWhitelist:
    components:
      - Construction
  startPreconditions:
    # We dont want deconstruct items for now
    - !type:HasComponentPrecondition
      targetKey: Target
      components:
        - type: Item
      invert: true
    - !type:DeconstructionPrecondition
      key: Target
  finishPreconditions:
    - !type:DeconstructionStartedPrecondition
      targetKey: Target

- type: npcTask
  id: Dig
  name: Dig
  maxPerformers: 1
  overlayColor: "#E36414"
  verbIcon: /Textures/_RF/Interface/VerbIcons/person-digging-solid.svg.192dpi.png
  compound: DigCompound
  onFinish: RfIdleCompound
  passive: true
  tempKeys:
    - Tags
    - AllTags
    - PickUpTarget
  targetWhitelist:
    tags:
      - Diggable
  finishPreconditions:
    - !type:EntityDeletedPrecondition
      key: Target

- type: npcTask
  id: FreeHandInteract
  name: Interact
  maxPerformers: 1
  overlayColor: "#00D5FF"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-pointer-solid.svg.192dpi.png
  compound: FreeHandInteractCompound
  onFinish: RfIdleCompound
  targetWhitelist:
    requireAll: false
    components:
      - Strap
      - Door
    tags:
      - HandGatherable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target

- type: npcTask
  id: Heal
  name: Heal
  overlayColor: "#16C934"
  verbIcon: /Textures/_RF/Interface/VerbIcons/hand-holding-medical-solid.svg.192dpi.png
  verbOnly: true
  selfPerform: true
  compound: HealCompound
  onFinish: RfIdleCompound
  tempKeys:
    - PickUpTarget
    - DamageType
    - DamageContainer
  targetWhitelist:
    components:
      - Damageable
      - HTN
  startPreconditions:
    - !type:MobStatePrecondition
      targetKey: Target
      state: Dead
      invert: true
    - !type:OrPrecondition
      preconditions:
        - !type:BleedingPrecondition
          targetKey: Target
        - !type:TotalDamagePrecondition
          targetKey: Target
          moreThan: 5.0
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:AndPrecondition
          preconditions:
            - !type:BleedingPrecondition
              targetKey: Target
              invert: true
            - !type:TotalDamagePrecondition
              targetKey: Target
              lessThan: 5.0
        # Doctor, we've lost him
        - !type:MobStatePrecondition
          targetKey: Target
          state: Dead

- type: npcTask
  id: Plant
  name: Plant
  maxPerformers: 1
  overlayColor: "#1A9927"
  verbIcon: /Textures/_RF/Interface/VerbIcons/seedling-solid.svg.192dpi.png
  compound: PlantingCompound
  onFinish: RfIdleCompound
  tempKeys:
    - PickUpTarget
  targetsQuery: PlantTaskTarget
  targetWhitelist:
    components:
      - PlantHolder
  startPreconditions:
    - !type:PlantHolderFilledPrecondition
      targetKey: Target
      invert: true
  finishPreconditions:
    - !type:PlantHolderFilledPrecondition
      targetKey: Target

- type: npcTask
  id: Chop
  name: Chop down
  maxPerformers: 1
  overlayColor: "#452615"
  verbIcon: /Textures/_RF/Interface/VerbIcons/tree-solid.svg.192dpi.png
  compound: ChopCompound
  onFinish: RfIdleCompound
  passive: true
  tempKeys:
    - PickUpTarget
  targetWhitelist:
    tags:
      - Tree
  finishPreconditions:
    - !type:EntityDeletedPrecondition
      key: Target
