- type: npcTask
  id: MoveTo
  overlayColor: "#D3D3D3"
  priority: -100
  compound: MoveToCompound
  onFinish: BaseFinishCompound
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: TargetCoordinates
        - !type:CoordinatesInRangePrecondition
          targetKey: TargetCoordinates
          rangeKey: MoveToCloseRange

- type: npcTask
  id: Attack
  overlayColor: "#FF0000"
  compound: AttackTargetCompound
  onFinish: BaseFinishCompound
  startWhitelist:
    components:
      - HTN
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:MobStatePrecondition
          targetKey: Target
          state: Alive
          invert: true
        - !type:MobStatePrecondition
          targetKey: Owner
          state: Alive
          invert: true
        - !type:IsFriendlyPrecondition
          targetKey: Target

- type: npcTask
  id: PickUp
  overlayColor: "#00D5FF"
  compound: PickUpCompound
  onFinish: BaseFinishCompound
  startWhitelist:
    components:
      - Item
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:ActiveHandEntityIsPrecondition
          targetKey: Target

- type: npcTask
  id: Pry
  overlayColor: "#00D5FF"
  compound: PryCompound
  onFinish: PryFinishCompound
  priority: 10
  startWhitelist:
    components:
      - Door
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:DoorStatePrecondition
          key: Target
          state: Closed
          invert: true

- type: npcTask
  id: Build
  overlayColor: "#FFFF00"
  compound: BuildCompound
  onFinish: BuildFinishCompound
  priority: 11
  startWhitelist:
    components:
      - Construction
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:ConstructionFinishedPrecondition
          key: Target

- type: npcTask
  id: Dig
  overlayColor: "#E36414"
  compound: DigCompound
  onFinish: BaseFinishCompound
  startWhitelist:
    tags:
      - Diggable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target

- type: npcTask
  id: FreeHandInteract
  overlayColor: "#00D5FF"
  compound: FreeHandInteractCompound
  onFinish: BaseFinishCompound
  startWhitelist:
    tags:
      - HandGatherable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target
