- type: npcTask
  id: MoveTo
  overlayColor: "#D3D3D3"
  priority: -100
  compound: MoveToCompound
  onFinish: IdleCompound
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: TargetCoordinates
        - !type:CoordinatesInRangePrecondition
          targetKey: TargetCoordinates
          rangeKey: MoveToCloseRange

- type: npcTask
  id: Attack
  overlayColor: "#FF0000"
  compound: AttackTargetCompound
  onFinish: IdleCompound
  tempKeys:
    - Item
  targetWhitelist:
    components:
      - HTN
  startPreconditions:
    - !type:MobStatePrecondition
      targetKey: Target
      state: Dead
      invert: true
    - !type:IsFriendlyPrecondition
      targetKey: Target
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:MobStatePrecondition
          targetKey: Target
          state: Alive
          invert: true
        - !type:MobStatePrecondition
          targetKey: Owner
          state: Alive
          invert: true
        - !type:IsFriendlyPrecondition
          targetKey: Target

- type: npcTask
  id: PickUp
  maxPerformers: 1
  overlayColor: "#00D5FF"
  compound: PickUpCompound
  onFinish: IdleCompound
  targetKey: PickUpTarget
  targetWhitelist:
    components:
      - Item
  startPreconditions:
    - !type:ActiveHandEntityIsPrecondition
      targetKey: PickUpTarget
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: PickUpTarget
        - !type:EntityDeletedPrecondition
          key: PickUpTarget
        - !type:ActiveHandEntityIsPrecondition
          targetKey: PickUpTarget

- type: npcTask
  id: Pry
  maxPerformers: 1
  overlayColor: "#00D5FF"
  compound: PryCompound
  onFinish: IdleCompound
  priority: 10
  tempKeys:
    - PickUpTarget
    - ToolQuality
  targetWhitelist:
    components:
      - Door
  startPreconditions:
    - !type:DoorStatePrecondition
      key: Target
      state: Closed
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:DoorStatePrecondition
          key: Target
          state: Closed
          invert: true

- type: npcTask
  id: Build
  maxPerformers: 1
  overlayColor: "#FFFF00"
  compound: BuildCompound
  onFinish: IdleCompound
  priority: 11
  tempKeys:
    - ItemEntityTarget
    - MaterialTarget
    - MaterialInsertAmount
    - TagsTarget
    - AllTagsRequired
    - ToolQualityTarget
    - ToolFuelTarget
    - ComponentTarget
  targetWhitelist:
    components:
      - Construction
  startPreconditions:
    - !type:ConstructionFinishedPrecondition
      key: Target
      invert: true
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:ConstructionFinishedPrecondition
          key: Target

- type: npcTask
  id: Dig
  maxPerformers: 1
  overlayColor: "#E36414"
  compound: DigCompound
  onFinish: IdleCompound
  tempKeys:
    - Tags
    - AllTags
    - PickUpTarget
  targetWhitelist:
    tags:
      - Diggable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target

- type: npcTask
  id: FreeHandInteract
  overlayColor: "#00D5FF"
  compound: FreeHandInteractCompound
  onFinish: IdleCompound
  targetWhitelist:
    tags:
      - HandGatherable
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target

- type: npcTask
  id: Heal
  overlayColor: "#16C934"
  selfPerform: true
  compound: HealCompound
  onFinish: IdleCompound
  tempKeys:
    - PickUpTarget
    - DamageType
    - DamageContainer
  targetWhitelist:
    components:
      - Damageable
      - HTN
  startPreconditions:
    - !type:MobStatePrecondition
      targetKey: Target
      state: Dead
      invert: true
    - !type:TotalDamagePrecondition
      targetKey: Target
      moreThan: 5.0
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:EntityDeletedPrecondition
          key: Target
        - !type:AndPrecondition
          preconditions:
            - !type:BleedingPrecondition
              targetKey: Target
              invert: true
            - !type:TotalDamagePrecondition
              targetKey: Target
              lessThan: 10.0
        # Doctor, we've lost him
        - !type:MobStatePrecondition
          targetKey: Target
          state: Dead
