- type: npcTask
  id: MoveTo
  overlayColor: "#D3D3D3FF"
  compound: MoveToCompound
  onFinish: BaseFinishCompound
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: TargetCoordinates
        - !type:CoordinatesInRangePrecondition
          targetKey: TargetCoordinates
          rangeKey: MoveToCloseRange

- type: npcTask
  id: Attack
  overlayColor: "#FF0000FF"
  compound: AttackTargetCompound
  onFinish: BaseFinishCompound
  startWhitelist:
    components:
      - HTN
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:MobStatePrecondition
          targetKey: Target
          state: Alive
          invert: true

- type: npcTask
  id: PickUp
  overlayColor: "#00D5FFFF"
  compound: PickUpCompound
  onFinish: BaseFinishCompound
  startWhitelist:
    components:
      - Item
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:ActiveHandEntityIsPrecondition
          targetKey: Target

- type: npcTask
  id: Pry
  overlayColor: "#00D5FFFF"
  compound: PryCompound
  onFinish: BaseFinishCompound
  priority: 10
  startWhitelist:
    components:
      - Prying
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        # TODO: pry precondition

- type: npcTask
  id: Build
  overlayColor: "#FFFF00FF"
  compound: BuildCompound
  onFinish: BuildFinishCompound
  priority: 11
  startWhitelist:
    components:
      - Construction
  finishPreconditions:
    - !type:OrPrecondition
      preconditions:
        - !type:KeyNotExistsPrecondition
          key: Target
        - !type:ConstructionFinishedPrecondition
          key: Target
