using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._RF.Zoning.Components;
using Content.Shared._RF.Zoning.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class BaseZoneWindow : FancyWindow
{
    [Dependency] private IEntityManager _entity = default!;

    private readonly ZoningUiController _controller;
    private readonly ZoningSystem _zoning;
    private Entity<ZoneComponent>? _zone;

    public BaseZoneWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _zoning = _entity.System<ZoningSystem>();
        _controller = UserInterfaceManager.GetUIController<ZoningUiController>();

        Tab.SetTabTitle(0, Loc.GetString("base-zone-window-visuals-tab-general-title"));
        Tab.SetTabTitle(1, Loc.GetString("base-zone-window-visuals-tab-visuals-title"));
        Tab.OnTabChanged += ind =>
        {
            if (ind == 1)
                VisualsControl.SetZone(_zone);
        };
    }

    public void Open(Entity<ZoneComponent> ent)
    {
        Open();
        _zone = ent;
        _controller.SelectZone(ent);

        if (_entity.TryGetComponent(ent, out MetaDataComponent? meta)
            && meta.EntityPrototype != null)
            Title = meta.EntityPrototype.Name;

        Tab.SetTabVisible(1, _entity.TryGetComponent(ent, out ZoneVisualsComponent? comp) && comp.Editable);

        BottonPanel.SetZone(ent);
        NameChange.SetZone(ent);
        VisualsControl.SetZone(ent);
        UpdateContent();
    }

    private void UpdateContent()
    {
        ContentBox.Content.RemoveAllChildren();

        if (!(_zone?.Comp.Entities.Count > 0))
            return;

        ContentBox.Visible = true;

        var contents = _zone.Value.Comp.Entities
            .Where(uid => _entity.HasComponent<MetaDataComponent>(uid))
            .Select(uid => new Entity<MetaDataComponent>(uid, _entity.GetComponent<MetaDataComponent>(uid)))
            .GroupBy(x => x.Comp.EntityName)
            .Select(x => x.ToHashSet())
            .ToList();

        foreach (var group in contents)
        {
            ContentBox.Content.AddChild(new ZoneContentControl(group.First(), group.Count));
        }
    }

    public override void Close()
    {
        base.Close();
        _controller.DeselectZone(_zone?.Owner);
        _zone = null;
        VisualsControl.ResetVisuals();
        ContentBox.Visible = false;
        ContentBox.CollapseAll();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _zoning.OnZoneUpdated += OnZoneUpdate;
        _zoning.OnZoneDeleted += OnZoneDelete;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _zoning.OnZoneUpdated -= OnZoneUpdate;
        _zoning.OnZoneDeleted -= OnZoneDelete;
    }

    private void OnZoneUpdate(Entity<ZoneComponent> ent)
    {
        if (ent == _zone)
            UpdateContent();
    }

    private void OnZoneDelete(Entity<ZoneComponent> ent)
    {
        if (ent == _zone)
            Close();
    }
}

