using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._RF.Zoning.Components;
using Content.Shared._RF.Zoning.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class BaseZoneWindow : FancyWindow
{
    [Dependency] private IEntityManager _entity = default!;

    private readonly ZoningUiController _controller;
    private readonly ZoningSystem _zoning;
    private Entity<ZoneComponent>? _zone;
    private Dictionary<ZoneVisualsState, ZoneVisualsStyle> _originalVisuals = new();

    public BaseZoneWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _zoning = _entity.System<ZoningSystem>();
        _controller = UserInterfaceManager.GetUIController<ZoningUiController>();

        _zoning.OnZoneUpdated += OnZoneUpdate;

        // Naming

        EditButton.OnPressed += _ =>
        {
            if (!_entity.TryGetComponent(_zone, out MetaDataComponent? meta))
                return;

            NameBox.Visible = false;
            NameEditBox.Visible = true;
            NameEdit.Text = meta.EntityName;
        };

        ApplyNameButton.OnPressed += _ =>
        {
            NameBox.Visible = true;
            NameEditBox.Visible = false;

            if (_zone == null)
                return;

            NameLabel.Text = NameEdit.Text;
            _controller.SetName(_zone.Value, NameEdit.Text);
        };

        CancelNameButton.OnPressed += _ =>
        {
            NameBox.Visible = true;
            NameEditBox.Visible = false;
        };

        // Bottom panel

        ExpandButton.OnPressed += _ =>
        {
            if (_zone != null)
                _controller.AddTileSelection(_zone.Value);
        };

        ShrinkButton.OnPressed += _ =>
        {
            if (_zone != null)
                _controller.RemoveTileSelection(_zone.Value);
        };

        DeleteButton.OnPressed += _ =>
        {
            if (_zone == null)
                return;

            _controller.DeleteZone(_zone.Value);
            Close();
        };

        // Visuals

        SaveVisualsButton.OnPressed += _ =>
        {
            VisualChangesBox.Visible = false;

            if (!_entity.TryGetComponent(_zone, out ZoneVisualsComponent? visuals))
                return;

            _controller.SetVisuals(_zone.Value, visuals.States);
        };

        ResetVisualsButton.OnPressed += _ =>
        {
            VisualChangesBox.Visible = false;

            if (_entity.HasComponent<ZoneVisualsComponent>(_zone))
                _controller.SetVisuals(_zone.Value, _originalVisuals);

            UpdateVisuals();
        };
    }

    public void Open(Entity<ZoneComponent> ent)
    {
        Open();
        _zone = ent;
        _controller.SelectZone(ent);

        if (_entity.TryGetComponent(ent, out MetaDataComponent? meta)
            && meta.EntityPrototype != null)
        {
            NameLabel.Text = meta.EntityName;
            Title = meta.EntityPrototype.Name;
        }

        UpdateContent();
        UpdateVisuals();
    }

    private void UpdateContent()
    {
        ContentBox.Content.RemoveAllChildren();

        if (!(_zone?.Comp.Entities.Count > 0))
            return;

        ContentBox.Visible = true;

        var contents = _zone.Value.Comp.Entities
            .Where(uid => _entity.HasComponent<MetaDataComponent>(uid))
            .Select(uid => new Entity<MetaDataComponent>(uid, _entity.GetComponent<MetaDataComponent>(uid)))
            .GroupBy(x => x.Comp.EntityName)
            .Select(x => x.ToHashSet())
            .ToList();

        foreach (var group in contents)
        {
            ContentBox.Content.AddChild(new ZoneContentControl(group.First(), group.Count));
        }
    }

    private void UpdateVisuals()
    {
        VisualsBox.RemoveAllChildren();
        _originalVisuals.Clear();

        if (_entity.TryGetComponent(_zone, out ZoneVisualsComponent? visuals) && visuals.Editable)
        {
            _originalVisuals = new(visuals.States);
            VisualsExpand.Visible = true;
            ContentDivider.Visible = ContentBox.Visible;

            for (var i = ZoneVisualsComponent.PriorityOrder.Length - 1; i >= 0; i--)
            {
                var state = ZoneVisualsComponent.PriorityOrder[i];
                var control = new ZoneVisualsLayerControl(state,
                    visuals.States.TryGetValue(state, out var s) ? s : null);

                control.OnStyleAdded += style =>
                {
                    visuals.States[state] = style;
                    VisualChangesBox.Visible = true;
                };

                control.OnStyleRemoved += _ =>
                {
                    visuals.States.Remove(state);
                    VisualChangesBox.Visible = true;
                };

                control.OnStyleChanged += style =>
                {
                    visuals.States[state] = style;
                    VisualChangesBox.Visible = true;
                };

                VisualsBox.AddChild(control);
            }
        }
        else
            VisualsExpand.Visible = false;
    }

    public override void Close()
    {
        base.Close();
        _controller.DeselectZone(_zone?.Owner);
        _zone = null;

        if (_entity.HasComponent<ZoneVisualsComponent>(_zone))
            _controller.SetVisuals(_zone.Value, _originalVisuals);

        VisualsExpand.Visible = false;
        ContentBox.Visible = false;
        ContentDivider.Visible = false;
        ContentBox.CollapseAll();
        VisualsExpand.CollapseAll();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _zoning.OnZoneUpdated -= OnZoneUpdate;
    }

    private void OnZoneUpdate(Entity<ZoneComponent> ent)
    {
        if (ent != _zone)
            return;

        Open(ent);
    }
}

