using Content.Shared._RF.Zoning.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneVisualsLayerControl : Control
{
    public ZoneVisualsStyle Style;

    public event Action<ZoneVisualsStyle>? OnStyleChanged;
    public event Action<ZoneVisualsStyle>? OnStyleAdded;
    public event Action<ZoneVisualsStyle>? OnStyleRemoved;

    public ZoneVisualsLayerControl()
    {
        RobustXamlLoader.Load(this);
    }

    public ZoneVisualsLayerControl(ZoneVisualsState state, ZoneVisualsStyle? style)
    {
        RobustXamlLoader.Load(this);
        Style = style != null ? new(style.Value) : new();

        LayerExpand.Title = Loc.GetString("zone-visuals-state", ("state", state.ToString().ToLowerInvariant()));
        LayerEnableButton.Pressed = SettingsBox.Visible = style != null;

        LayerEnableButton.OnPressed += args =>
        {
            SettingsBox.Visible = args.Button.Pressed;

            if (args.Button.Pressed)
                OnStyleAdded?.Invoke(Style);
            else
                OnStyleRemoved?.Invoke(Style);
        };

        BorderColorButton.Pressed = BorderColor.Visible = Style.BorderColor != null;
        BorderColor.Color = Style.BorderColor ?? Color.Transparent;

        BorderColorButton.OnPressed += args =>
        {
            BorderColor.Visible = args.Button.Pressed;
            BorderColor.Color = Style.BorderColor ?? Color.Transparent;
            Style.BorderColor = args.Button.Pressed ? BorderColor.Color : null;
            OnStyleChanged?.Invoke(Style);
        };

        BorderColor.OnColorChanged += color =>
        {
            Style.BorderColor = color;
            OnStyleChanged?.Invoke(Style);
        };

        ZoneColorButton.Pressed = ZoneColor.Visible = Style.ZoneColor != null;
        ZoneColor.Color = Style.ZoneColor ?? Color.Transparent;

        ZoneColorButton.OnPressed += args =>
        {
            ZoneColor.Visible = args.Button.Pressed;
            ZoneColor.Color = Style.ZoneColor ?? Color.Transparent;
            Style.ZoneColor = args.Button.Pressed ? ZoneColor.Color : null;
            OnStyleChanged?.Invoke(Style);
        };

        ZoneColor.OnColorChanged += color =>
        {
            Style.ZoneColor = color;
            OnStyleChanged?.Invoke(Style);
        };

        ShowTileBordersButton.OnPressed += args =>
        {
            Style.ShowTileBorders = args.Button.Pressed ? true : null;
            OnStyleChanged?.Invoke(Style);
        };

        ShowConditionsButton.OnPressed += args =>
        {
            Style.ShowConditions = args.Button.Pressed ? true : null;
            OnStyleChanged?.Invoke(Style);
        };
    }
}

