using Content.Shared._RF.Zoning.Components;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneChangeTileControl : Control
{
    private Entity<ZoneComponent>? _zone;

    public ZoneChangeTileControl()
    {
        RobustXamlLoader.Load(this);

        var controller = UserInterfaceManager.GetUIController<ZoningUiController>();

        ExpandButton.OnPressed += _ =>
        {
            if (_zone != null)
                controller.AddTileSelection(_zone.Value);
        };

        ShrinkButton.OnPressed += _ =>
        {
            if (_zone != null)
                controller.RemoveTileSelection(_zone.Value);
        };

        DeleteButton.OnPressed += _ =>
        {
            if (_zone == null)
                return;

            controller.DeleteZone(_zone.Value);
        };
    }


    [PublicAPI]
    public void SetZone(Entity<ZoneComponent>? zone)
    {
        _zone = zone;
    }
}

