using Content.Shared._RF.Zoning.Components;
using Content.Shared._RF.Zoning.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneVisualsControl : Control
{
    [Dependency] private IEntityManager _entity = default!;

    private readonly ZoningSystem _zoning;
    private readonly ZoningUiController _controller;
    private EntityUid? _zone;
    private Dictionary<ZoneVisualsState, ZoneVisualsStyle> _originalVisuals = new();

    public ZoneVisualsControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _zoning = _entity.System<ZoningSystem>();
        _zoning.OnZoneUpdated += OnZoneUpdate;
        _controller = UserInterfaceManager.GetUIController<ZoningUiController>();

        SaveVisualsButton.OnPressed += _ =>
        {
            VisualChangesBox.Visible = false;

            if (!_entity.TryGetComponent(_zone, out ZoneVisualsComponent? visuals))
                return;

            _controller.SetVisuals(_zone.Value, visuals.States);
            _originalVisuals = new(visuals.States);
        };

        ResetVisualsButton.OnPressed += _ =>
        {
            ResetVisuals();
            UpdateVisuals();
        };
    }

    [PublicAPI]
    public void SetZone(EntityUid? zone)
    {
        _zone = zone;
        UpdateVisuals();
    }

    [PublicAPI]
    public void ResetVisuals()
    {
        VisualChangesBox.Visible = false;

        if (_entity.HasComponent<ZoneVisualsComponent>(_zone))
            _controller.SetVisuals(_zone.Value, _originalVisuals);
    }

    private void UpdateVisuals()
    {
        VisualsBox.RemoveAllChildren();
        _originalVisuals.Clear();

        if (!_entity.TryGetComponent(_zone, out ZoneVisualsComponent? visuals) || !visuals.Editable)
            return;

        _originalVisuals = new(visuals.States);

        for (var i = ZoneVisualsComponent.PriorityOrder.Length - 1; i >= 0; i--)
        {
            var state = ZoneVisualsComponent.PriorityOrder[i];
            var control = new ZoneVisualsLayerControl(state,
                visuals.States.TryGetValue(state, out var s) ? s : null);

            control.OnStyleAdded += style =>
            {
                visuals.States[state] = style;
                VisualChangesBox.Visible = true;
            };

            control.OnStyleRemoved += _ =>
            {
                visuals.States.Remove(state);
                VisualChangesBox.Visible = true;
            };

            control.OnStyleChanged += style =>
            {
                visuals.States[state] = style;
                VisualChangesBox.Visible = true;
            };

            VisualsBox.AddChild(control);
        }
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _zoning.OnZoneUpdated -= OnZoneUpdate;
    }

    private void OnZoneUpdate(Entity<ZoneComponent> ent)
    {
        if (ent == _zone)
            UpdateVisuals();
    }
}

