using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneCreationWidget : UIWidget
{
    public ZoneCreationWidget()
    {
        RobustXamlLoader.Load(this);
    }
}

