using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneContentControl : Control
{
    public ZoneContentControl()
    {
        RobustXamlLoader.Load(this);
    }

    public ZoneContentControl(Entity<MetaDataComponent> ent, int amount)
    {
        RobustXamlLoader.Load(this);

        SpriteView.SetEntity(ent);
        Label.Text = Loc.GetString("zone-content-name-label", ("name", ent.Comp.EntityName), ("amount", amount));
    }
}

