using System.Linq;
using Content.Shared._RF.Zoning.Components;
using Content.Shared._RF.Zoning.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneConditionsList : Control
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IEyeManager _eye = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly ZoningSystem _zoning;
    private Entity<ZoneComponent>? _trackingZone;

    public ZoneConditionsList()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        LabelText.OutlineColorOverride = TextOutline.Default.Color;
        LabelText.OutlineThicknessOverride = 2f;

        _zoning = _entity.System<ZoningSystem>();
    }

    [PublicAPI]
    public void SetZone(Entity<ZoneComponent> ent)
    {
        LabelText.Visible = true;
        Conditions.RemoveAllChildren();
        _trackingZone = null;
        var descriptions = _zoning.ConditionDescription(ent);

        if (descriptions.All(x => x.IsMet))
            return;

        foreach (var desc in descriptions)
        {
            Conditions.AddChild(new ZoneConditionControl(desc));
        }

        _trackingZone = ent;
        Reposition();
    }

    [PublicAPI]
    public void SetTile(Entity<ZoneComponent> ent, TileRef tile)
    {
        LabelText.Visible = false;
        Conditions.RemoveAllChildren();
        _trackingZone = null;
        var descriptions = _zoning.TileAddConditionsDescription(ent, tile);

        if (descriptions.All(x => x.IsMet))
            return;

        foreach (var desc in descriptions)
        {
            Conditions.AddChild(new ZoneConditionControl(desc));
        }
    }

    [PublicAPI]
    public void SetTile(EntProtoId<ZoneComponent> protoId, TileRef tile)
    {
        LabelText.Visible = false;
        Conditions.RemoveAllChildren();
        _trackingZone = null;

        if (!_proto.Resolve(protoId, out var proto)
            || !proto.TryComp(out ZoneComponent? comp, _entity.ComponentFactory))
            return;

        var descriptions = _zoning.TileAddConditionsDescription(comp, tile);

        if (descriptions.All(x => x.IsMet))
            return;

        foreach (var desc in descriptions)
        {
            Conditions.AddChild(new ZoneConditionControl(desc));
        }
    }

    private void Reposition()
    {
        if (_trackingZone == null)
            return;

        var center = _zoning.ZoneCenter(_trackingZone.Value);
        var screen = _eye.CoordinatesToScreen(center).Position / UIScale;
        var offset = DesiredSize / 2;
        LayoutContainer.SetPosition(this, screen - offset);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        Reposition();
    }
}

