using System.Numerics;
using Content.Client._RF.Stylesheets;
using Content.Shared._RF.Zoning;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneConditionControl : Control
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IResourceCache _cache = default!;

    private const string IsMetTexture = "/Textures/_RF/Interface/check-solid.svg.192dpi.png";
    private const string NotMetTexture = "/Textures/_RF/Interface/Style/cross.png";

    public ZoneConditionControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public ZoneConditionControl(ZoneConditionDesc desc)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Text.OutlineColorOverride = TextOutline.Default.Color;
        Progress.OutlineColorOverride = TextOutline.Default.Color;
        Text.OutlineThicknessOverride = 2f;
        Progress.OutlineThicknessOverride = 2f;

        IsMetOutLine.TexturePath = desc.IsMet ? IsMetTexture : NotMetTexture;
        IsMet.TexturePath = desc.IsMet ? IsMetTexture : NotMetTexture;
        IsMetOutLine.ModulateSelfOverride = TextOutline.Default.Color;
        IsMet.ModulateSelfOverride = desc.IsMet ? StyleFortress.Good : StyleFortress.Bad;

        Text.Text = $"[bold]{desc.Text}[/bold]";
        Progress.Text = $"[bold]{desc.Progress}[/bold]";

        if (desc.EntIcon != null)
        {
            foreach (var protoId in desc.EntIcon)
            {
                var view = new EntityPrototypeView(protoId, _entity)
                {
                    SetSize = new Vector2(16f),
                    ToolTip = Loc.GetString(_proto.Index(protoId).Name),
                    TrackingTooltip = true,
                    TooltipDelay = 0,
                    MouseFilter = MouseFilterMode.Pass,
                };

                Textures.AddChild(view);
            }
        }

        if (desc.TileIcon == null)
            return;

        foreach (var tileId in desc.TileIcon)
        {
            if (!_proto.Resolve(tileId, out var proto)
                || proto.Sprite == null)
                continue;

            var res = _cache.GetResource<TextureResource>(proto.Sprite.Value);
            var texture = new TextureRect
            {
                Texture = res.Texture,
                SetSize = new Vector2(16f),
                Stretch = TextureRect.StretchMode.KeepAspectCovered,
                CanShrink = true,
                ToolTip = Loc.GetString(proto.Name),
                TrackingTooltip = true,
                TooltipDelay = 0,
                MouseFilter = MouseFilterMode.Pass,
            };
            Textures.AddChild(texture);
        }
    }
}

