using Content.Shared._RF.Zoning.Components;
using Content.Shared._RF.Zoning.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneChangeNameControl : Control
{
    [Dependency] private IEntityManager _entity = default!;

    private readonly ZoningSystem _zoning;
    private EntityUid? _zone;

    public ZoneChangeNameControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _zoning = _entity.System<ZoningSystem>();
        _zoning.OnZoneUpdated += OnZoneUpdate;
        var controller = UserInterfaceManager.GetUIController<ZoningUiController>();

        EditButton.OnPressed += _ =>
        {
            if (!_entity.TryGetComponent(_zone, out MetaDataComponent? meta))
                return;

            NameBox.Visible = false;
            NameEditBox.Visible = true;
            NameEdit.Text = meta.EntityName;
            UserInterfaceManager.GrabKeyboardFocus(NameEdit);
        };

        NameEdit.OnTextEntered += _ => SetName();
        ApplyNameButton.OnPressed += _ => SetName();

        NameEdit.OnFocusExit += _ => Cancel();
        CancelNameButton.OnPressed += _ => Cancel();

        return;

        void Cancel()
        {
            NameBox.Visible = true;
            NameEditBox.Visible = false;
        }

        void SetName()
        {
            NameBox.Visible = true;
            NameEditBox.Visible = false;

            if (_zone == null)
                return;

            NameLabel.Text = NameEdit.Text;
            controller.SetName(_zone.Value, NameEdit.Text);
        }
    }

    [PublicAPI]
    public void SetZone(EntityUid? zone)
    {
        _zone = zone;

        if (_entity.TryGetComponent(zone, out MetaDataComponent? meta)
            && meta.EntityPrototype != null)
            NameLabel.Text = meta.EntityName;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _zoning.OnZoneUpdated -= OnZoneUpdate;
    }

    private void OnZoneUpdate(Entity<ZoneComponent> ent)
    {
        if (ent != _zone)
            return;

        SetZone(_zone);
    }
}

