using Content.Client._RF.Stylesheets;
using Content.Shared._RF.Zoning;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Zoning.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ZoneConditionControl : Control
{
    private const string IsMetTexture = "/Textures/_RF/Interface/check-solid.svg.192dpi.png";
    private const string NotMetTexture = "/Textures/_RF/Interface/Style/cross.png";

    public ZoneConditionControl()
    {
        RobustXamlLoader.Load(this);
    }

    public ZoneConditionControl(IZoneConditionDesc desc)
    {
        RobustXamlLoader.Load(this);

        Text.OutlineColorOverride = TextOutline.Default.Color;
        Progress.OutlineColorOverride = TextOutline.Default.Color;
        Text.OutlineThicknessOverride = 2f;
        Progress.OutlineThicknessOverride = 2f;

        IsMetOutLine.TexturePath = desc.IsMet ? IsMetTexture : NotMetTexture;
        IsMet.TexturePath = desc.IsMet ? IsMetTexture : NotMetTexture;
        IsMetOutLine.ModulateSelfOverride = TextOutline.Default.Color;
        IsMet.ModulateSelfOverride = desc.IsMet ? StyleFortress.Good : StyleFortress.Bad;

        Text.Text = $"[bold]{desc.Text}[/bold]";
        Progress.Text = $"[bold]{desc.Progress}[/bold]";

        if (desc.SubDescriptions == null)
            return;

        foreach (var subDesc in desc.SubDescriptions)
        {
            SubDescriptions.AddChild(new ZoneConditionControl(subDesc));
        }
    }
}

