- type: entity
  id: BaseWorkshop
  abstract: true
  components:
  - type: Workshop
  - type: WorkshopVisuals
    itemsVisualStates:
      Empty: 0
      NotEmpty: 1
  - type: Appearance
  - type: Sprite
    layers:
    - state: base
      map: ["enum.WorkshopLayers.Base"]
    - state: items
      map: ["enum.WorkshopLayers.Items"]
      visible: false
    - state: crafting
      map: ["enum.WorkshopLayers.Crafting"]
      visible: false
  - type: GenericVisualizer
    visuals:
      enum.WorkshopVisuals.Items:
        enum.WorkshopLayers.Items:
          Empty: { visible: false }
          NotEmpty: { visible: true }
      enum.WorkshopVisuals.Crafting:
        enum.WorkshopLayers.Base:
          Idle: { state: base }
          Empty: { state: base_crafting }
          NotEmpty: { state: base_crafting }
        enum.WorkshopLayers.Crafting:
          Idle: { visible: false }
          Empty: { visible: false }
          NotEmpty: { visible: true }
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-0.5,0.5,0.5"
        density: 50
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: ActivatableUI
    key: enum.WorkshopUiKey.Key
    requiresComplex: false
  - type: UserInterface
    interfaces:
      enum.WorkshopUiKey.Key:
        type: WorkshopBoundUserInterface
  - type: Destructible
    thresholds:
    - trigger: # Excess damage, don't spawn entities
        !type:DamageTrigger
        damage: 200
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:DoActsBehavior
        acts: ["Breakage"]
      - !type:PlaySoundBehavior
        sound:
          collection: MetalBreak
  - type: EmptyOnMachineDeconstruct
    containers:
    - workshop_entity_container

- type: entity
  id: BaseWorkshop2States
  parent: BaseWorkshop
  abstract: true
  components:
  - type: WorkshopVisuals
    itemsVisualStates:
      Empty: 0
      Half: 6
      Full: 12
  - type: Sprite
    layers:
    - state: base
      map: ["enum.WorkshopLayers.Base"]
    - map: ["enum.WorkshopLayers.Items"]
      visible: false
    - map: ["enum.WorkshopLayers.Crafting"]
      visible: false
  - type: GenericVisualizer
    visuals:
      enum.WorkshopVisuals.Items:
        enum.WorkshopLayers.Items:
          Empty: { visible: false }
          Half: { visible: true, state: items_half }
          Full: { visible: true, state: items_full }
      enum.WorkshopVisuals.Crafting:
        enum.WorkshopLayers.Base:
          Idle: { state: base }
          Empty: { state: base_crafting }
          Half: { state: base_crafting }
          Full: { state: base_crafting }
        enum.WorkshopLayers.Crafting:
          Idle: { visible: false }
          Empty: { visible: false }
          Half: { visible: true, state: crafting_half }
          Full: { visible: true, state: crafting_full }

- type: entity
  id: BaseWorkshop3States
  parent: BaseWorkshop
  abstract: true
  components:
  - type: WorkshopVisuals
    itemsVisualStates:
      0: 0
      33: 4
      66: 8
      100: 12
  - type: Sprite
    layers:
    - state: base
      map: ["enum.WorkshopLayers.Base"]
    - map: ["enum.WorkshopLayers.Items"]
      visible: false
    - map: ["enum.WorkshopLayers.Crafting"]
      visible: false
  - type: GenericVisualizer
    visuals:
      enum.WorkshopVisuals.Items:
        enum.WorkshopLayers.Items:
          0: { visible: false }
          33: { visible: true, state: items_33 }
          66: { visible: true, state: items_66 }
          100: { visible: true, state: items_100 }
      enum.WorkshopVisuals.Crafting:
        enum.WorkshopLayers.Base:
          Idle: { state: base }
          0: { state: base_crafting }
          33: { state: base_crafting }
          66: { state: base_crafting }
          100: { state: base_crafting }
        enum.WorkshopLayers.Crafting:
          Idle: { visible: false }
          0: { visible: false }
          33: { visible: true, state: crafting_33 }
          66: { visible: true, state: crafting_66 }
          100: { visible: true, state: crafting_100 }

- type: entity
  id: BaseWorkshop4States
  parent: BaseWorkshop
  abstract: true
  components:
  - type: WorkshopVisuals
    itemsVisualStates:
      0: 0
      25: 3
      50: 6
      75: 9
      100: 12
  - type: Sprite
    layers:
    - state: base
      map: ["enum.WorkshopLayers.Base"]
    - map: ["enum.WorkshopLayers.Items"]
      visible: false
    - map: ["enum.WorkshopLayers.Crafting"]
      visible: false
  - type: GenericVisualizer
    visuals:
      enum.WorkshopVisuals.Items:
        enum.WorkshopLayers.Items:
          0: { visible: false }
          25: { visible: true, state: items_25 }
          50: { visible: true, state: items_50 }
          75: { visible: true, state: items_75 }
          100: { visible: true, state: items_100 }
      enum.WorkshopVisuals.Crafting:
        enum.WorkshopLayers.Base:
          Idle: { state: base }
          0: { state: base_crafting }
          25: { state: base_crafting }
          50: { state: base_crafting }
          75: { state: base_crafting }
          100: { state: base_crafting }
        enum.WorkshopLayers.Crafting:
          Idle: { visible: false }
          0: { visible: false }
          25: { visible: true, state: crafting_25 }
          50: { visible: true, state: crafting_50 }
          75: { visible: true, state: crafting_75 }
          100: { visible: true, state: crafting_100 }
