using System.Linq;
using Content.Shared._RF.Stockpile.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.UserInterface.Controls.Stockpile;

[GenerateTypedNameReferences]
public sealed partial class StockpileItemButton : Button
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<int>? OnSettingsChanged;

    private readonly bool _category;

    public int MaxValue
    {
        get;
        set
        {
            var val = field;
            field = value;

            Counter.Visible = !_category && field != -1;
            UnlimitedCheck.Pressed = field == -1;

            if (field != -1)
                Counter.Value = field;

            if (val == field)
                return;

            OnSettingsChanged?.Invoke(field);
        }
    }

    public StockpileItemButton()
    {
        RobustXamlLoader.Load(this);
    }

    public StockpileItemButton(StockpileCategoryPrototype proto, int count)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _category = true;
        var sprite = _entManager.System<SpriteSystem>();

        NameLabel.Text = count == 0 ? proto.Name : $"{proto.Name} ({count})";

        if (_prototype.TryIndex(proto.IconEntity, out var entProto))
        {
            Texture.Textures.AddRange(sprite
                .GetPrototypeTextures(entProto)
                .Select(x => x.Default));
        }
        else if (proto.Icon != null)
            Texture.Textures.Add(sprite.Frame0(proto.Icon));

        Counter.Visible = false;

        EnsureSetup();
    }

    public StockpileItemButton(EntityPrototype proto, int count)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Disabled = true;

        NameLabel.Text = string.IsNullOrEmpty(proto.EditorSuffix) ? proto.Name : $"{proto.Name} [{proto.EditorSuffix}]";
        NameLabel.Text = count == 0 ? NameLabel.Text : $"{NameLabel.Text} ({count})";

        Texture.Textures.AddRange(_entManager
            .System<SpriteSystem>()
            .GetPrototypeTextures(proto)
            .Select(x => x.Default));

        Counter.OnValueChanged += value => MaxValue = value.New;

        EnsureSetup();
    }

    private void EnsureSetup()
    {
        ToolTip = NameLabel.Text;

        UnlimitedCheck.OnPressed += _ =>
        {
            UnlimitedCheck.ToolTip = Loc.GetString(UnlimitedCheck.Pressed
                ? "stockpile-settings-menu-unlimited-checkbox-enabled-tooltip"
                : "stockpile-settings-menu-unlimited-checkbox-disabled-tooltip");

            MaxValue = UnlimitedCheck.Pressed ? -1 : 0;
        };
    }
}

