using Content.Shared._RF.Stockpile;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.UserInterface.Controls.Stockpile;

[GenerateTypedNameReferences]
public sealed partial class StockpileItemButton : Button
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<int>? OnSettingsChanged;

    private int _maxValue;

    public int MaxValue
    {
        get => _maxValue;
        set
        {
            if (_maxValue == value)
            {
                CountLine.Text = _maxValue.ToString();
                return;
            }

            _maxValue = value;

            if (_maxValue < -1)
                _maxValue = -1;

            ItemCountBox.Visible = _maxValue != -1;
            UnlimitedCheck.Pressed = _maxValue == -1;
            Minus.Disabled = _maxValue == 0;
            OnSettingsChanged?.Invoke(_maxValue);
            CountLine.Text = _maxValue.ToString();
        }
    }

    public StockpileItemButton()
    {
        RobustXamlLoader.Load(this);
    }

    public StockpileItemButton(StockpileCategoryPrototype proto, int count)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Label.Text = count == 0 ? proto.Name : $"{proto.Name} ({count})";

        if (proto.Icon != null)
            Texture.Texture = _entManager.System<SpriteSystem>().Frame0(proto.Icon);

        if (_prototype.TryIndex(proto.IconEntity, out var entProto))
            Texture.Texture = _entManager.System<SpriteSystem>().Frame0(entProto);

        EnsureSetup();
    }

    public StockpileItemButton(EntityPrototype proto, int count)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Disabled = true;

        Label.Text = string.IsNullOrEmpty(proto.EditorSuffix) ? proto.Name : $"{proto.Name} [{proto.EditorSuffix}]";
        Label.Text = count == 0 ? Label.Text : $"{Label.Text} ({count})";
        Texture.Texture = _entManager.System<SpriteSystem>().Frame0(proto);

        EnsureSetup();
    }

    private void EnsureSetup()
    {
        Plus.OnPressed += _ => MaxValue++;
        Minus.OnPressed += _ => MaxValue--;

        CountLine.OnTextChanged += args =>
            MaxValue = int.TryParse(args.Text, out var value) ? value : 0;

        UnlimitedCheck.OnPressed += _ =>
        {
            UnlimitedCheck.ToolTip = Loc.GetString(UnlimitedCheck.Pressed
                ? "stockpile-settings-menu-unlimited-checkbox-enabled-tooltip"
                : "stockpile-settings-menu-unlimited-checkbox-disabled-tooltip");

            MaxValue = UnlimitedCheck.Pressed ? -1 : 0;
        };
    }
}

