using System.Linq;
using Content.Client._RF.Stockpile;
using Content.Client._RF.UserInterface.Controllers;
using Content.Client.UserInterface.Controls;
using Content.Shared._RF.Stockpile;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._RF.UserInterface.Controls.Stockpile;

[GenerateTypedNameReferences]
public sealed partial class StockpileSettingsWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IComponentFactory _factory = default!;

    private const string StockTitlePrefix = "stockpile-label-prefix";

    [ValidatePrototypeId<EntityCategoryPrototype>]
    private readonly ProtoId<EntityCategoryPrototype> _doNotMapCategory = "DoNotMap";

    private readonly StockpileUiController _stockpileController;

    private StockpileCategoryPrototype? _currentCategory;

    private readonly Dictionary<StockpileCategoryPrototype, List<EntityPrototype>> _categoryItems = new();

    public StockpileSettingsWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _stockpileController = UserInterfaceManager.GetUIController<StockpileUiController>();

        _stockpileController.OnStockSelected += SetStock;
        _stockpileController.OnStockpileUpdated += id =>
        {
            if (Visible && _stockpileController.SettingStock?.Id == id)
                BuildItems(_currentCategory);
        };

        _stockpileController.OnSupplyRequested += supplied =>
        {
            if (_stockpileController.SettingStock is not { } stock)
                return;

            var stockpile = _entity.System<StockpileSystem>();

            if (stock.SuppliedStockpiles.ToList().Contains(supplied.Id))
                stockpile.RemoveSuppliedStock(stock, supplied);
            else
                stockpile.AddSuppliedStock(stock, supplied);
        };

        ExpandStockButton.OnPressed += _ =>
        {
            if (_stockpileController.SettingStock is { } stock)
                _stockpileController.AddTileSelection(stock);
        };
        ShrinkStockButton.OnPressed += _ =>
        {
            if (_stockpileController.SettingStock is { } stock)
                _stockpileController.RemoveTileSelection(stock);
        };
        DeleteStockButton.OnPressed += _ =>
        {
            if (_stockpileController.SettingStock == null)
                return;

            _entity.System<StockpileSystem>().DeleteStockpile(_stockpileController.SettingStock.Id);
            _stockpileController.SettingStock = null;
            Visible = false;
        };
        SuppliersButton.OnPressed += _ => _stockpileController.SelectMode = StockpileSelectionMode.Supply;

        Search.OnTextChanged += _ => BuildItems(_currentCategory);
        BackButton.OnPressed += _ =>
        {
            Search.Text = string.Empty;
            BuildItems(_currentCategory != null
                ? GetCategoryParent(_currentCategory)
                : null);
        };
        CloseButton.OnPressed += _ => Close();

        ColorPicker.OnColorChanged += color =>
        {
            if (_stockpileController.SettingStock is { } stock)
                _entity.System<StockpileSystem>().SetStockColor(stock, color);
        };

        _prototype.PrototypesReloaded += args =>
        {
            if (args.WasModified<EntityPrototype>()
                || args.WasModified<StockpileCategoryPrototype>())
                ReloadPrototypes();
        };
    }

    private void ReloadPrototypes()
    {
        _categoryItems.Clear();

        var doNotMap = _prototype.Index(_doNotMapCategory);

        foreach (var prototype in _prototype.EnumeratePrototypes<EntityPrototype>())
        {
            if (prototype.Abstract
                || prototype.HideSpawnMenu
                || prototype.Categories.Contains(doNotMap)
                || !prototype.TryGetComponent(out StockpileCategoryComponent? comp, _factory)
                || !_prototype.TryIndex(comp.Category, out var category))
                continue;

            _categoryItems.GetOrNew(category).Add(prototype);
        }
    }

    public override void Close()
    {
        base.Close();

        _stockpileController.Clear();
        ColorPicker.CloseWindow();
    }

    public void SetStock(Stock stock)
    {
        Title = $"{Loc.GetString(StockTitlePrefix)}#{stock.Id}";
        ColorPicker.Color = stock.Color;
    }

    public void BuildItems(StockpileCategoryPrototype? category)
    {
        if (_categoryItems.Count == 0)
            ReloadPrototypes();

        if (_stockpileController.SettingStock is not { } stock)
            return;

        ItemList.RemoveAllChildren();
        BackButton.Visible = category != null;

        _currentCategory = category;

        UpdateAddress(category);

        var categories = new List<StockpileCategoryPrototype>();

        if (category == null)
        {
            // Build root categories
            foreach (var cat in _prototype.EnumeratePrototypes<StockpileCategoryPrototype>())
            {
                if (GetCategoryParent(cat) == null)
                    categories.Add(cat);
            }
        }
        else
        {
            foreach (var child in category.SubCategories)
            {
                if (!_prototype.TryIndex(child, out var proto))
                    continue;

                categories.Add(proto);
            }
        }

        categories.Sort((x, y) => string.Compare(x.Name, y.Name, StringComparison.OrdinalIgnoreCase));

        // Add categories buttons
        foreach (var cat in categories)
        {
            if (!cat.Name.Contains(Search.Text))
                continue;

            var button = new StockpileItemButton(cat, GetCategoryCount(cat));

            if (GetCategorySettings(cat) is { } setting)
                button.MaxValue = setting;

            button.OnPressed += _ =>
            {
                Search.Text = string.Empty;
                BuildItems(cat);
            };
            button.OnSettingsChanged += value => SetCategorySettings(cat, value);

            ItemList.AddChild(button);
        }

        if (category == null || !_categoryItems.TryGetValue(category, out var list))
            return;

        list.Sort((x, y) =>
            string.Compare(x.Name + x.EditorSuffix, y.Name + x.EditorSuffix, StringComparison.OrdinalIgnoreCase));

        // Add items buttons
        foreach (var proto in list)
        {
            if (!proto.Name.Contains(Search.Text))
                continue;

            var button = new StockpileItemButton(proto, stock.GetCount(proto));
            button.MaxValue = stock.GetSetting(proto);
            button.OnSettingsChanged += value => _entity.System<StockpileSystem>().SetSetting(proto, value, stock);

            ItemList.AddChild(button);
        }
    }

    private void UpdateAddress(StockpileCategoryPrototype? category)
    {
        AddressBox.Visible = category != null;
        Address.Text = string.Empty;

        if (category == null)
            return;

        while (category != null)
        {
            Address.Text = $"{category.Name} > {Address.Text}";
            category = GetCategoryParent(category);
        }
    }

    private void SetCategorySettings(StockpileCategoryPrototype category, int value)
    {
        if (_stockpileController.SettingStock is not { } stock)
            return;

        foreach (var subCategory in category.SubCategories)
        {
            if (!_prototype.TryIndex(subCategory, out var proto))
                continue;

            SetCategorySettings(proto, value);
        }

        if (!_categoryItems.TryGetValue(category, out var items))
            return;

        var settings = new Dictionary<EntProtoId, int>();

        foreach (var item in items)
        {
            settings[item] = value;
        }

        _entity.System<StockpileSystem>().SetSetting(settings, stock);
    }

    private int? GetCategorySettings(StockpileCategoryPrototype category)
    {
        int? prevSettings = null;

        if (_stockpileController.SettingStock is not { } stock)
            return prevSettings;

        foreach (var subCategory in category.SubCategories)
        {
            if (!_prototype.TryIndex(subCategory, out var proto))
                continue;

            if (prevSettings == null)
            {
                prevSettings = GetCategorySettings(proto);
                continue;
            }

            if (prevSettings != GetCategorySettings(proto))
                return null;
        }

        if (!_categoryItems.TryGetValue(category, out var items))
            return prevSettings;

        foreach (var item in items)
        {
            var setting = stock.GetSetting(item);

            if (setting != -1 && setting != 0)
                return null;

            if (prevSettings == null)
            {
                prevSettings = setting;
                continue;
            }

            if (prevSettings != setting)
                return null;
        }

        return prevSettings;
    }

    private int GetCategoryCount(StockpileCategoryPrototype category)
    {
        var count = 0;

        if (_stockpileController.SettingStock is not { } stock)
            return count;

        foreach (var cat in category.SubCategories)
        {
            if (!_prototype.TryIndex(cat, out var proto))
                continue;

            count += GetCategoryCount(proto);
        }

        if (!_categoryItems.TryGetValue(category, out var items))
            return count;

        foreach (var item in items)
        {
            count += stock.GetCount(item);
        }

        return count;
    }

    private StockpileCategoryPrototype? GetCategoryParent(StockpileCategoryPrototype category)
    {
        foreach (var cat in _prototype.EnumeratePrototypes<StockpileCategoryPrototype>())
        {
            if (cat.SubCategories.Contains(category))
                return cat;
        }

        return null;
    }
}

