using System.Linq;
using Content.Shared._RF.Stockpile;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.UserInterface.Controls.Stockpile;

[GenerateTypedNameReferences]
public sealed partial class StockpileItemButton : Button
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceCache _resources = default!;

    public event Action<int>? OnSettingsChanged;

    private int _maxValue;
    private readonly bool _category;

    public int MaxValue
    {
        get => _maxValue;
        set
        {
            var val = _maxValue;
            _maxValue = value;

            Counter.Visible = !_category && _maxValue != -1;
            UnlimitedCheck.Pressed = _maxValue == -1;

            if (_maxValue != -1)
                Counter.Value = _maxValue;

            if (val == _maxValue)
                return;

            OnSettingsChanged?.Invoke(_maxValue);
        }
    }

    public StockpileItemButton()
    {
        RobustXamlLoader.Load(this);
    }

    public StockpileItemButton(StockpileCategoryPrototype proto, int count)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _category = true;

        Label.Text = count == 0 ? proto.Name : $"{proto.Name} ({count})";

        if (_prototype.TryIndex(proto.IconEntity, out var entProto))
        {
            Texture.Textures.AddRange(SpriteComponent
                .GetPrototypeTextures(entProto, _resources)
                .Select(x => x.Default));
        }
        else if (proto.Icon != null)
            Texture.Textures.Add(_entManager.System<SpriteSystem>().Frame0(proto.Icon));

        Counter.Visible = false;

        EnsureSetup();
    }

    public StockpileItemButton(EntityPrototype proto, int count)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Disabled = true;

        Label.Text = string.IsNullOrEmpty(proto.EditorSuffix) ? proto.Name : $"{proto.Name} [{proto.EditorSuffix}]";
        Label.Text = count == 0 ? Label.Text : $"{Label.Text} ({count})";

        Texture.Textures.AddRange(SpriteComponent
            .GetPrototypeTextures(proto, _resources)
            .Select(x => x.Default));

        Counter.OnValueChanged += value => MaxValue = value;

        EnsureSetup();
    }

    private void EnsureSetup()
    {
        ToolTip = Label.Text;

        UnlimitedCheck.OnPressed += _ =>
        {
            UnlimitedCheck.ToolTip = Loc.GetString(UnlimitedCheck.Pressed
                ? "stockpile-settings-menu-unlimited-checkbox-enabled-tooltip"
                : "stockpile-settings-menu-unlimited-checkbox-disabled-tooltip");

            MaxValue = UnlimitedCheck.Pressed ? -1 : 0;
        };
    }
}

