using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.Stockpile;

[GenerateTypedNameReferences]
public sealed partial class StockpileMenu : Control
{
    public StockpileMenu()
    {
        RobustXamlLoader.Load(this);

        var stockpileController = UserInterfaceManager.GetUIController<StockpileUiController>();

        CreateStockpileButton.OnPressed += _ => stockpileController.CreateSelection();
        EditStockpileButton.OnPressed += _ => stockpileController.SelectMode = true;
    }
}

