- type: npcTask
  id: BaseStoringTask
  parent: BaseSoloPerformTask
  abstract: true
  unionPerformersWith:
  - Storing
  - MoveStoredInContainer
  - FixStoredOffset
  - MoveToSuppliedStock
  overlayColor: "#A16C2B"
  verbIcon: /Textures/_RF/Interface/cubes-solid.svg.192dpi.png
  targetKey: PickUpTarget
  tempKeys:
  - Container
  - SupplyingOnly
  - SupplyingStartStock
