- type: npcTask
  id: MoveStoredInContainer
  name: Move stored items into crates
  parent: BaseStoringTask
  compound: MoveStoredInContainerCompound
  targetsQuery: MoveStoredInContainerTarget
  targetWhitelist:
    components:
    - Item
  startPreconditions:
  - !type:StockpileFreeContainerPrecondition
    targetKey: PickUpTarget
  finishPreconditions:
  - !type:OrPrecondition
    preconditions:
    - !type:EntityDeletedPrecondition
      key: PickUpTarget
    - !type:AndPrecondition
      preconditions:
      - !type:StoredPrecondition
        targetKey: PickUpTarget
      - !type:TargetInContainerPrecondition
        targetKey: PickUpTarget

- type: htnCompound
  id: MoveStoredInContainerCompound
  branches:
  - tasks:
    - !type:HTNPrimitiveTask
      operator: !type:DetachStoredOperator
        targetKey: PickUpTarget
    - !type:HTNCompoundTask
      task: StoringItemCompound

- type: utilityQuery
  id: MoveStoredInContainerTarget
  query:
  - !type:StoredQuery
  - !type:InContainerFilter
  - !type:InventoryFilter
  - !type:InHandsFilter
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
