- type: npcTask
  id: MoveToSuppliedStock
  name: Move stored between stockpiles
  parent: BaseStoringTask
  compound: MoveToSuppliedStockCompound
  targetsQuery: MoveToSuppliedStockTarget
  targetWhitelist:
    components:
    - Item
    - Pullable
  finishPreconditions:
  - !type:OrPrecondition
    preconditions:
    - !type:EntityDeletedPrecondition
      key: PickUpTarget
    - !type:AndPrecondition
      preconditions:
      - !type:StoredPrecondition
        targetKey: PickUpTarget
      - !type:CanInsertInSuppliedPrecondition
        targetKey: PickUpTarget
        invert: true

- type: htnCompound
  id: MoveToSuppliedStockCompound
  branches:
  - preconditions:
    - !type:KeyNotExistsPrecondition
      key: SupplyingStartStock
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:StockpileOperator
        targetKey: PickUpTarget
        resultKey: SupplyingStartStock
    - !type:HTNPrimitiveTask
      operator: !type:DetachStoredOperator
        targetKey: PickUpTarget

  - preconditions:
    - !type:KeyExistsPrecondition
      key: SupplyingStartStock
    tasks:
    - !type:HTNPrimitiveTask
      operator: !type:SetBoolOperator
        targetKey: SupplyingOnly
        value: true
    - !type:HTNCompoundTask
      task: StoringCompound

- type: utilityQuery
  id: MoveToSuppliedStockTarget
  query:
  - !type:StoredQuery
  - !type:CanInsertInSuppliedFilter
    invert: true
  - !type:InventoryFilter
  - !type:InHandsFilter
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
