using System.Numerics;
using Content.Client._RF.Stylesheets;
using Content.Client._RF.Tooltip.Prototypes;
using Content.Shared._RF.CCVar;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RF.Tooltip.Controls;

/// <summary>
/// A more advanced version of the tooltip that bypasses the current engine-based implementation, since it's crap.
/// This implementation supports both the standard tooltip format—where the tooltip follows the cursor
/// and hides when it moves outside the parent control—and a pinned mode,
/// where the tooltip stops following the cursor allows the cursor to hover over the tooltip’s content,
/// including opening nested tooltips multiple times. <br/>
/// The tooltip automatically switches from standard to pinned mode
/// if it remains open for longer than the time specified in <see cref="RfVars.PopupPinDelay"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TooltipPopup : Popup
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IResourceCache _cache = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    private TimeSpan PinDelay => TimeSpan.FromSeconds(_cfg.GetCVar(RfVars.PopupPinDelay));

    /// <summary>
    /// Offset of the tooltip from the mouse cursor.
    /// </summary>
    public Vector2 MouseOffset { get; set; }

    /// <summary>
    /// Control that opened this popup.
    /// </summary>
    public Control? Owner;

    /// <summary>
    /// Is this popup pinned?
    /// </summary>
    public bool Pinned { get; private set; }

    private TimeSpan? _trackingUntil;

    public TooltipPopup()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public TooltipPopup(ITooltipDefinition def)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Panel.Margin = new Thickness(MouseOffset.X + 5, MouseOffset.Y + 5);
        SetDefinition(def);
    }

    /// <summary>
    /// Updates the tooltip content.
    /// </summary>
    [PublicAPI]
    public void SetDefinition(ITooltipDefinition def)
    {
        Title.Text = ToFirstUpper(def.Title);
        IconPanel.Visible = false;
        IconDivider.Visible = false;
        Body.Visible = false;
        AddControlAfter.RemoveAllChildren();

        switch (def.IconType)
        {
            case TooltipIconType.Base:
                Texture.Stretch = TextureRect.StretchMode.KeepAspectCentered;
                break;
            case TooltipIconType.Tile:
                Texture.Stretch = TextureRect.StretchMode.KeepAspectCovered;
                Texture.CanShrink = true;
                break;
        }

        if (_proto.TryIndex(def.EntIcon, out var proto)
            && proto.HasComp<SpriteComponent>(_entity.ComponentFactory))
        {
            IconPanel.Visible = true;
            IconDivider.Visible = true;

            if (def.CanIconFocus)
                IconPanel.TooltipSupplier = _ => EntTooltip(proto);

            EntView.SetPrototype(def.EntIcon);
        }

        if (def.UidIcon != null
            && _entity.TryGetEntity(def.UidIcon, out var uid)
            && _entity.HasComponent<SpriteComponent>(uid))
        {
            IconPanel.Visible = true;
            IconDivider.Visible = true;

            if (def.CanIconFocus)
                IconPanel.TooltipSupplier = _ => SpriteTooltip(def.UidIcon.Value);

            SpriteView.SetEntity(def.UidIcon.Value);
        }

        if (def.TexturePath != null)
        {
            var tex = _cache.GetResource<TextureResource>(def.TexturePath.Value).Texture;
            IconPanel.Visible = true;
            IconDivider.Visible = true;

            if (def.CanIconFocus)
                IconPanel.TooltipSupplier = _ => IconTooltip(tex);

            Texture.Texture = tex;
        }

        if (def.Body != null)
        {
            Body.Visible = true;
            Body.OutlineColorOverride = TextOutline.Default.Color;
            Body.OutlineThicknessOverride = 1f;
            Body.Text = def.Body;
        }

        if (def.ControlAfter != null)
        {
            AddControlAfter.AddChild(def.ControlAfter);
        }

        return;

        string ToFirstUpper(string str)
            => string.IsNullOrEmpty(str) ? str : $"{char.ToUpper(str[0])}{str.Substring(1)}";

        Control EntTooltip(EntProtoId protoId)
        {
            var panel = new PanelContainer();
            panel.SetOnlyStyleClass(StyleFortress.StyleClassPanelDarkBordered);
            var view = new EntityPrototypeView
            {
                SetSize = new Vector2(128, 128),
                Scale = new Vector2(4f),
            };
            view.SetPrototype(protoId);
            panel.AddChild(view);
            return panel;
        }

        Control SpriteTooltip(NetEntity netUid)
        {
            var panel = new PanelContainer();
            panel.SetOnlyStyleClass(StyleFortress.StyleClassPanelDarkBordered);
            var view = new SpriteView
            {
                SetSize = new Vector2(128, 128),
                Scale = new Vector2(4f),
            };
            view.SetEntity(netUid);
            panel.AddChild(view);
            return panel;
        }

        Control IconTooltip(Texture tex)
        {
            var panel = new PanelContainer();
            panel.SetOnlyStyleClass(StyleFortress.StyleClassPanelDarkBordered);
            panel.AddChild(new TextureRect
            {
                SetSize = new Vector2(128, 128),
                Stretch = Texture.Stretch,
                CanShrink = Texture.CanShrink,
                Texture = tex,
            });
            return panel;
        }
    }

    /// <summary>
    /// The tooltip begins to follow the cursor and starts a timer until it is pinned.
    /// </summary>
    [PublicAPI]
    public void StartTracking()
    {
        if (_trackingUntil != null)
            return;

        Pinned = false;
        Progress.Visible = true;
        Progress.MinValue = (float)_timing.CurTime.TotalSeconds;
        Progress.MaxValue = (float)(_timing.CurTime + PinDelay).TotalSeconds;
        Panel.SetOnlyStyleClass(StyleFortress.ClassAngleRect);
        _trackingUntil = _timing.CurTime + PinDelay;
    }

    private void Pin()
    {
        Pinned = true;
        Progress.Visible = false;
        MouseFilter = MouseFilterMode.Stop;
        Panel.SetOnlyStyleClass(StyleFortress.StyleClassPanelAngleRectGolden);
        _trackingUntil = null;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_trackingUntil == null)
            return;

        if (_trackingUntil < _timing.CurTime)
        {
            Pin();
            return;
        }

        Progress.Value = (float)_timing.CurTime.TotalSeconds;
        PopupContainer.SetPopupOrigin(this, UserInterfaceManager.MousePositionScaled.Position - MouseOffset);
    }
}

