- type: htnCompound
  id: BuildCompound
  branches:
    - preconditions:
        - !type:HasComponentPrecondition
          components:
            - type: ActiveDoAfter
      tasks:
        - !type:HTNPrimitiveTask
          operator: !type:SetFloatOperator
            targetKey: Time
            amount: 0.5
        - !type:HTNPrimitiveTask
          operator: !type:WaitOperator
            key: Time

    # Turn off welder
    - preconditions:
        - !type:ActiveHandComponentPrecondition
          components:
            - type: Welder
        - !type:ItemTogglePrecondition
          targetKey: PickUpTarget
      tasks:
        - !type:HTNPrimitiveTask
          operator: !type:InteractWithOperator
            targetKey: PickUpTarget

    - tasks:
        # Find item for construction
        - !type:HTNPrimitiveTask
          operator: !type:UtilityOperator
            proto: Construction
            key: PickUpTarget
        - !type:HTNPrimitiveTask
          operator: !type:ConstructionAmountOperator
            targetKey: Target
        - !type:HTNCompoundTask
          task: PickUpCompound

        # Cleanup
        - !type:HTNPrimitiveTask
          operator: !type:TryOperator
            try: !type:HTNPrimitiveTask
              preconditions:
                - !type:KeyExistsPrecondition
                  key: Amount
                - !type:ActiveHandEntityIsPrecondition
                  targetKey: PickUpTarget
              operator: !type:RemoveKeyOperator
                key: Amount

        # Go to the construction target
        - !type:HTNPrimitiveTask
          operator: !type:EntityCoordinatesOperator
            targetKey: Target
        - !type:HTNPrimitiveTask
          operator: !type:MoveToOperator
            pathfindInPlanning: true
            rangeKey: InteractRange
            removeKeyOnFinish: true

        # Turn on Welder
        - !type:HTNPrimitiveTask
          operator: !type:TryOperator
            try: !type:HTNPrimitiveTask
              preconditions:
                - !type:ActiveHandComponentPrecondition
                  components:
                    - type: Welder
                - !type:ItemTogglePrecondition
                  targetKey: PickUpTarget
                  invert: true
              operator: !type:InteractWithOperator
                targetKey: PickUpTarget

        - !type:HTNPrimitiveTask
          operator: !type:InteractWithOperator
            targetKey: Target


- type: htnCompound
  id: DeconstructionCompound
  branches:
    - tasks:
        - !type:HTNPrimitiveTask
          operator: !type:StartDeconstructionOperator
            targetKey: Target
