using Content.Client._RF.Construction;
using Content.Client._RF.NPC;
using Content.Client._RF.Selection;
using Content.Client._RF.UserInterface.Controls.NpcJobs;
using Content.Client._RF.UserInterface.Controls.Stockpile;
using Content.Client._RF.UserInterface.Controls.TreeMenu;
using Content.Client._RF.World;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class ActionsHotbarWidget : UIWidget
{
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;

    private NpcControlSystem _npcControl  = default!;

    private readonly Dictionary<string, TreeMenuButton> _taskButtons = new();
    private TreeMenuButton? _taskEraseButton;

    public ActionsHotbarWidget()
    {
        RobustXamlLoader.Load(this);

        BuildButton.OnPressed += _ => UserInterfaceManager.GetUIController<ConstructionMenuUiController>().ToggleWindow();
        WorldMapButton.OnPressed += _ => UserInterfaceManager.GetUIController<WorldMapUiController>().ToggleWindow();
        NpcJobsButton.OnPressed += _ => UserInterfaceManager.GetUIController<NpcJobsUiController>().TogglePriorityWindow();

        var stockpileController = UserInterfaceManager.GetUIController<StockpileUiController>();

        CreateStockpileButton.OnPressed += _ => stockpileController.CreateSelection();
        EditStockpileButton.OnPressed += _ => stockpileController.SelectMode = StockpileSelectionMode.Edit;
    }

    public void EnsureSetup()
    {
        _npcControl = _systemManager.GetEntitySystem<NpcControlSystem>();
        _npcControl.OnTaskData += UpdateList;

        _systemManager.GetEntitySystem<SelectionSystem>().OnUpdateSelection += UpdateButtons;

        UpdateList();
    }

    private void UpdateList()
    {
        PassiveTasksButton.ClearContent();
        _taskButtons.Clear();

        _taskEraseButton = new TreeMenuButton
        {
            TexturePath = "/Textures/_RF/Interface/VerbIcons/eraser-solid.svg.192dpi.png",
            ToolTip = Loc.GetString("passive-tasks-menu-eraser-tooltip"),
            ToggleMode = true,
        };

        _taskEraseButton.OnToggled += args => _npcControl.SetEraser(args.Pressed);

        PassiveTasksButton.AddContent(_taskEraseButton);

        foreach (var (id, task) in _npcControl.TasksData)
        {
            var button = new TreeMenuButton
            {
                ToolTip = $"{task.TaskName}\n{task.Description}".Trim(),
                ToggleMode = true,
            };

            if (task.IconPath != null)
                button.TexturePath = task.IconPath;

            button.OnToggled += args => _npcControl.SetSelectedTask(args.Pressed ? task.TaskId : null);
            _taskButtons.Add(id, button);
            PassiveTasksButton.AddContent(button);
        }
    }

    private void UpdateButtons()
    {
        foreach (var (task, button) in _taskButtons)
        {
            button.Pressed = task == _npcControl.SelectedTask?.TaskId;
        }

        if (_taskEraseButton != null)
            _taskEraseButton.Pressed = _npcControl.Eraser;
    }
}

