using Content.Client._RF.Construction;
using Content.Client._RF.NPC.Executable.Systems;
using Content.Client._RF.Selection;
using Content.Client._RF.UserInterface.Controllers;
using Content.Client._RF.UserInterface.Controls.TreeMenu;
using Content.Client._RF.World;
using Content.Shared._RF.NPC.Executable.Components;
using Content.Shared._RF.NPC.Executable.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class ActionsHotbarWidget : UIWidget
{
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private ExecutableGoalSystem _executable = default!;
    private SpriteSystem _sprite = default!;
    private SelectionSystem _selection = default!;

    private readonly Dictionary<ProtoId<ExecutableGoalPrototype>, TreeMenuButton> _taskButtons = new();
    private TreeMenuButton? _taskEraseButton;
    private bool _setup;

    public ActionsHotbarWidget()
    {
        RobustXamlLoader.Load(this);

        BuildButton.OnPressed += _ => UserInterfaceManager.GetUIController<ConstructionMenuUiController>().ToggleWindow();
        WorldMapButton.OnPressed += _ => UserInterfaceManager.GetUIController<WorldMapUiController>().ToggleWindow();
        NpcJobsButton.OnPressed += _ => UserInterfaceManager.GetUIController<NpcJobsUiController>().TogglePriorityWindow();

        var stockpileController = UserInterfaceManager.GetUIController<StockpileUiController>();

        CreateStockpileButton.OnPressed += _ => stockpileController.CreateSelection();
        EditStockpileButton.OnPressed += _ => stockpileController.SelectMode = StockpileSelectionMode.Edit;
    }

    public void EnsureSetup()
    {
        if (_setup)
            return;

        _setup = true;
        _executable = _entity.System<ExecutableGoalSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _selection = _entity.System<SelectionSystem>();

        _selection.OnUpdateSelection += UpdateButtons;
        _executable.OnControllerAttached += UpdateList;

        UpdateList();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        if (!_setup)
            return;

        _setup = false;
        _selection.OnUpdateSelection -= UpdateButtons;
        _executable.OnControllerAttached -= UpdateList;
    }

    private void UpdateList()
    {
        PassiveTasksButton.ClearContent();
        _taskButtons.Clear();

        _taskEraseButton = new TreeMenuButton
        {
            TexturePath = "/Textures/_RF/Interface/VerbIcons/eraser-solid.svg.192dpi.png",
            ToolTip = Loc.GetString("passive-tasks-menu-eraser-tooltip"),
            ToggleMode = true,
        };

        _taskEraseButton.OnToggled += args => _executable.SetEraser(args.Pressed);

        PassiveTasksButton.AddContent(_taskEraseButton);

        if (!_entity.TryGetComponent(_player.LocalEntity, out NpcControllerComponent? control))
            return;

        foreach (var goal in control.Goals)
        {
            if (!_proto.Resolve(goal, out var proto)
                || !proto.GoalType.HasFlag(ExecutableGoalType.Passive))
                continue;

            var button = new TreeMenuButton
            {
                ToolTip = Loc.GetString(_proto.Index(proto.Goal).Name),
                ToggleMode = true,
                Texture = proto.Icon != null ? _sprite.Frame0(proto.Icon) : null,
            };

            button.OnToggled += args =>
                _executable.SetSelectedTask(args.Pressed ? (ProtoId<ExecutableGoalPrototype>?)goal : null);
            _taskButtons.Add(goal, button);
            PassiveTasksButton.AddContent(button);
        }
    }

    private void UpdateButtons()
    {
        foreach (var (task, button) in _taskButtons)
        {
            button.Pressed = task == _executable.SelectedTask;
        }

        if (_taskEraseButton != null)
            _taskEraseButton.Pressed = _executable.Eraser;
    }
}

