using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class ActionsHotbarWidget : UIWidget
{
    public ActionsHotbarWidget()
    {
        RobustXamlLoader.Load(this);
    }
}

