using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class ColorPicker : Control
{
    [Dependency] private readonly IUserInterfaceManager _ui = default!;

    public event Action<Color>? OnColorChanged;

    private readonly ColorPickerWindow _window;

    public Color Color
    {
        get => _window.Selector.Color;
        set
        {
            ColorPanel.PanelOverride = new StyleBoxFlat(value);
            _window.Selector.Color = value;
        }
    }

    public ColorPicker()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _window = _ui.CreateWindow<ColorPickerWindow>();

        _window.Selector.OnColorChanged += color =>
        {
            ColorPanel.PanelOverride = new StyleBoxFlat(color);
            OnColorChanged?.Invoke(color);
        };

        PickColorButton.OnPressed += _ =>
        {
            if (_window.IsOpen)
                _window.Close();
            else
                _window.Open(PickColorButton.GlobalPosition + new Vector2(0, 50f));
        };

        OnResized += () =>
        {
            var size = new Vector2(Height);
            ColorPanel.SetSize = size - new Vector2(ColorPanel.Margin.Left, ColorPanel.Margin.Top);
            PickColorButton.SetSize = size;
        };
    }

    public void CloseWindow()
    {
        _window.Close();
    }
}

