using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class ColorPickerWindow : FancyWindow
{
    public ColorPickerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

