using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class HotbarActionButton : Control
{
    public string TexturePath { set => Texture.TexturePath = value; }

    public event Action<BaseButton.ButtonEventArgs>? OnPressed;

    public HotbarActionButton()
    {
        RobustXamlLoader.Load(this);

        Button.OnPressed += args => OnPressed?.Invoke(args);
    }
}

