using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class HotbarActionButton : TextureButton
{
    public string IconTexturePath { set => Texture.TexturePath = value; }
    public Color IconModulate { set => Texture.Modulate = value; }

    public HotbarActionButton()
    {
        RobustXamlLoader.Load(this);

        OnToggled += args => SetPressed(args.Pressed);
    }

    public void SetPressed(bool pressed)
    {
        Modulate = pressed ? StyleNano.ButtonColorPressed : Color.White;
        Pressed = pressed;
    }
}

