using System.Numerics;
using Content.Client._RF.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

/// <summary>
/// Button with icon instead of text
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class IconButton : Button
{
    /// <summary>
    /// Path to icon texture
    /// </summary>
    public string TexturePath { set => _icon!.TexturePath = value; }

    /// <summary>
    /// Icon texture
    /// </summary>
    public Texture? Texture
    {
        get => _icon?.Texture;
        set => _icon!.Texture = value;
    }

    private Color DefaultColor => HasStyleClass(StyleFortress.StyleClassButtonColorGold)
        ? StyleFortress.ButtonColorDefault
        : StyleFortress.GoldButtonColorDefault;

    private Color HoveredColor => HasStyleClass(StyleFortress.StyleClassButtonColorGold)
        ? StyleFortress.ButtonColorHovered
        : StyleFortress.GoldButtonColorHovered;

    private Color PressedColor => HasStyleClass(StyleFortress.StyleClassButtonColorGold)
        ? StyleFortress.ButtonColorPressed
        : StyleFortress.GoldButtonColorPressed;

    private Color DisabledColor => HasStyleClass(StyleFortress.StyleClassButtonColorGold)
        ? StyleFortress.ButtonColorDisabled
        : StyleFortress.GoldButtonColorDisabled;

    private readonly TextureRect? _icon;

    public IconButton()
    {
        _icon = new TextureRect
        {
            TextureScale = new Vector2(0.5f, 0.5f),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            ModulateSelfOverride = DefaultColor,
            Margin = new Thickness(2f),
        };

        RobustXamlLoader.Load(this);
        Label.Visible = false;

        AddChild(_icon);
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        UpdateChildColors();
    }

    protected override void StylePropertiesChanged()
    {
        // colors of children depend on style, so ensure we update when style is changed
        base.StylePropertiesChanged();
        UpdateChildColors();
    }

    private void UpdateChildColors()
    {
        if (_icon == null)
            return;

        _icon.ModulateSelfOverride = DrawMode switch
        {
            DrawModeEnum.Normal => DefaultColor,
            DrawModeEnum.Hover => HoveredColor,
            DrawModeEnum.Pressed => PressedColor,
            DrawModeEnum.Disabled => DisabledColor,
            _ => _icon.ModulateSelfOverride,
        };
    }
}

