using Content.Client._RF.Info;
using Content.Client._RF.Selection;
using Content.Client._RF.Stylesheets;
using Content.Shared.Follower;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class PopIcon : Button
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityNetworkManager _net = default!;

    private TimeSpan _lastClicked;

    public PopIcon(EntityUid uid, string? name)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddStyleClass(StyleFortress.StyleClassButtonTransparent);

        Icon.OverrideDirection = Direction.South;
        Icon.SetEntity(uid);
        ToolTip = name;

        OnToggled += OnButtonToggled;
    }

    protected override void ExitedTree()
    {
        OnToggled -= OnButtonToggled;

        base.ExitedTree();
    }

    private void OnButtonToggled(ButtonEventArgs args)
    {
        if (Icon.Entity is not { } uid)
            return;

        var time = _timing.CurTime;

        if (_lastClicked > time - TimeSpan.FromSeconds(0.333))
        {
            Pressed = false;

            // THIS IS HORRIBLE,
            // but we can't work properly with the FollowerSystem on the client
            // and have to send the message to the server
            _net.SendSystemNetworkMessage(new FollowEntityRequest(_entityManager.GetNetEntity(uid)));
        }

        _lastClicked = time;

        var selection = _entityManager.System<SelectionSystem>();

        if (Pressed)
            selection.Select(uid);
        else
            selection.DeSelect(uid);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (Icon.Entity?.Owner is not { } uid)
            return;

        if (args.Function == EngineKeyFunctions.UIRightClick)
            UserInterfaceManager.GetUIController<PopInfoUIController>().OpenWindow(uid, GlobalPosition);
    }
}

