using Content.Client._RF.Selection;
using Content.Shared._RF.World;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class PopList : UIWidget
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private static readonly TimeSpan UpdateRate = TimeSpan.FromSeconds(1);

    private SelectionSystem _selection = default!;
    private TimeSpan _nextUpdate;

    private readonly Dictionary<EntityUid, PopIcon> _icons = new();

    public PopList()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    private void AddPop(EntityUid uid)
    {
        if (_icons.ContainsKey(uid) || !_entityManager.EntityExists(uid))
            return;

        _entityManager.TryGetComponent(uid, out MetaDataComponent? meta);

        var icon = new PopIcon(uid, meta?.EntityName);
        _icons.Add(uid, icon);
        Icons.AddChild(icon);
    }

    private void RemovePop(EntityUid uid)
    {
        if (!_icons.TryGetValue(uid, out var icon))
            return;

        Icons.RemoveChild(icon);
        _icons.Remove(uid);
    }

    public void EnsureSetup()
    {
        _selection = _entityManager.System<SelectionSystem>();
        _selection.OnSelectedChanged += UpdateSelection;

        Update();
    }

    private void UpdateSelection()
    {
        foreach (var (uid, icon) in _icons)
        {
            icon.Pressed = _selection.Selected.Contains(uid);
        }
    }

    private void Update()
    {
        if (!_entityManager.TryGetComponent(_player.LocalEntity, out RimFortressPlayerComponent? player))
            return;

        foreach (var pop in player.Pops)
        {
            if (!_icons.ContainsKey(pop))
                AddPop(pop);
            else if (!_entityManager.EntityExists(pop))
                RemovePop(pop);
        }

        foreach (var (uid, _) in _icons)
        {
            if (!player.Pops.Contains(uid))
                RemovePop(uid);
        }
    }

    public void Clear()
    {
        Icons.RemoveAllChildren();
        _icons.Clear();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_nextUpdate > _timing.CurTime)
            return;

        Update();
        _nextUpdate = _timing.CurTime + UpdateRate;
    }

    protected override void ExitedTree()
    {
        _selection.OnSelectedChanged -= UpdateSelection;
        base.ExitedTree();
    }
}

