using Content.Client._RF.NPC.Executable.Systems;
using Content.Client._RF.Selection;
using Content.Client._RF.World;
using Content.Client.CombatMode;
using Content.Shared._RF.World.Components;
using Content.Shared.CombatMode;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class PopList : UIWidget
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private const string CombatModeIcon = "/Textures/Interface/Actions/harm.png";
    private const string NoCombatModeIcon = "/Textures/Interface/Actions/harmOff.png";

    private SelectionSystem _selection = default!;
    private ExecutableGoalSystem _executable = default!;
    private CombatModeSystem _combatMode = default!;
    private RimFortressWorldSystem _world = default!;
    private bool _setup;

    private readonly Dictionary<EntityUid, PopIcon> _icons = new();

    private bool CombatMode
    {
        set
        {
            CombatButton.TexturePath = value ? CombatModeIcon : NoCombatModeIcon;
            CombatButton.Pressed = value;
        }
    }

    public PopList()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        CombatButton.TexturePath = NoCombatModeIcon;
        CombatButton.OnPressed += _ =>
        {
            _executable.SetCombatMode(CombatButton.Pressed);
            UpdateCombat();
        };
    }

    private void AddPop(EntityUid uid)
    {
        if (_icons.ContainsKey(uid) || !_entityManager.EntityExists(uid))
            return;

        _entityManager.TryGetComponent(uid, out MetaDataComponent? meta);

        var icon = new PopIcon(uid, meta?.EntityName);
        _icons.Add(uid, icon);
        Icons.AddChild(icon);
    }

    private void RemovePop(EntityUid uid)
    {
        if (!_icons.TryGetValue(uid, out var icon))
            return;

        Icons.RemoveChild(icon);
        _icons.Remove(uid);
    }

    public void EnsureSetup()
    {
        if (_setup)
            return;

        _selection = _entityManager.System<SelectionSystem>();
        _executable = _entityManager.System<ExecutableGoalSystem>();
        _combatMode = _entityManager.System<CombatModeSystem>();
        _world = _entityManager.System<RimFortressWorldSystem>();

        _selection.OnSelectedChanged += UpdateSelection;
        _combatMode.CombatModeChanged += UpdateCombat;
        _world.OnPlayerUpdate += Update;
        _setup = true;

        if (_entityManager.TryGetComponent(_player.LocalEntity, out RimFortressPlayerComponent? comp))
            Update(new(_player.LocalEntity.Value, comp));
    }

    private void UpdateSelection()
    {
        var selected = _selection.SelectedEntities();

        foreach (var (uid, icon) in _icons)
        {
            icon.Pressed = selected.Contains(uid);
        }

        UpdateCombat();
    }

    private void UpdateCombat(Entity<CombatModeComponent> ent)
    {
        if (!_entityManager.TryGetComponent(_player.LocalEntity, out RimFortressPlayerComponent? player)
            || !player.Pops.Contains(ent))
            return;

        UpdateCombat();
    }

    private void UpdateCombat()
    {
        CombatMode = true;
        var selected = _selection.SelectedEntities();

        foreach (var (uid, icon) in _icons)
        {
            var select = selected.Contains(uid);
            var combat = _combatMode.IsInCombatMode(uid);

            icon.CombatMode = combat;

            if ((select || selected.Count == 0) && !combat)
                CombatMode = false;
        }
    }

    private void Update(Entity<RimFortressPlayerComponent> ent)
    {
        foreach (var pop in ent.Comp.Pops)
        {
            if (!_icons.ContainsKey(pop))
                AddPop(pop);
            else if (!_entityManager.EntityExists(pop))
                RemovePop(pop);
        }

        foreach (var (uid, _) in _icons)
        {
            if (!ent.Comp.Pops.Contains(uid))
                RemovePop(uid);
        }

        UpdateCombat();
    }

    public void Clear()
    {
        Icons.RemoveAllChildren();
        _icons.Clear();
    }

    protected override void ExitedTree()
    {
        if (_setup)
        {
            _selection.OnSelectedChanged -= UpdateSelection;
            _combatMode.CombatModeChanged -= UpdateCombat;
            _world.OnPlayerUpdate -= Update;
            _setup = false;
        }

        base.ExitedTree();
    }
}

