using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class RfConstructionMenu : Control
{
    public RfConstructionMenu()
    {
        RobustXamlLoader.Load(this);
    }
}
