using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Screens;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class RimFortressScreen : InGameScreen
{
    public override ChatBox ChatBox => Chat;

    public RimFortressScreen()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.CenterLeft, margin: 10);
        SetAnchorAndMarginPreset(Chat, LayoutPreset.TopRight, margin: 10);
        SetAnchorAndMarginPreset(Right, LayoutPreset.RightWide, margin: 10);

        // We dont need it
        TopBar.CharacterButton.Visible = false;
        TopBar.ActionButton.Visible = false;
        TopBar.EmotesButton.Visible = false;
        TopBar.CraftingButton.Visible = false;

        TopBar.GuidebookButton.RemoveStyleClass(StyleBase.ButtonSquare);
        TopBar.AdminButton.RemoveStyleClass(StyleBase.ButtonSquare);
        TopBar.SandboxButton.RemoveStyleClass(StyleBase.ButtonSquare);

        TopBar.GuidebookButton.AddStyleClass(StyleBase.ButtonOpenBoth);
        TopBar.AdminButton.AddStyleClass(StyleBase.ButtonOpenBoth);
        TopBar.SandboxButton.AddStyleClass(StyleBase.ButtonOpenBoth);

        Chat.OnChatResizeFinish += ChatOnResizeFinish;
        Datetime.ChatToggle.OnToggled += args => Chat.Visible = args.Pressed;
    }

    private void ChatOnResizeFinish(Vector2 _)
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        var marginLeft = Chat.GetValue<float>(MarginLeftProperty);
        OnChatResized?.Invoke(new Vector2(marginBottom, marginLeft));
    }

    public override void SetChatSize(Vector2 size)
    {
        SetMarginBottom(Chat, size.X);
        SetMarginLeft(Chat, size.Y);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        PopList.Update();
    }
}

