using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Screens;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class RimFortressScreen : InGameScreen
{
    public override ChatBox ChatBox => Chat;

    public RimFortressScreen()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);

        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.CenterLeft, margin: 10);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(TopRight, LayoutPreset.TopRight, margin: 10);
        SetAnchorAndMarginPreset(MenuBar, LayoutPreset.BottomRight, margin: 10);

        SetAnchorAndMarginPreset(PopList, LayoutPreset.Wide, margin: 10);

        // We dont need it
        MenuBar.CharacterButton.Visible = false;
        MenuBar.ActionButton.Visible = false;
        MenuBar.EmotesButton.Visible = false;
        MenuBar.CraftingButton.Visible = false;

        MenuBar.GuidebookButton.RemoveStyleClass(StyleBase.ButtonSquare);
        MenuBar.AdminButton.RemoveStyleClass(StyleBase.ButtonSquare);
        MenuBar.SandboxButton.RemoveStyleClass(StyleBase.ButtonSquare);

        MenuBar.GuidebookButton.AddStyleClass(StyleBase.ButtonOpenBoth);
        MenuBar.AdminButton.AddStyleClass(StyleBase.ButtonOpenBoth);
        MenuBar.SandboxButton.AddStyleClass(StyleBase.ButtonOpenBoth);
    }

    public override void SetChatSize(Vector2 size)
    {
        SetMarginBottom(Chat, size.X);
        SetMarginLeft(Chat, size.Y);
    }
}

