- type: npcTask
  id: BaseWorkshopTask
  parent: BaseSoloPerformTask
  abstract: true
  compound: WorkshopCompound
  targetsQuery: WorkshopTaskTarget
  tempKeys:
  - TargetRecipe
  - PickUpTarget
  finishPreconditions:
  - !type:WorkshopCraftingDonePrecondition

- type: htnCompound
  id: WorkshopCompound
  branches:
  - tasks:
    - !type:HTNPrimitiveTask
      operator: !type:GetWorkshopIngredientOperator
        resultKey: PickUpTarget
    - !type:HTNCompoundTask
      task: PickUpCompound
    - !type:HTNPrimitiveTask
      operator: !type:EntityCoordinatesOperator
        targetKey: Target
    - !type:HTNPrimitiveTask
      operator: !type:MoveToOperator
        rangeKey: InteractLongRange
    - !type:HTNPrimitiveTask
      operator: !type:InteractWithOperator
        targetKey: Target
    - !type:HTNPrimitiveTask
      operator: !type:WaitWhileOperator
        preconditions:
        - !type:WorkshopCraftingPrecondition

# Queries
- type: utilityQuery
  id: WorkshopTaskTarget
  query:
  - !type:OwnedQuery
  - !type:WorkshopHasRecipeFilter
    recipeKey: TargetRecipe
    invert: true
  considerations:
  - !type:NormTargetDistanceCon
    curve: !type:PresetCurve
      preset: TargetDistance
