using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.GOAP.UI;

[GenerateTypedNameReferences]
public sealed partial class BreakpointControl : Control
{
    public BreakpointControl()
    {
        RobustXamlLoader.Load(this);
    }
}

