using System.Numerics;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._RF.NPC.GOAP.UI;

[GenerateTypedNameReferences]
public sealed partial class DraggablePanel : Control
{
    [PublicAPI]
    public string? Title
    {
        get => Label.Text;
        set => Label.Text = value;
    }

    [PublicAPI]
    public bool Expanded
    {
        get => Contents.Visible;
        set => SetExpanded(value);
    }

    private bool _dragging;
    private Vector2 _lastMousePosition;

    public DraggablePanel()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = Contents.Children;

        Drag.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick || args.IsRepeat)
                return;

            _dragging = true;
            _lastMousePosition = UserInterfaceManager.MousePositionScaled.Position;
            args.Handle();
        };

        Drag.OnKeyBindUp += args =>
        {
            if (args.Function == EngineKeyFunctions.UIRightClick)
            {
                SetExpanded(!Expanded);
                args.Handle();
                return;
            }

            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _dragging = false;
            args.Handle();
        };

        SetExpanded(Expanded);
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_dragging)
            return;

        var mouse = UserInterfaceManager.MousePositionScaled.Position;
        var delta = mouse - _lastMousePosition;
        _lastMousePosition = mouse;

        var newPos = Position + delta;

        if (Parent == null)
        {
            LayoutContainer.SetPosition(this, newPos);
            args.Handle();
            return;
        }

        newPos.X = Math.Clamp(newPos.X, 0, Parent.Width - Size.X);
        newPos.Y = Math.Clamp(newPos.Y, 0, Parent.Height - Size.Y);

        LayoutContainer.SetPosition(this, newPos);
        args.Handle();
    }

    private void SetExpanded(bool expanded)
    {
        Marker.TexturePath = expanded
            ? "/Textures/_RF/Interface/chevron-down-solid-full.svg.192dpi.png"
            : "/Textures/_RF/Interface/chevron-right-solid.svg.192dpi.png";
        Divider.Visible = expanded;
        Contents.Visible = expanded;
    }
}

