using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._RF.NPC.GOAP.UI;

[GenerateTypedNameReferences]
public sealed partial class DraggablePanel : Control
{
    public string? Title
    {
        get => Label.Text;
        set => Label.Text = value;
    }

    private bool _dragging;
    private Vector2 _lastMousePosition;

    public DraggablePanel()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = Contents.Children;

        Drag.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick || args.IsRepeat)
                return;

            _dragging = true;
            _lastMousePosition = UserInterfaceManager.MousePositionScaled.Position;
            args.Handle();
        };

        Drag.OnKeyBindUp += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _dragging = false;
            args.Handle();
        };
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_dragging)
            return;

        var mouse = UserInterfaceManager.MousePositionScaled.Position;
        var delta = mouse - _lastMousePosition;
        _lastMousePosition = mouse;

        var newPos = Position + delta;

        if (Parent == null)
        {
            LayoutContainer.SetPosition(this, newPos);
            args.Handle();
            return;
        }

        newPos.X = Math.Clamp(newPos.X, 0, Parent.Width - Size.X);
        newPos.Y = Math.Clamp(newPos.Y, 0, Parent.Height - Size.Y);

        LayoutContainer.SetPosition(this, newPos);
        args.Handle();
    }
}

