using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._RF.NPC.GOAP.UI;

/// <summary>
/// A container whose contents can be hidden or revealed by clicking.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ExpandableBox : BoxContainer
{
    /// <summary>
    /// A title that will be displayed even if the container is hidden.
    /// </summary>
    [PublicAPI]
    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    [PublicAPI]
    public string? SecondaryText
    {
        get => SecondaryLabel.Text;
        set => SecondaryLabel.Text = value;
    }

    [PublicAPI]
    public bool Expanded
    {
        get => Content.Visible;
        set => SetExpanded(value);
    }

    public ExpandableBox()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = Content.Children;
        Orientation = LayoutOrientation.Horizontal;

        TitleBox.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.Use
                || args.Function == EngineKeyFunctions.UseSecondary)
                SetExpanded(!Expanded);
        };

        SetExpanded(Expanded);
    }

    private void SetExpanded(bool expanded)
    {
        Marker.TexturePath = expanded
            ? "/Textures/_RF/Interface/chevron-down-solid-full.svg.192dpi.png"
            : "/Textures/_RF/Interface/chevron-right-solid.svg.192dpi.png";
        Content.Visible = expanded;
    }

    public void ExpandAll()
    {
        Expanded = true;
        var parent = Parent;

        while (parent != null)
        {
            if (parent is ExpandableBox box)
                box.Expanded = true;

            parent = parent.Parent;
        }
    }
}

