using System.Linq;
using System.Numerics;
using Content.Client._RF.NPC.UI;
using Content.Client._RF.Stylesheets;
using Content.Client._RF.UserInterface.Controls;
using Content.Shared._RF.NPC;
using Content.Shared._RF.NPC.GOAP;
using Content.Shared._RF.NPC.GOAP.Prototypes;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._RF.NPC.GOAP.UI;

[GenerateTypedNameReferences]
public sealed partial class GoapDebugTab : Control
{
    /// <summary>
    /// The base size of the graph's nodes.
    /// </summary>
    [PublicAPI]
    public Vector2 NodeSize { get; set; } = new(100f);

    /// <summary>
    /// The minimum possible zoom level for the graph.
    /// </summary>
    [PublicAPI]
    public float MinZoom { get; set; } = 0.6f;

    /// <summary>
    /// The maximum possible zoom level for the graph.
    /// </summary>
    [PublicAPI]
    public float MaxZoom { get; set; } = 1.4f;

    /// <summary>
    /// How fast the zoom level will change.
    /// </summary>
    [PublicAPI]
    public float ZoomStep { get; set; } = 0.1f;

    private readonly AiDevWindowUiController _controller;
    private readonly Dictionary<GoapBreakpoint, BreakpointControl> _points = new();
    private readonly Dictionary<int, Control> _nodeControls = new();
    private readonly Dictionary<ProtoId<GoapCompoundPrototype>, List<Control>> _compounds = new();
    private readonly Dictionary<ProtoId<GoapCompoundPrototype>, bool> _compoundSettings = new();

    private GoapStaticGraphDebug? _graph;
    private GoapPlanDebugInfo? _plan;
    private EntityUid? _target;
    private GraphLayout? _layout;

    private float _zoom = 1.0f;

    public GoapDebugTab()
    {
        RobustXamlLoader.Load(this);

        _controller = UserInterfaceManager.GetUIController<AiDevWindowUiController>();

        LayoutContainer.SetAnchorAndMarginPreset(PlanPanel, LayoutContainer.LayoutPreset.BottomRight, margin: 50);
        LayoutContainer.SetAnchorAndMarginPreset(VisibilityPanel, LayoutContainer.LayoutPreset.BottomLeft, margin: 50);
        LayoutContainer.SetAnchorAndMarginPreset(BreakpointsPanel, LayoutContainer.LayoutPreset.TopRight, margin: 50);

        NodeId.OnItemSelected += args => SelectNodeId(args.Id);

        PointType.OnItemSelected += args =>
        {
            if (_graph == null)
                return;

            Index.Visible = true;
            Result.Visible = true;
            Index.Clear();
            Result.Clear();
            PointType.Select(args.Id);

            if (PointType.SelectedMetadata is not GoapBreakpointKind kind)
                return;

            if (_graph.Value.Nodes.TryGetValue(NodeId.SelectedId, out var node))
            {
                Index.AddItem("Any", -1);

                foreach (var action in node.Actions)
                {
                    Index.AddItem(action.Name);
                }
            }
            else
                Index.AddItem("Any", -1);

            switch (kind)
            {
                case GoapBreakpointKind.Planning:
                case GoapBreakpointKind.ActionStartup:
                    Result.AddItem("True", 0);
                    Result.SetItemMetadata(0, GoapBreakpointResultKind.True);
                    Result.AddItem("False", 1);
                    Result.SetItemMetadata(1, GoapBreakpointResultKind.False);
                    break;
                case GoapBreakpointKind.ActionUpdate:
                    Result.AddItem("Continuing", 0);
                    Result.SetItemMetadata(0, GoapBreakpointResultKind.Continuing);
                    Result.AddItem("Finished", 1);
                    Result.SetItemMetadata(1, GoapBreakpointResultKind.Finished);
                    Result.AddItem("Failed", 2);
                    Result.SetItemMetadata(2, GoapBreakpointResultKind.Failed);
                    break;
                case GoapBreakpointKind.ActionShutdown:
                default:
                    Result.AddItem("None", 0);
                    Result.SetItemMetadata(0, GoapBreakpointResultKind.None);
                    break;
            }

            UpdateConfirm();
        };

        Index.OnItemSelected += args =>
        {
            Index.Select(Index.GetIdx(args.Id));
            UpdateConfirm();
        };

        Result.OnItemSelected += args =>
        {
            Result.Select(args.Id);
            UpdateConfirm();
        };

        Confirm.OnPressed += _ =>
        {
            if (_graph == null
                || _target == null
                || PointType.SelectedMetadata is not GoapBreakpointKind kind
                || Result.SelectedMetadata is not GoapBreakpointResultKind result)
                return;

            _controller.AddBreakpoint(
                _target.Value,
                NodeId.SelectedId,
                Index.SelectedId,
                kind,
                result);
            CreatePointBox.Visible = false;
            AddPointButton.Visible = true;
        };

        Cancel.OnPressed += _ =>
        {
            CreatePointBox.Visible = false;
            AddPointButton.Visible = true;
        };

        AddPointButton.OnPressed += _ =>
        {
            CreatePointBox.Visible = true;
            AddPointButton.Visible = false;
            UpdateConfirm();
        };

        _controller.OnBreakpointAdded += _onBreakpointAdded;
        _controller.OnBreakpointRemoved += _onBreakpointRemoved;
        _controller.OnBreakpointHit += _onBreakpointHit;
    }

    public void SetTarget(EntityUid target)
    {
        if (_target != null && _target != target)
            _controller.Unsubscribe(_target.Value);

        _controller.Subscribe(target);
        _controller.RequestGoapDebug(target);
        _target = target;
    }

    public void Update(GoapStaticGraphDebug graphDebug, GoapPlanDebugInfo? plan)
    {
        _graph = graphDebug;
        _plan = plan;
        _nodeControls.Clear();
        _compounds.Clear();

        NodesLayer.RemoveAllChildren();
        _layout = GraphLayoutBuilder.Build(graphDebug, NodeSize);

        foreach (var node in graphDebug.Nodes)
        {
            var planNode = GetNode(node.Id);
            var actions = plan?.Actions
                .Where(x => x.NodeIndex == node.Id)
                .ToList();

            var control = new GraphNodeControl(node, actions, planNode);
            control.OnMouseEntered += _ => SelectNode(node.Id);
            control.OnMouseExited += _ => DeselectNodes();
            control.OnKeyBindUp += args => NodeClick(node, args);

            NodesLayer.AddChild(control);
            _nodeControls[node.Id] = control;

            if (node.Compound == null)
                continue;

            _compoundSettings.TryAdd(node.Compound.Value, true);
            control.Visible = _compoundSettings[node.Compound.Value];

            if (!_compounds.TryAdd(node.Compound.Value, new() { control }))
                _compounds[node.Compound.Value].Add(control);
        }

        UpdateLayout();

        // BreakpointsPanel
        if (NodeId.ItemCount != graphDebug.Nodes.Count + 1)
        {
            NodeId.Clear();
            PointType.Visible = false;
            Index.Visible = false;
            Result.Visible = false;
            Confirm.Disabled = true;
            NodeId.AddItem("Any", -1);

            foreach (var node in graphDebug.Nodes)
            {
                NodeId.AddItem(
                    (graphDebug.Nodes.FirstOrNull(x => x.Id == node.Id)?.Compound ?? "Node") + $" #{node.Id}",
                    node.Id);
            }
        }

        // VisibilityPanel
        VisibilityBox.RemoveAllChildren();

        foreach (var (compound, pressed) in _compoundSettings)
        {
            var check = new CheckBox { Text = compound, Pressed = pressed };
            check.OnPressed += _ =>
            {
                if (!_compounds.TryGetValue(compound, out var controls))
                    return;

                foreach (var control in controls)
                {
                    control.Visible = check.Pressed;
                }
            };

            VisibilityBox.AddChild(check);
        }

        // PlanPanel
        PlanPanel.Visible = plan != null;

        if (plan == null)
            return;

        TotalCost.Text = $"[bold]Total Cost: {plan.Value.TotalCost}[/bold]";
        ConditionsChecked.Text = $"[bold]Conditions Checked: {plan.Value.ConditionsChecked}[/bold]";
        PlanningNodes.Text = $"[bold]Available Nodes: {graphDebug.Nodes.Count}[/bold]";
        NodesInPlan.Text = "[bold]Nodes in Plan: "
                           + graphDebug.Nodes.Count(x
                               => plan.Value.Actions.Any(y
                                   => y.NodeIndex == x.Id))
                           + "[/bold]";
        EffectsApplied.Text = $"[bold]Effects Applied: {plan.Value.EffectsApplied}[/bold]";
        SkippedExpensiveNodes.Text = $"[bold]Skipped Expensive Nodes: {plan.Value.SkippedExpensiveNodes}[/bold]";
        NodesExpanded.Text = $"[bold]Nodes Expanded: {plan.Value.NodesExpanded}[/bold]";
        Planning.Text = plan.Value.Success
            ? $"[bold]Planning: [color={StyleFortress.LightGood.ToHex()}]Success[/color][/bold]"
            : $"[bold]Planning: [color={StyleFortress.LightBad.ToHex()}]Failed[/color][/bold]";
        ElapsedTime.Text = $"[bold]Elapsed Time: {plan.Value.ElapsedTime.TotalMilliseconds}ms[/bold]";
        AddTypes(StartState, plan.Value.StartState);
        AddTypes(GoalState, plan.Value.GoalState);

        return;

        void AddTypes(ExpandableBox parent, GoapStateDebugDump data)
        {
            parent.Content.RemoveAllChildren();

            if (data.State.Count == 0)
                return;

            foreach (var (key, (type, value)) in data.State)
            {
                parent.Content.AddChild(new PanelContainer
                {
                    StyleClasses = { StyleFortress.StyleClassLowDividerDark },
                    Margin = new Thickness(3f, 2f),
                });

                parent.Content.AddChild(new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(0f, 1f),
                    Children =
                    {
                        new BoxContainer
                        {
                            Children =
                            {
                                new RichTextLabel { Text = $"[bold]{key}[/bold]" },
                                new Control { HorizontalExpand = true },
                                new RichTextLabel { Text = $":{type}" },
                            },
                        },
                        new BoxContainer
                        {
                            Children =
                            {
                                new RichTextLabel { Text = value },
                            },
                        },
                    },
                });
            }
        }

        GoapNodeDebugEntry? GetNode(int id)
        {
            if (plan == null)
                return null;

            var nodes = plan.Value.Nodes
                .Where(x => x.NodeId == id)
                .ToList();
            return nodes.FirstOrNull(x => x.InPlan)
                   ?? nodes.FirstOrNull(x => x.HelpGoal)
                   ?? nodes.OrderByDescending(x
                           => x.Preconditions.Count(y => y.Result))
                       .FirstOrNull();
        }
    }

    private void CenterOnNode(Control node)
    {
        var nodeCenter = node.Position + node.Size / 2f;
        var targetOffset = nodeCenter - ScrollContainer.Size / 2f;
        ScrollContainer.SetScrollValue(targetOffset);
    }

    private void SelectNode(int id)
    {
        var highlight = new HashSet<int>();
        var queue = new Queue<int>();
        queue.Enqueue(id);

        while (queue.TryDequeue(out var nodeId))
        {
            if (!highlight.Add(nodeId))
                continue;

            if (_plan != null)
            {
                foreach (var child in _plan.Value.Nodes.Where(x => x.FromNodeId == nodeId))
                {
                    queue.Enqueue(child.NodeId);
                }
            }

            if (_graph != null)
            {
                foreach (var edge in _graph.Value.Edges.Where(x => x.ToNodeId == nodeId))
                {
                    queue.Enqueue(edge.FromNodeId);
                }
            }
        }

        foreach (var (nodeId, control) in _nodeControls)
        {
            control.Modulate = highlight.Contains(nodeId) ? Color.White : Color.White.WithAlpha(0.30f);
        }
    }

    private void DeselectNodes()
    {
        foreach (var (_, control) in _nodeControls)
        {
            control.Modulate = Color.White;
        }
    }

    private void NodeClick(GoapStaticGraphNodeDebug node, GUIBoundKeyEventArgs args)
    {
        if (CreatePointBox.Visible && args.Function == EngineKeyFunctions.UIClick)
            SelectNodeId(node.Id);

        if (args.Function != EngineKeyFunctions.UIRightClick)
            return;

        if (_target is not { } uid)
            return;

        (GoapBreakpointKind Kind, GoapBreakpointResultKind[] Results)[] kinds =
        {
            (GoapBreakpointKind.ActionStartup,
                new[] { GoapBreakpointResultKind.True, GoapBreakpointResultKind.False }),
            (GoapBreakpointKind.ActionUpdate,
                new[]
                {
                    GoapBreakpointResultKind.Finished, GoapBreakpointResultKind.Continuing,
                    GoapBreakpointResultKind.Failed,
                }),
        };

        var existing = _controller.GoapBreakpoints
            .Where(p => p.NodeId == node.Id || p.NodeId == -1)
            .ToList();
        var menu = ContextMenuBuilder
            .New(Root!.ModalRoot)
            .Submenu("Add breakpoint",
                r => r
                    .Submenus(node.Actions,
                        act => act.Name,
                        (b, _, actIndex) => b
                            .Submenus(kinds,
                                k => PointTypeString(k.Kind),
                                (s, k) => s.Items(k.Results,
                                    res => res.ToString(),
                                    result => _controller.AddBreakpoint(uid, node.Id, actIndex, k.Kind, result)))
                            .Item("Shutdown",
                                () => _controller.AddBreakpoint(uid,
                                    node.Id,
                                    actIndex,
                                    GoapBreakpointKind.ActionShutdown,
                                    GoapBreakpointResultKind.None)))
                    .Submenu("Planning",
                        s => s.Items(new[] { GoapBreakpointResultKind.True, GoapBreakpointResultKind.False },
                            result => result == GoapBreakpointResultKind.True ? "Success" : "Failure",
                            result => _controller.AddBreakpoint(uid,
                                node.Id,
                                -1,
                                GoapBreakpointKind.Planning,
                                result))))
            .When(existing.Count > 0,
                r => r.Submenu("Remove breakpoint",
                    b => b
                        .Items(existing, GetName, point => _controller.RemoveBreakpoint(point))))
            .Build();

        menu.Open(UIBox2.FromDimensions(args.PointerLocation.Position / UIScale, new Vector2(1, 1)));
    }

    private void UpdateLayout()
    {
        if (_layout == null)
            return;

        var layout = _layout.Value.Scaled(_zoom);

        foreach (var (id, control) in _nodeControls)
        {
            if (!layout.Nodes.TryGetValue(id, out var placement))
                continue;

            LayoutContainer.SetPosition(control, placement.Position);
            control.SetSize = placement.Size;
        }

        EdgeOverlay.SetData(
            _nodeControls,
            layout.EdgePaths,
            layout.EdgePaths
                .Select(xy => (xy.Key, ConnectionColor(xy.Key)))
                .ToDictionary());

        GraphRoot.MinSize = layout.TotalSize;
        return;

        Color ConnectionColor((int From, int To) fromTo)
        {
            if (_plan?.Nodes.Any(x => x.NodeId == fromTo.From && x.InPlan) == true)
                return Color.LimeGreen;

            if (_graph?.Nodes.FirstOrNull(x => x.Id == fromTo.From)?.Compound is not { } compound)
                return Color.DimGray; // Default color

            // Some magic
            var hash = (uint)compound.GetHashCode();
            hash = (hash ^ (hash >> 16)) * 0x45d9f3b;
            hash = (hash ^ (hash >> 16)) * 0x45d9f3b;
            hash ^= hash >> 16;
            var hue = hash / (float)uint.MaxValue;
            return Color.FromHsv(new(hue, 0.5f, 0.6f, 1f));
        }
    }

    private void SelectNodeId(int id)
    {
        if (_graph == null)
            return;

        PointType.Visible = true;
        Index.Visible = false;
        Result.Visible = false;
        PointType.Clear();

        NodeId.Select(NodeId.GetIdx(id));

        PointType.AddItem("Action Startup", 0);
        PointType.SetItemMetadata(0, GoapBreakpointKind.ActionStartup);
        PointType.AddItem("Action Update", 1);
        PointType.SetItemMetadata(1, GoapBreakpointKind.ActionUpdate);
        PointType.AddItem("Action Shutdown", 2);
        PointType.SetItemMetadata(2, GoapBreakpointKind.ActionShutdown);
        PointType.AddItem("Planning", 3);
        PointType.SetItemMetadata(3, GoapBreakpointKind.Planning);

        UpdateConfirm();
    }

    private void UpdateConfirm()
    {
        Confirm.Disabled = _graph == null
                           || _target == null
                           || PointType.ItemCount == 0
                           || PointType.SelectedMetadata == null
                           || Result.ItemCount == 0
                           || Result.SelectedMetadata == null;
    }

    private string GetName(GoapBreakpoint point)
    {
        if (_graph?.Nodes is not { } nodes)
            return string.Empty;

        var nodeName = point.NodeId != -1
            ? $"#{point.NodeId}"
            : "#Any";
        var actName = point.Index != -1
            ? $"{nodes[point.NodeId].Actions[point.Index].Name} ({point.Index})"
            : "Any";
        var str = $"{nodeName} {actName}";

        return point.Kind switch
        {
            GoapBreakpointKind.ActionStartup => $"{str} Startup: {point.Result}",
            GoapBreakpointKind.ActionUpdate => $"{str} Update: {point.Result}",
            GoapBreakpointKind.ActionShutdown => $"{str} Shutdown",
            GoapBreakpointKind.Planning => $"{nodeName} Planning: {point.Result}",
            _ => throw new ArgumentOutOfRangeException(),
        };
    }

    private static string PointTypeString(GoapBreakpointKind type)
    {
        return type switch
        {
            GoapBreakpointKind.ActionStartup => "Startup",
            GoapBreakpointKind.ActionUpdate => "Update",
            GoapBreakpointKind.ActionShutdown => "Shutdown",
            GoapBreakpointKind.Planning => "Planning",
            _ => throw new ArgumentOutOfRangeException(),
        };
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        var delta = args.Delta;
        var zoomChange = delta.Y > 0 ? ZoomStep : -ZoomStep;
        _zoom = Math.Clamp(_zoom + zoomChange, MinZoom, MaxZoom);
        UpdateLayout();
        args.Handle();
    }

    protected override void ExitedTree()
    {
        foreach (var (point, _) in _points)
        {
            _controller.RemoveBreakpoint(point);
        }

        if (_target != null)
            _controller.Unsubscribe(_target.Value);

        _controller.OnBreakpointAdded += _onBreakpointAdded;
        _controller.OnBreakpointRemoved += _onBreakpointRemoved;
        _controller.OnBreakpointHit += _onBreakpointHit;

        base.ExitedTree();
    }

    private void _onBreakpointAdded(GoapBreakpoint point)
    {
        if (_points.TryGetValue(point, out var check))
        {
            check.Check.Pressed = true;
            return;
        }

        check = new BreakpointControl();
        check.Check.Text = GetName(point);
        check.Check.Pressed = true;
        _points[point] = check;
        Breakpoints.AddChild(check);

        check.Check.OnToggled += _ =>
        {
            if (!check.Check.Pressed)
                _controller.RemoveBreakpoint(point);
            else
                _controller.AddBreakpoint(point);
        };

        check.RemoveButton.OnPressed += _ =>
        {
            _points.Remove(point);
            Breakpoints.RemoveChild(check);
            _controller.RemoveBreakpoint(point);
        };
    }

    private void _onBreakpointRemoved(GoapBreakpoint point)
    {
        if (_points.TryGetValue(point, out var check))
            check.Check.Pressed = false;
    }

    private void _onBreakpointHit((GoapBreakpoint Point, GoapPlanDebugInfo Plan) point)
    {
        if (_graph != null)
            Update(_graph.Value, point.Plan);

        if (_nodeControls.TryGetValue(point.Point.NodeId, out var node))
            CenterOnNode(node);
    }
}

