using System.Linq;
using Content.Client._RF.NPC.UI;
using Content.Client._RF.Stylesheets;
using Content.Shared._RF.NPC.GOAP;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RF.NPC.GOAP.UI;

[GenerateTypedNameReferences]
public sealed partial class GraphNodeControl : DebugNodeControl
{
    private readonly AiDevWindowUiController _controller;
    private readonly GoapStaticGraphNodeDebug _graphNode;
    private List<GoapActionDebugInfo>? _actions;
    private readonly GoapNodeDebugEntry? _debug;
    private bool _selected;

    public GraphNodeControl()
    {
        RobustXamlLoader.Load(this);
        _controller = UserInterfaceManager.GetUIController<AiDevWindowUiController>();
    }

    public GraphNodeControl(
        GoapStaticGraphNodeDebug graphNode,
        List<GoapActionDebugInfo>? actions = null,
        GoapNodeDebugEntry? debug = null)
    {
        RobustXamlLoader.Load(this);
        Title.Text = $"{graphNode.Compound ?? "Node"} #{graphNode.Id}";

        TabContainer.SetTabTitle(CommonTab, "Common");
        TabContainer.SetTabTitle(ActionsTab, "Actions");
        TabContainer.SetTabTitle(PreconditionsTab, "Preconditions");

        TabContainer.SetTabVisible(ActionsTab, graphNode.Actions.Count > 0);
        TabContainer.SetTabVisible(PreconditionsTab, graphNode.Preconditions.Count > 0);

        _graphNode = graphNode;
        _actions = actions;
        _debug = debug;
        _controller = UserInterfaceManager.GetUIController<AiDevWindowUiController>();

        _controller.OnBreakpointHit += _onBreakpointHit;
        _controller.OnBreakpointAdded += _onBreakpointAdded;
        _controller.OnBreakpointRemoved += _onBreakpointRemoved;

        OnMouseEntered += _ => _selected = true;
        OnMouseExited += _ => _selected = false;

        // ActionsTab
        AddAction();

        // PreconditionsTab
        for (var i = 0; i < graphNode.Preconditions.Count; i++)
        {
            var (condition, entityCon) = graphNode.Preconditions[i];

            // Static graph info
            var box = debug == null
                ? AiUiHelper.AddBox(PreconditionsTab, condition.Type)
                : AiUiHelper.AddBox(PreconditionsTab,
                    condition.Type,
                    debug.Value.Preconditions[i].Result
                        ? $"[color={StyleFortress.LightGood.ToHex()}]True[/color]"
                        : $"[color={StyleFortress.LightBad.ToHex()}]False[/color]");
            AiUiHelper.AddLabel(box.Content, "Type:", entityCon ? "ECS" : "Static");
            AiUiHelper.AddTypes(box.Content, "Fields", condition.Reflection);

            // Planing debug info
            if (debug == null)
                continue;

            var debugCon = debug.Value.Preconditions[i];
            AiUiHelper.AddTypes(box.Content, "State Snapshot", debugCon.Dump.StateSnapshot.State);
            AiUiHelper.AddLogs(box.Content, debugCon.Dump.Dump);
        }

        // Common
        UpdateStatus();

        AiUiHelper.AddTypes(CommonTab, "Effects", graphNode.EffectsDump.State);

        if (debug == null)
            return;

        AiUiHelper.AddLabel(CommonTab, "Cost:", $"{debug.Value.TaskCost}");
        AiUiHelper.AddTypes(CommonTab, "State Before", debug.Value.StateBefore.State);
        AiUiHelper.AddTypes(CommonTab, "State After", debug.Value.StateAfter?.State);

        if (debug.Value.SkipReason != null)
            AiUiHelper.AddExpandLabel(CommonTab, "Skip Reason",  debug.Value.SkipReason);
    }

    private static string UpdateText(GoapActionResult result)
    {
        return result switch
        {
            GoapActionResult.Finished => $"[color={StyleFortress.LightGood.ToHex()}]Finished[/color]",
            GoapActionResult.Failed => $"[color={StyleFortress.LightBad.ToHex()}]Failed[/color]",
            GoapActionResult.Continuing => $"[color={Color.Yellow.ToHex()}]Continuing[/color]",
            _ => throw new ArgumentOutOfRangeException(),
        };
    }

    private static string? ActionStatusText(GoapActionDebugInfo action)
    {
        if (action.StartupSuccess == null)
            return null;

        if (action.StartupSuccess == false)
            return $"[color={StyleFortress.LightBad.ToHex()}]Fail[/color]";

        if (action.UpdateDumps.Count == 0)
            return $"[color={Color.Yellow.ToHex()}]Not Started[/color]";

        return action.UpdateDumps.Count > 0 ? UpdateText(action.UpdateDumps.Last().Result) : null;
    }

    private void AddAction()
    {
        for (var i = 0; i < _graphNode.Actions.Count; i++)
        {
            var index = i;
            var action = _graphNode.Actions[i];

            if (_actions?.FirstOrNull(x => x.ActionIndex == index) is not { } debugAction)
            {
                // Static graph info
                var staticBox = AiUiHelper.AddBox(ActionsTab, action.Type);
                AiUiHelper.AddTypes(staticBox.Content, "Fields", action.Reflection);
                continue;
            }

            // Runtime debug info
            var box = AiUiHelper.AddBox(ActionsTab, action.Type, ActionStatusText(debugAction));
            AiUiHelper.AddTypes(box.Content, "Fields", action.Reflection);

            // Startup
            if (debugAction.StartupSuccess != null)
            {
                var startupBox = AiUiHelper.AddBox(
                    box.Content,
                    "Startup",
                    debugAction.StartupSuccess == true
                        ? $"[color={StyleFortress.LightGood.ToHex()}]Success[/color]"
                        : $"[color={StyleFortress.LightBad.ToHex()}]Fail[/color]");

                if (debugAction.StartupDump != null)
                {
                    AiUiHelper.AddTypes(startupBox.Content, "State Snapshot", debugAction.StartupDump.Value.StateSnapshot.State);
                    AiUiHelper.AddLogs(startupBox.Content, debugAction.StartupDump.Value.Dump);
                }
            }

            // Shutdown
            if (debugAction.ShutdownDump != null)
            {
                var shutdownBox = AiUiHelper.AddBox(box.Content, "Shutdown");

                AiUiHelper.AddTypes(shutdownBox.Content, "State Snapshot", debugAction.ShutdownDump.Value.StateSnapshot.State);
                AiUiHelper.AddLogs(shutdownBox.Content, debugAction.ShutdownDump.Value.Dump);
            }

            // Updates
            if (debugAction.UpdateDumps.Count == 0)
                continue;

            var updateBox = AiUiHelper.AddBox(box.Content, "Updates", UpdateText(debugAction.UpdateDumps.Last().Result));

            foreach (var update in debugAction.UpdateDumps)
            {
                var upd = AiUiHelper.AddBox(updateBox.Content, update.Tick.ToString(), UpdateText(update.Result));
                AiUiHelper.AddTypes(upd.Content, "State Snapshot", update.Dump.StateSnapshot.State);
                AiUiHelper.AddLogs(upd.Content, update.Dump.Dump);
            }
        }
    }

    private void UpdateStatus()
    {
        StatusLabel.Text = string.Empty;
        SubTitle.Text = string.Empty;

        if (_controller.GoapBreakpoints.Any(x => x.NodeId == _graphNode.Id))
            SubTitle.Text = $@"[color={StyleFortress.LightBad.ToHex()}]\[BP\][/color]";

        if (_debug?.IndexInPlan is { } index)
            SubTitle.Text = $"{StatusLabel.Text} [color={Color.Aqua.ToHex()}]#{index}[/color]";

        if (_debug is { HelpGoal: true })
            StatusLabel.Text = $@"[color={StyleFortress.GoldFortress.ToHex()}]\[GOAL\][/color]";

        if (_actions?.Count > 0)
        {
            StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.Aqua.ToHex()}]\[PLAN\][/color]";

            if (_actions.All(x => x.StartupSuccess == null))
                StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.Yellow.ToHex()}]\[START\][/color]";
            else if (_actions.Any(x
                    => x.UpdateDumps.Any(y
                           => y.Result == GoapActionResult.Failed)
                       || x.StartupSuccess == false))
                StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.BetterViolet.ToHex()}]\[FAIL\][/color]";
            else if (_actions.Any(x
                    => x.StartupSuccess == null || x.UpdateDumps.Any(y
                        => y.Result == GoapActionResult.Continuing)))
                StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.Yellow.ToHex()}]\[CONT\][/color]";
            else if (_actions.Count > 0
                     && _actions.All(x
                         => x.UpdateDumps.Any(y
                             => y.Result == GoapActionResult.Finished)))
                StatusLabel.Text = $@"{StatusLabel.Text} [color={StyleFortress.Good.ToHex()}]\[FINISH\][/color]";
        }
        else
        {
            StatusLabel.Text = _debug?.PreconditionsMet switch
            {
                false => $@"{StatusLabel.Text} [color={StyleFortress.LightBad.ToHex()}]\[NOT MET\][/color]",
                true => $@"{StatusLabel.Text} [color={StyleFortress.LightGood.ToHex()}]\[MET\][/color]",
                _ => StatusLabel.Text,
            };
        }

        SubTitle.Text = $"[bold]{SubTitle.Text.Trim()}[/bold]";
        StatusLabel.Visible = !string.IsNullOrWhiteSpace(StatusLabel.Text);
        StatusLabel.Text = $"[bold]{StatusLabel.Text.Trim()}[/bold]";
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        if (_selected)
        {
            var box = UIBox2.FromDimensions(Vector2i.Zero, PixelSize).Scale(1.01f);
            handle.DrawRect(box, StyleFortress.GoldFortress);
        }

        base.Draw(handle);
    }

    protected override void ExitedTree()
    {
        _controller.OnBreakpointHit -= _onBreakpointHit;
        _controller.OnBreakpointAdded -= _onBreakpointAdded;
        _controller.OnBreakpointRemoved -= _onBreakpointRemoved;
        base.ExitedTree();
    }

    private void _onBreakpointHit((GoapBreakpoint Point, GoapPlanDebugInfo Plan) args)
    {
        if (args.Point.NodeId == _graphNode.Id)
            TabContainer.CurrentTab = 1;

        _actions = args.Plan.Actions
            .Where(x => x.NodeIndex == _graphNode.Id)
            .ToList();

        ActionsTab.RemoveAllChildren();
        AddAction();
        UpdateStatus();
    }

    private void _onBreakpointAdded(GoapBreakpoint point)
    {
        UpdateStatus();
    }

    private void _onBreakpointRemoved(GoapBreakpoint point)
    {
        UpdateStatus();
    }
}
