using System.Linq;
using Content.Client._RF.NPC.UI;
using Content.Client._RF.Stylesheets;
using Content.Shared._RF.NPC.GOAP;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RF.NPC.GOAP.UI;

[GenerateTypedNameReferences]
public sealed partial class GraphNodeControl : Control
{
    public GraphNodeControl()
    {
        RobustXamlLoader.Load(this);
    }

    public GraphNodeControl(
        GoapStaticGraphNodeDebug graphNode,
        List<GoapActionDebugInfo>? actions = null,
        GoapNodeDebugEntry? debug = null)
    {
        RobustXamlLoader.Load(this);
        Title.Text = $"{debug?.Compound ?? "Node"} #{graphNode.Id}";

        TabContainer.SetTabTitle(CommonTab, "Common");
        TabContainer.SetTabTitle(ActionsTab, "Actions");
        TabContainer.SetTabTitle(PreconditionsTab, "Preconditions");

        TabContainer.SetTabVisible(ActionsTab, graphNode.Actions.Count > 0);
        TabContainer.SetTabVisible(PreconditionsTab, graphNode.Preconditions.Count > 0);

        var controller = UserInterfaceManager.GetUIController<AiDevWindowUiController>();

        controller.OnBreakpointHit += args =>
        {
            if (args.Point.NodeId == graphNode.Id)
                TabContainer.CurrentTab = 1;

            ActionsTab.RemoveAllChildren();
            AddAction(args.Actions);
            UpdateStatus(args.Actions);
        };

        // ActionsTab
        AddAction(actions ?? new());

        // PreconditionsTab
        for (var i = 0; i < graphNode.Preconditions.Count; i++)
        {
            var condition = graphNode.Preconditions[i];

            // Static graph info
            var box = debug == null
                ? AddBox(PreconditionsTab, condition.Type)
                : AddBox(PreconditionsTab,
                    condition.Type,
                    debug.Value.Preconditions[i].Result
                        ? $"[color={StyleFortress.LightGood.ToHex()}]True[/color]"
                        : $"[color={StyleFortress.LightBad.ToHex()}]False[/color]");
            AddTypes(box.Content, "Fields", condition.Reflection);

            // Planing debug info
            if (debug == null)
                continue;

            var debugCon = debug.Value.Preconditions[i];
            AddTypes(box.Content, "State Snapshot", debugCon.Dump.StateSnapshot.State);
            AddLogs(box.Content, debugCon.Dump.Dump);
        }

        // Common
        UpdateStatus(actions);

        AddTypes(CommonTab, "Effects", graphNode.EffectsDump.State);

        if (debug == null)
            return;

        AddLabel(CommonTab, "Cost:", $"{debug.Value.TaskCost}");
        AddLabel(CommonTab, "Heuristic:", $"{debug.Value.Heuristic}");
        AddTypes(CommonTab, "State Before", debug.Value.StateBefore.State);
        AddTypes(CommonTab, "State After", debug.Value.StateAfter?.State);

        if (debug.Value.SkipReason != null)
            AddExpandLabel(CommonTab, "Skip Reason",  debug.Value.SkipReason);

        return;

        void AddTypes(Control parent, string title, Dictionary<string, (string, string)>? data)
        {
            if (data == null || data.Count == 0)
                return;

            AddSeparator(parent);
            var expandBox = new ExpandableBox { Title = $"[bold]{title}[/bold]" };
            parent.AddChild(expandBox);

            foreach (var (key, (type, value)) in data)
            {
                AddSeparator(expandBox.Content);
                expandBox.Content.AddChild(new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(0f, 1f),
                    MaxWidth = 300,
                    Children =
                    {
                        new BoxContainer
                        {
                            Children =
                            {
                                new RichTextLabel { Text = $"[bold]{key}[/bold]" },
                                new Control { HorizontalExpand = true },
                                new RichTextLabel { Text = $":{type}" },
                            },
                        },
                        new BoxContainer
                        {
                            Children =
                            {
                                new RichTextLabel { Text = value },
                            },
                        },
                    },
                });
            }
        }

        void AddLabel(Control parent, string left, string right)
        {
            AddSeparator(parent);
            parent.AddChild(new BoxContainer
            {
                Margin = new Thickness(20f, 0f, 5f, 0f),
                Children =
                {
                    new RichTextLabel { Text = $"[bold]{left}[/bold]" },
                    new Control { HorizontalExpand = true },
                    new RichTextLabel { Text = $"[bold]{right}[/bold]" },
                },
            });
        }

        void AddExpandLabel(Control parent, string title, string text)
        {
            AddSeparator(parent);
            var expandBox = new ExpandableBox { Title = $"[bold]{title}[/bold]" };
            parent.AddChild(expandBox);
            expandBox.Content.AddChild(new RichTextLabel { Text = text });
        }

        void AddSeparator(Control parent)
        {
            parent.AddChild(new PanelContainer
            {
                StyleClasses = { StyleFortress.StyleClassLowDividerDark },
                Margin = new Thickness(3f, 2f),
            });
        }

        void AddLogs(Control parent, string? logs)
        {
            if (string.IsNullOrWhiteSpace(logs))
                return;

            AddSeparator(parent);
            var box = new ExpandableBox { Title = "[bold]Logs[/bold]" };
            parent.AddChild(box);
            var dumps = logs.Split('\n', StringSplitOptions.RemoveEmptyEntries);

            foreach (var dump in dumps)
            {
                box.Content.AddChild(new RichTextLabel
                {
                    Text = dump,
                    MaxWidth = 300,
                });
            }
        }

        ExpandableBox AddBox(Control parent, string title, string? second = null)
        {
            AddSeparator(parent);
            var box = new ExpandableBox
            {
                Title = $"[bold]{title}[/bold]",
                SecondaryText = second != null ? $"[bold]{second}[/bold]" : null,
            };
            parent.AddChild(box);
            return box;
        }

        string UpdateText(GoapActionResult result)
        {
            return result switch
            {
                GoapActionResult.Finished => $"[color={StyleFortress.LightGood.ToHex()}]Finished[/color]",
                GoapActionResult.Failed => $"[color={StyleFortress.LightBad.ToHex()}]Failed[/color]",
                GoapActionResult.Continuing => $"[color={Color.Yellow.ToHex()}]Continuing[/color]",
                _ => throw new ArgumentOutOfRangeException(),
            };
        }

        void AddAction(List<GoapActionDebugInfo> actionsDebug)
        {
            for (var i = 0; i < graphNode.Actions.Count; i++)
            {
                var index = i;
                var action = graphNode.Actions[i];

                // Static graph info
                var box = AddBox(ActionsTab, action.Type);
                AddTypes(box.Content, "Fields", action.Reflection);

                // Runtime debug info
                if (actionsDebug?.FirstOrNull(x => x.ActionIndex == index) is not { } debugAction)
                    continue;

                // Startup
                if (debugAction.StartupSuccess != null)
                {
                    var startupBox = AddBox(
                        box.Content,
                        "Startup",
                        debugAction.StartupSuccess == true
                            ? $"[color={StyleFortress.LightGood.ToHex()}]Success[/color]"
                            : $"[color={StyleFortress.LightBad.ToHex()}]Fail[/color]");

                    if (debugAction.StartupDump != null)
                    {
                        AddTypes(startupBox.Content, "State Snapshot", debugAction.StartupDump.Value.StateSnapshot.State);
                        AddLogs(startupBox.Content, debugAction.StartupDump.Value.Dump);
                    }
                }

                // Shutdown
                if (debugAction.ShutdownDump != null)
                {
                    var shutdownBox = AddBox(box.Content, "Shutdown");

                    AddTypes(shutdownBox.Content, "State Snapshot", debugAction.ShutdownDump.Value.StateSnapshot.State);
                    AddLogs(shutdownBox.Content, debugAction.ShutdownDump.Value.Dump);
                }

                // Updates
                if (debugAction.UpdateDumps.Count == 0)
                    continue;

                var updateBox = AddBox(box.Content, "Updates", UpdateText(debugAction.UpdateDumps.Last().Result));

                foreach (var update in debugAction.UpdateDumps)
                {
                    var upd = AddBox(updateBox.Content, update.Tick.ToString(), UpdateText(update.Result));
                    AddTypes(upd.Content, "State Snapshot", update.Dump.StateSnapshot.State);
                    AddLogs(upd.Content, update.Dump.Dump);
                }
            }
        }

        void UpdateStatus(List<GoapActionDebugInfo>? actionsDebug)
        {
            StatusLabel.Text = string.Empty;

            if (actionsDebug?.Any(x => x.NodeIndex == graphNode.Id) == true)
            {
                StatusLabel.Text = $@"[color={Color.Aqua.ToHex()}]\[In Plan\][/color]";

                if (actionsDebug.Any(x => x.StartupSuccess == null))
                    StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.Yellow.ToHex()}]\[Not Started\][/color]";

                if (actionsDebug.Any(x
                        => x.UpdateDumps.Any(y
                            => y.Result == GoapActionResult.Continuing)))
                    StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.Yellow.ToHex()}]\[Continuing\][/color]";

                if (actionsDebug.Any(x
                        => x.UpdateDumps.Any(y
                               => y.Result == GoapActionResult.Failed)
                           || x.StartupSuccess == false))
                    StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.BetterViolet.ToHex()}]\[Failed\][/color]";

                if (actionsDebug.Count > 0
                    && actionsDebug.All(x
                        => x.UpdateDumps.Any(y
                            => y.Result == GoapActionResult.Finished)))
                    StatusLabel.Text = $@"{StatusLabel.Text} [color={StyleFortress.Good.ToHex()}]\[Finished\][/color]";
            }
            else
            {
                if (debug is { AddedToOpenList: false, PreconditionsMet: false })
                    StatusLabel.Text = $@"[color={StyleFortress.GraySilver.ToHex()}]\[Skipped\][/color]";

                StatusLabel.Text = debug?.PreconditionsMet switch
                {
                    false => $@"{StatusLabel.Text} [color={StyleFortress.LightBad.ToHex()}]\[NotMet\][/color]",
                    true => $@"{StatusLabel.Text} [color={StyleFortress.LightGood.ToHex()}]\[Met\][/color]",
                    _ => StatusLabel.Text,
                };
            }

            StatusLabel.Text = $"[bold]{StatusLabel.Text}[/bold]";
        }
    }
}
