using Content.Shared._RF.Workshops.Prototypes;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._RF.Workshops.UI;

[GenerateTypedNameReferences]
public sealed partial class RecipeQueueButton : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    public event Action? OnRemoved;
    public event Action? OnToggleRepeat;
    public event Action? OnToggleSuspend;

    private readonly TimeSpan _endAt;

    public RecipeQueueButton()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public RecipeQueueButton(
        ProtoId<WorkshopRecipePrototype> protoId,
        TimeSpan? endAt = null,
        bool subRecipe = false,
        bool repeat = false,
        bool suspended = false,
        bool active = false)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        if (!_proto.Resolve(protoId, out var proto))
            return;

        _endAt = endAt ?? TimeSpan.Zero;

        Icon.SetPrototype(proto.Result);
        RecipeName.Text = _proto.Index(proto.Result).Name;
        CloseButton.Visible = !subRecipe;

        Status.Text = GetStatus(active, repeat, suspended);

        if (subRecipe)
            Margin = new Thickness(Margin.Left + 20, Margin.Top, Margin.Right, Margin.Bottom);
        else
        {
            TooltipSupplier = _ =>
            {
                var msg = FormattedMessage.FromMarkupOrThrow(
                    ToolTip = Loc.GetString("workshop-menu-recipe-queue-tooltip"));
                var tooltip = new Tooltip();
                tooltip.SetMessage(msg);
                return tooltip;
            };
            CloseButton.OnPressed += _ => OnRemoved?.Invoke();
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_endAt == TimeSpan.Zero)
            return;

        RemainingTime.Text = ContentLocalizationManager.FormatTimeShort(_endAt - _timing.CurTime);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function == EngineKeyFunctions.UseSecondary)
            OnToggleRepeat?.Invoke();

        if (args.Function == EngineKeyFunctions.Use)
            OnToggleSuspend?.Invoke();
    }

    private static string GetStatus(bool active = false, bool repeat = false, bool suspended = false)
    {
        var text = string.Empty;

        if (active)
            text = Loc.GetString("workshop-menu-recipe-queue-status-active");

        if (repeat)
            text = $"{text}{Loc.GetString("workshop-menu-recipe-queue-status-repeat")}";

        if (suspended)
            text = $"{text}{Loc.GetString("workshop-menu-recipe-queue-status-suspended")}";

        return text;
    }
}

