using Content.Shared._RF.Workshops.Prototypes;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RF.Workshops.UI;

[GenerateTypedNameReferences]
public sealed partial class RecipeQueueButton : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    public event Action? OnRemoved;

    private readonly TimeSpan _endAt;

    public RecipeQueueButton()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public RecipeQueueButton(
        ProtoId<WorkshopRecipePrototype> protoId,
        TimeSpan? endAt = null,
        bool subRecipe = false)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        if (!_proto.Resolve(protoId, out var proto))
            return;

        _endAt = endAt ?? TimeSpan.Zero;

        Icon.SetPrototype(proto.Result);
        RecipeName.Text = _proto.Index(proto.Result).Name;
        CloseButton.Visible = !subRecipe;

        if (endAt != TimeSpan.Zero)
            Status.Text = Loc.GetString("workshop-menu-recipe-queue-status-active");

        if (subRecipe)
            Margin = new Thickness(Margin.Left + 20, Margin.Top, Margin.Right, Margin.Bottom);
        else
            CloseButton.OnPressed += _ => OnRemoved?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_endAt == TimeSpan.Zero)
            return;

        RemainingTime.Text = ContentLocalizationManager.FormatTimeShort(_endAt - _timing.CurTime);
    }
}

