using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Workshops.UI;

[GenerateTypedNameReferences]
public sealed partial class WorkshopRecipeIngredient : Control
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private const string ReagentIconPath = "/Textures/_RF/Interface/droplet-solid-full.svg.192dpi.png";

    public WorkshopRecipeIngredient()
    {
        RobustXamlLoader.Load(this);
    }

    public WorkshopRecipeIngredient(EntProtoId protoId, int count)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        ProtoIcon.SetPrototype(protoId);
        Label.Text = _proto.Index(protoId).Name;
        Quantity.Text = $"x{count}";
    }

    public WorkshopRecipeIngredient(ProtoId<StackPrototype> protoId, int count)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        var system = _entity.System<SpriteSystem>();
        var proto = _proto.Index(protoId);
        Icon.Texture = proto.Icon != null ? system.Frame0(proto.Icon) : null;
        Label.Text = Loc.GetString(proto.Name);
        Quantity.Text = $"x{count}";
    }

    public WorkshopRecipeIngredient(ProtoId<ReagentPrototype> protoId, FixedPoint2 quantity)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        var proto = _proto.Index(protoId);
        ProtoIcon.Visible = false;
        Icon.Visible = true;
        Icon.TexturePath = ReagentIconPath;
        Icon.ModulateSelfOverride = proto.SubstanceColor;
        Label.Text = Loc.GetString(proto.LocalizedName);
        Quantity.Text = Loc.GetString("workshop-menu-reagent-quantity", ("quantity", quantity));
    }

    protected override void Parented(Control newParent)
    {
        base.Parented(newParent);

        var index = 0;

        foreach (var child in newParent.Children)
        {
            if (child is not WorkshopRecipeIngredient control)
                continue;

            index++;

            if (control != this)
                continue;

            Number.Text = $"{index}.";
            break;
        }
    }
}

