using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RF.NPC;
using Content.Shared._RF.Stockpile.Components;
using Content.Shared._RF.Stockpile.Systems;
using Content.Shared._RF.Workshops;
using Content.Shared._RF.Workshops.Prototypes;
using Content.Shared._RF.Workshops.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Workshops.UI;

[GenerateTypedNameReferences]
public sealed partial class WorkshopMenu : FancyWindow
{
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private ProtoId<WorkshopRecipeTablePrototype>? _table;
    private ProtoId<WorkshopRecipeGroupPrototype>? _group;
    private HashSet<ProtoId<WorkshopRecipePrototype>> _tableRecipes = new();
    private readonly Dictionary<RecipeQueueButton, int> _queueButtons = new();

    public event Action<int>? OnRemoved;
    public event Action<ProtoId<WorkshopRecipePrototype>>? OnAdded;
    public event Action<int>? OnToggleRepeat;
    public event Action<int>? OnToggleSuspend;
    public event Action<Entity<StockpileComponent>>? OnSupplyStockpile;

    public WorkshopMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Search.OnTextChanged += _ => UpdateSearchList();
        ClearSearch.OnPressed += _ => Search.SetText(string.Empty, true);
        BackButton.OnPressed += _ => BackGroup();
        SuppliedStock.OnItemSelected += args =>
        {
            SuppliedStock.SelectId(args.Id);

            if (SuppliedStock.SelectedMetadata is Entity<StockpileComponent> ent)
                OnSupplyStockpile?.Invoke(ent);
        };
    }

    public void SetTitle(EntityUid uid)
    {
        Title = _entity.GetComponent<MetaDataComponent>(uid).EntityPrototype?.Name;
    }

    public void UpdateRecipes(ProtoId<WorkshopRecipeTablePrototype> protoId)
    {
        if (_table == protoId)
            return;

        _table = protoId;
        _tableRecipes = _entity.System<WorkshopSystem>().GetTableRecipes(protoId);

        BuildRecipesList(null);
    }

    public void UpdateContents(NetEntity[] contents)
    {
        ContentsBox.RemoveAllChildren();

        foreach (var uid in contents)
        {
            ContentsBox.AddChild(new RecipeResultButton(_entity.GetEntity(uid)));
        }
    }

    public void UpdateUser(NetEntity? user)
    {
        if (!_entity.TryGetEntity(user, out var uid))
            UserLabel.Text = Loc.GetString("workshop-menu-no-user");
        else
        {
            UserLabel.Text = Loc.GetString("workshop-menu-user",
                ("user", _entity.GetComponent<MetaDataComponent>(uid.Value).EntityName));
        }
    }

    public void UpdateResults(NetEntity[] results, int resultsCapacity)
    {
        ResultsBox.RemoveAllChildren();
        ResultsLabel.Text = $"({results.Length}/{resultsCapacity})";

        foreach (var uid in results)
        {
            ResultsBox.AddChild(new RecipeResultButton(_entity.GetEntity(uid)));
        }
    }

    public void UpdateQueue(WorkshopQueue queue, int maxQueue)
    {
        _queueButtons.Clear();
        QueueBox.RemoveAllChildren();
        QueueLabel.Text = $"({queue.Count}/{maxQueue})";

        if (queue.Count == 0)
            return;

        for (var i = 0; i < queue.Count; i++)
        {
            var entry = queue.Queue[i];
            var path = entry.RemainingPath;

            var button = new RecipeQueueButton(
                entry.Recipe,
                path.Length == 0 ? entry.CraftingEndTime : null,
                repeat: entry.Repeat,
                suspended: entry.Suspended,
                active: path.Length == 0 && i == queue.Index);

            button.OnRemoved += () => OnRemoved?.Invoke(_queueButtons.GetValueOrDefault(button, -1));
            button.OnToggleRepeat += () => OnToggleRepeat?.Invoke(_queueButtons.GetValueOrDefault(button, -1));
            button.OnToggleSuspend += () => OnToggleSuspend?.Invoke(_queueButtons.GetValueOrDefault(button, -1));

            QueueBox.AddChild(button);
            _queueButtons[button] = i;

            for (var j = entry.PathIndex; j < path.Length; j++)
            {
                var subButton = new RecipeQueueButton(
                    path[j],
                    j == entry.PathIndex ? entry.CraftingEndTime : null,
                    subRecipe: true,
                    active: i == queue.Index && j == entry.PathIndex);
                QueueBox.AddChild(subButton);
            }
        }
    }

    public void UpdateSupplying(EntityUid uid)
    {
        if (_player.LocalEntity is not { } player)
            return;

        SuppliedStock.Clear();
        SuppliedStock.AddItem(Loc.GetString("workshop-menu-stock-none"), -1);

        var enumerator = _entity
            .System<OwnershipSystem>()
            .GetEntitiesEnumerator<StockpileComponent>(player);
        var system = _entity.System<ContainerStockSupplierSystem>();

        var idx = 0;
        while (enumerator.MoveNext(out var stock, out var stockComp))
        {
            SuppliedStock.AddItem(_entity.GetComponent<MetaDataComponent>(stock).EntityName, idx);
            SuppliedStock.SetItemMetadata(idx, new Entity<StockpileComponent>(stock, stockComp));

            if (system.IsSupplying(uid, stock))
                SuppliedStock.SelectId(idx);

            idx++;
        }
    }

    private void BuildRecipesList(ProtoId<WorkshopRecipeGroupPrototype>? group)
    {
        RecipesBox.RemoveAllChildren();
        RecipesScroll.SetScrollValue(Vector2.Zero);
        BackButton.Disabled = group == null;
        _group = group;

        GroupLabel.Text = _proto.TryIndex(group, out var proto) ? proto.Name : string.Empty;

        if (_table == null)
            return;

        var system = _entity.System<WorkshopSystem>();

        foreach (var groupId in system.GetChildrenGroups(_group, _table.Value))
        {
            var button = new WorkshopRecipeButton(groupId, system.GetGroupCount(groupId, _tableRecipes));
            button.Button.OnPressed += _ => BuildRecipesList(groupId);
            RecipesBox.AddChild(button);
        }

        foreach (var recipe in system.GetGroupRecipes(_group, _tableRecipes))
        {
            var button = new WorkshopRecipeButton(recipe, _table.Value);
            button.Button.OnPressed += _ => OnAdded?.Invoke(recipe);
            RecipesBox.AddChild(button);
        }
    }

    private void UpdateSearchList()
    {
        RecipesScroll.SetScrollValue(Vector2.Zero);

        foreach (var child in RecipesBox.Children)
        {
            if (child is not WorkshopRecipeButton button)
                continue;

            button.Visible = button.NameLabel.Text?.Contains(Search.Text) ?? false;
        }
    }

    private void BackGroup()
    {
        if (_table == null)
            return;

        BuildRecipesList(_entity
            .System<WorkshopSystem>()
            .GetParentGroup(_group, _table.Value));
    }
}

