using Content.Client._RF.NPC.UI;
using Content.Client._RF.Stylesheets;
using Content.Shared._RF.NPC.UtilityAi;
using Content.Shared._RF.NPC.UtilityAi.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RF.NPC.UtilityAi.UI;

[GenerateTypedNameReferences]
public sealed partial class UtilityAiGoalControl : DebugNodeControl
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public UtilityAiGoalControl()
    {
        RobustXamlLoader.Load(this);
    }

    public UtilityAiGoalControl(
        UtilityAiGoalDebugInfo info,
        ProtoId<UtilityAiGoalPrototype>? current)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(CommonTab, "Common");
        TabContainer.SetTabTitle(CurvesTab, "Curves");
        TabContainer.SetTabTitle(ConditionsTab, "Conditions");

        TabContainer.SetTabVisible(CurvesTab, info.Curves.Length > 0);
        TabContainer.SetTabVisible(ConditionsTab, info.Preconditions.Length > 0);

        // Status
        if (current == info.ProtoId)
            StatusLabel.Text = $@"[color={StyleFortress.LightGood.ToHex()}]\[Active][/color]";

        if (info.AgentGoal)
            StatusLabel.Text = $@"{StatusLabel.Text} [color={StyleFortress.LightGood.ToHex()}]\[Available][/color]";

        if (info.FallbackGoal)
            StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.Yellow.ToHex()}]\[Fallback][/color]";

        if (info.ExecutableGoal)
            StatusLabel.Text = $@"{StatusLabel.Text} [color={Color.Orange.ToHex()}]\[Executable][/color]";

        if (info.Cooldown != TimeSpan.Zero)
            StatusLabel.Text = $@"{StatusLabel.Text} [color={StyleFortress.LightBad.ToHex()}]\[Cooldown][/color]";

        if (info.Penalty != 0)
            StatusLabel.Text = $@"{StatusLabel.Text} [color={StyleFortress.LightBad.ToHex()}]\[Penalty][/color]";

        StatusLabel.Text = $"[bold]{StatusLabel.Text}[/bold]";

        if (!_proto.Resolve(info.ProtoId, out var proto))
            return;

        Title.Text = $"[bold][color={proto.Color.ToHex()}]{info.ProtoId}[/color] ({info.Result:F2})[/bold]";

        // Common
        AiUiHelper.AddLabel(CommonTab, "Name:", Loc.GetString(proto.Name));
        AiUiHelper.AddLabel(CommonTab, "Fail Policy:", $"{proto.FailPolicy}");

        if (proto.FailPolicy == UtilityAiFailPolicy.Penalty)
            AiUiHelper.AddLabel(CommonTab, "Fail Penalty:", $"{proto.FailPenalty}");

        if (proto.Fallbacks.Count > 0)
            AiUiHelper.AddLabel(CommonTab, "Fallbacks:", string.Join(',', proto.Fallbacks));

        if (info.Cooldown > TimeSpan.Zero)
            AiUiHelper.AddLabel(CommonTab, "Cooldown:", $"{(info.Cooldown - _timing.CurTime).Seconds}s");

        AiUiHelper.AddTypes(CommonTab, "Goal State", info.GoalState.State);

        // Curves
        foreach (var curve in info.Curves)
        {
            var box = AiUiHelper.AddBox(CurvesTab, curve.Reflection.Name, $"{curve.Output:F3}");
            AiUiHelper.AddTypes(box.Content, "Fields", curve.Reflection);
            AiUiHelper.AddLabel(box.Content, "Input:", $"{curve.Input:F3}");
        }

        if (info.Penalty > 0)
            AiUiHelper.AddLabel(CurvesTab, "Total Penalty:", $"{info.Penalty:F3}");

        AiUiHelper.AddLabel(CurvesTab, "Modified Score:", $"{info.Modified:F3}");
        AiUiHelper.AddLabel(CurvesTab, "Total Score:", $"{info.Result:F3}");

        // Conditions
        foreach (var condition in info.Preconditions)
        {
            var box = AiUiHelper.AddBox(
                ConditionsTab,
                condition.Reflection.Name,
                condition.Result
                    ? $"[color={StyleFortress.LightGood.ToHex()}]True[/color]"
                    : $"[color={StyleFortress.LightBad.ToHex()}]False[/color]");
            AiUiHelper.AddTypes(box.Content, "Fields", condition.Reflection);
            AiUiHelper.AddTypes(box.Content, "State Snapshot", condition.Dump.StateSnapshot.State);
            AiUiHelper.AddLogs(box.Content, condition.Dump.Dump);
        }
    }
}

