using System.Linq;
using System.Numerics;
using Content.Shared._RF.NPC;
using Content.Shared._RF.NPC.UtilityAi;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.UtilityAi.UI;

[GenerateTypedNameReferences]
public sealed partial class UtilityAiDebugTab : Control
{
    /// <summary>
    /// The base size of the graph's nodes.
    /// </summary>
    [PublicAPI]
    public Vector2 NodeSize { get; set; } = new(100f);

    /// <summary>
    /// The minimum possible zoom level for the graph.
    /// </summary>
    [PublicAPI]
    public float MinZoom { get; set; } = 0.6f;

    /// <summary>
    /// The maximum possible zoom level for the graph.
    /// </summary>
    [PublicAPI]
    public float MaxZoom { get; set; } = 1.4f;

    /// <summary>
    /// How fast the zoom level will change.
    /// </summary>
    [PublicAPI]
    public float ZoomStep { get; set; } = 0.1f;

    private readonly Dictionary<int, Control> _nodeControls = new();
    private GraphLayout? _layout;
    private UtilityAiDebugInfo? _info;
    private float _zoom = 1.0f;

    public UtilityAiDebugTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(UtilityAiDebugInfo info)
    {
        _nodeControls.Clear();
        _info = info;

        NodesLayer.RemoveAllChildren();
        _layout = GraphLayoutBuilder.Build(info.Graph, NodeSize);

        foreach (var node in info.Graph.Nodes)
        {
            var control = new UtilityAiGoalControl(node, info.CurrentGoal);
            NodesLayer.AddChild(control);
            _nodeControls[node.Id] = control;
        }

        UpdateLayout();
    }


    private void UpdateLayout()
    {
        if (_layout == null)
            return;

        var layout = _layout.Value.Scaled(_zoom);

        foreach (var (id, control) in _nodeControls)
        {
            if (!layout.Nodes.TryGetValue(id, out var placement))
                continue;

            LayoutContainer.SetPosition(control, placement.Position);
            control.SetSize = placement.Size;
        }

        EdgeOverlay.SetData(
            _nodeControls,
            layout.EdgePaths,
            _info?.Graph.Nodes
                .Where(x => x.InActiveBranch)
                .Select(x => x.Id));

        GraphRoot.MinSize = layout.TotalSize;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        var delta = args.Delta;
        var zoomChange = delta.Y > 0 ? ZoomStep : -ZoomStep;
        _zoom = Math.Clamp(_zoom + zoomChange, MinZoom, MaxZoom);
        UpdateLayout();
        args.Handle();
    }
}

