using System.Linq;
using Content.Shared._RF.NPC.UtilityAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.UtilityAi.UI;

[GenerateTypedNameReferences]
public sealed partial class UtilityAiDebugTab : Control
{
    public UtilityAiDebugTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(UtilityAiDebugInfo info)
    {
        Grid.RemoveAllChildren();

        foreach (var goal in info.Goals.OrderByDescending(x => x.Result))
        {
            Grid.AddChild(new UtilityAiGoalControl(goal, info.CurrentGoal));
        }
    }
}

