using System.Linq;
using System.Numerics;
using Content.Shared._RF.NPC;
using Content.Shared._RF.NPC.UtilityAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.UtilityAi.UI;

[GenerateTypedNameReferences]
public sealed partial class UtilityAiDebugTab : Control
{
    public Vector2 NodeSize { get; set; }

    private readonly Dictionary<int, Control> _nodeControls = new();

    public UtilityAiDebugTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(UtilityAiDebugInfo info)
    {
        _nodeControls.Clear();

        NodesLayer.RemoveAllChildren();
        var layout = GraphLayoutBuilder.Build(info.Graph, NodeSize);

        GraphRoot.MinSize = layout.TotalSize;

        foreach (var node in info.Graph.Nodes)
        {
            var control = new UtilityAiGoalControl(node, info.CurrentGoal);
            NodesLayer.AddChild(control);

            if (!layout.Nodes.TryGetValue(node.Id, out var placement))
                continue;

            LayoutContainer.SetPosition(control, placement.Position);
            control.SetSize = placement.Size;
            _nodeControls[node.Id] = control;
        }

        EdgeOverlay.SetData(info.Graph,
            _nodeControls,
            info.Graph.Nodes
                .Where(x => x.InActiveBranch)
                .Select(x => x.Id));
    }
}

