using Content.Client._RF.NPC.GOAP.UI;
using Content.Client._RF.Stylesheets;
using Content.Shared._RF.NPC.UtilityAi;
using Content.Shared._RF.NPC.UtilityAi.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RF.NPC.UtilityAi.UI;

[GenerateTypedNameReferences]
public sealed partial class UtilityAiGoalControl : Control
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public UtilityAiGoalControl()
    {
        RobustXamlLoader.Load(this);
    }

    public UtilityAiGoalControl(
        UtilityAiGoalDebugInfo info,
        ProtoId<UtilityAiGoalPrototype>? current)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(CommonTab, "Common");
        TabContainer.SetTabTitle(CurvesTab, "Curves");
        TabContainer.SetTabTitle(ConditionsTab, "Conditions");

        TabContainer.SetTabVisible(CurvesTab, info.Curves.Length > 0);
        TabContainer.SetTabVisible(ConditionsTab, info.Preconditions.Length > 0);

        // Status
        if (current == info.Id)
            StatusLabel.Text = $@"[color={StyleFortress.LightGood.ToHex()}]\[Active][/color]";

        if (info.AgentGoal)
            StatusLabel.Text = $@"{StatusLabel.Text} [color={StyleFortress.LightGood.ToHex()}]\[Available][/color]";

        if (info.Cooldown != TimeSpan.Zero)
            StatusLabel.Text = $@"{StatusLabel.Text} [color={StyleFortress.LightBad.ToHex()}]\[Cooldown][/color]";

        if (info.Penalty != 0)
            StatusLabel.Text = $@"{StatusLabel.Text} [color={StyleFortress.LightBad.ToHex()}]\[Penalty][/color]";

        StatusLabel.Text = $"[bold]{StatusLabel.Text}[/bold]";

        if (!_proto.Resolve(info.Id, out var proto))
            return;

        Title.Text = $"[bold][color={proto.Color.ToHex()}]{info.Id}[/color] ({info.Result:F2})[/bold]";

        // Common
        AddLabel(CommonTab, "Name:", Loc.GetString(proto.Name));
        AddLabel(CommonTab, "Fail Policy:", $"{proto.FailPolicy}");

        if (proto.FailPolicy == UtilityAiFailPolicy.Penalty)
            AddLabel(CommonTab, "Fail Penalty:", $"{proto.FailPenalty}");

        if (proto.Fallbacks.Count > 0)
            AddLabel(CommonTab, "Fallbacks:", string.Join(',', proto.Fallbacks));

        if (info.Cooldown > TimeSpan.Zero)
            AddLabel(CommonTab, "Cooldown:", $"{(info.Cooldown - _timing.CurTime).Seconds}s");

        AddTypes(CommonTab, "Goal State", info.GoalState.State);

        // Curves
        if (info.Penalty > 0)
            AddLabel(CurvesTab, "Total Penalty:", $"{info.Penalty:F3}");

        AddLabel(CurvesTab, "Modified Score:", $"{info.Modified:F3}");
        AddLabel(CurvesTab, "Total Score:", $"{info.Result:F3}");

        foreach (var curve in info.Curves)
        {
            var box = AddBox(CurvesTab, curve.Type, $"{curve.Output:F3}");
            AddTypes(box.Content, "Fields", curve.Reflection);
            AddLabel(box.Content, "Input:", $"{curve.Input:F3}");
        }

        // Conditions
        foreach (var condition in info.Preconditions)
        {
            var box = AddBox(
                ConditionsTab,
                condition.Type,
                condition.Result
                    ? $"[color={StyleFortress.LightGood.ToHex()}]True[/color]"
                    : $"[color={StyleFortress.LightBad.ToHex()}]False[/color]");
            AddTypes(box.Content, "Fields", condition.Reflection);
            AddTypes(box.Content, "State Snapshot", condition.Dump.StateSnapshot.State);
            AddLogs(box.Content, condition.Dump.Dump);
        }

        return;

        void AddTypes(Control parent, string title, Dictionary<string, (string, string)>? data)
        {
            if (data == null || data.Count == 0)
                return;

            AddSeparator(parent);
            var expandBox = new ExpandableBox { Title = $"[bold]{title}[/bold]" };
            parent.AddChild(expandBox);

            foreach (var (key, (type, value)) in data)
            {
                AddSeparator(expandBox.Content);
                expandBox.Content.AddChild(new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(0f, 1f),
                    MaxWidth = 300,
                    Children =
                    {
                        new BoxContainer
                        {
                            Children =
                            {
                                new RichTextLabel { Text = $"[bold]{key}[/bold]" },
                                new Control { HorizontalExpand = true },
                                new RichTextLabel { Text = $":{type}" },
                            },
                        },
                        new BoxContainer
                        {
                            Children =
                            {
                                new RichTextLabel { Text = value },
                            },
                        },
                    },
                });
            }
        }

        void AddLabel(Control parent, string left, string right)
        {
            AddSeparator(parent);
            parent.AddChild(new BoxContainer
            {
                Margin = new Thickness(20f, 0f, 5f, 0f),
                Children =
                {
                    new RichTextLabel { Text = $"[bold]{left}[/bold]" },
                    new Control { HorizontalExpand = true },
                    new RichTextLabel { Text = $"[bold]{right}[/bold]" },
                },
            });
        }

        void AddSeparator(Control parent)
        {
            parent.AddChild(new PanelContainer
            {
                StyleClasses = { StyleFortress.StyleClassLowDividerDark },
                Margin = new Thickness(3f, 2f),
            });
        }

        void AddLogs(Control parent, string? logs)
        {
            if (string.IsNullOrWhiteSpace(logs))
                return;

            AddSeparator(parent);
            var box = new ExpandableBox { Title = "[bold]Logs[/bold]" };
            parent.AddChild(box);
            var dumps = logs.Split('\n', StringSplitOptions.RemoveEmptyEntries);

            foreach (var dump in dumps)
            {
                box.Content.AddChild(new RichTextLabel
                {
                    Text = dump,
                    MaxWidth = 300,
                });
            }
        }

        ExpandableBox AddBox(Control parent, string title, string? second = null)
        {
            AddSeparator(parent);
            var box = new ExpandableBox
            {
                Title = $"[bold]{title}[/bold]",
                SecondaryText = second != null ? $"[bold]{second}[/bold]" : null,
            };
            parent.AddChild(box);
            return box;
        }
    }
}

