using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.TreeMenu;

[GenerateTypedNameReferences]
public sealed partial class TreeMenuPanel : Control
{
    [Dependency] private readonly IInputManager _input = default!;

    public bool Closable { get; set; } = true;
    public TreeMenuButton? ParentButton { get; internal set; }
    public TreeMenuPanel? ParentPanel { get; internal set; }

    public BoxContainer.LayoutOrientation Orientation
    {
        get => Content.Orientation;
        set
        {
            Container.Orientation = value.Opposite();
            Content.Orientation = value;
        }
    }

    public TreeMenuPanel()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        XamlChildren = Content.Children;
    }

    /// <summary>
    /// Deletes all the contents of this panel
    /// </summary>
    public void Clear()
    {
        Content.RemoveAllChildren();
    }

    /// <summary>
    /// Hides this panel and all child panels
    /// </summary>
    public void Collapse()
    {
        if (!Closable || !Visible)
            return;

        Visible = false;

        foreach (var child in Content.Children)
        {
            if (child is TreeMenuButton button)
                button.Content.Collapse();
        }
    }

    /// <summary>
    /// Perform a visibility check for this panel and all child panels
    /// </summary>
    public void ValidateVisibility()
    {
        if (UserInterfaceManager.MouseGetControl(_input.MouseScreenPosition) is TreeMenuButton hovered
            && ParentPanel?.Content.Children.Contains(hovered) == true
            && ParentButton != hovered)
            Collapse();

        var point = (Vector2i) _input.MouseScreenPosition.Position;
        var canCollapse = true;

        foreach (var child in Content.Children)
        {
            if (child is not TreeMenuButton button)
                continue;

            if (button == ParentButton && button.GlobalPixelRect.Contains(point))
                continue;

            if (button.Content.Content.ChildCount <= 0
                || !button.Content.Visible)
                continue;

            button.Content.ValidateVisibility();

            if (button.Content.Visible)
                canCollapse = false;
        }

        if (!canCollapse
            || ParentPanel?.GlobalPixelRect.Contains(point) == true
            || GlobalPixelRect.Contains(point))
            return;

        Collapse();
    }
}

