using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.TreeMenu;

[GenerateTypedNameReferences]
public sealed partial class TreeMenuButton : IconButton
{
    public const string StyleClassTreeMenuButton = "TreeMenuButton";
    public const string StylePropertyMarkerTexture = "marker-texture";
    public const string StylePropertyMarkerColor = "marker-color";

    private Texture _markerTexture = Texture.Transparent;
    private Color _markerColor;

    public TreeMenuButton()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = Content.Content.Children;
        Content.ParentButton = this;
    }

    /// <summary>
    /// Deletes all the content of the panel connected to this button
    /// </summary>
    public void ClearContent()
    {
        Content.Clear();
    }

    /// <summary>
    /// Adds content to the panel connected to this button
    /// </summary>
    public void AddContent(Control control)
    {
        Content.Content.AddChild(control);
    }

    protected override void StylePropertiesChanged()
    {
        if (TryGetStyleProperty<Texture>(StylePropertyMarkerTexture, out var texture))
            _markerTexture = texture;

        TryGetStyleProperty(StylePropertyMarkerColor, out _markerColor);

        base.StylePropertiesChanged();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (Content.Content.ChildCount == 0)
            return;

        var mod = handle.Modulate;
        handle.Modulate = Color.White;
        handle.DrawTextureRect(_markerTexture, PixelSizeBox, _markerColor);
        handle.Modulate = mod;
    }
}

