using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.TreeMenu;

/// <summary>
/// Separator between the tree menu panels.
/// It exists only to simplify the logic of opening/closing panels
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TreeMenuSeparator : BoxContainer
{
    public TreeMenuSeparator()
    {
        RobustXamlLoader.Load(this);
    }
}
