using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.TreeMenu;

[GenerateTypedNameReferences]
public sealed partial class TreeMenu : Control
{
    public BoxContainer.LayoutOrientation Orientation { get; set; }

    public TreeMenu()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = RootPanel.XamlChildren;

        PanelContainer.Orientation = Orientation;
        RootPanel.Orientation = Orientation.Opposite();

        RootPanel.Content.OnChildAdded += control =>
        {
            if (control is TreeMenuButton button)
                BuildTree(button, RootPanel);
        };

        OnMouseExited += _ => RootPanel.ValidateVisibility();
    }

    private void BuildTree(TreeMenuButton button, TreeMenuPanel parent)
    {
        button.Content.Orientation = Orientation.Opposite();
        button.Content.ParentPanel = parent;

        // bruuuh
        button.RemoveChild(button.Content);
        PanelContainer.AddChild(button.Content);

        button.OnMouseEntered += _ =>
        {
            button.Content.Visible = button.Content.Content.ChildCount > 0;
            RootPanel.ValidateVisibility();
        };
        button.OnMouseExited += _ => RootPanel.ValidateVisibility();

        foreach (var child in button.Content.Content.Children)
        {
            if (child is TreeMenuButton buttonChild)
                BuildTree(buttonChild, button.Content);
        }
    }
}

public static class LayoutOrientationExtensions
{
    public static BoxContainer.LayoutOrientation Opposite(this BoxContainer.LayoutOrientation orientation)
    {
        return orientation == BoxContainer.LayoutOrientation.Horizontal
            ? BoxContainer.LayoutOrientation.Vertical
            : BoxContainer.LayoutOrientation.Horizontal;
    }
}
