using Content.Client._RF.NPC.UI;
using Content.Shared._RF.NPC;
using Content.Shared._RF.NPC.Search;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.Search.UI;

[GenerateTypedNameReferences]
public sealed partial class SearcherDebugTab : AiDevWindowTab
{
    private readonly Dictionary<int, Control> _nodeControls = new();

    protected override Control LayoutRoot => GraphRoot;

    public SearcherDebugTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(NpcSearchGraph graph)
    {
        _nodeControls.Clear();

        NodesLayer.RemoveAllChildren();
        Layout = GraphLayoutBuilder.Build(graph, NodeSize);

        foreach (var node in graph.Nodes)
        {
            var control = new SearchQueryControl(node);
            NodesLayer.AddChild(control);
            _nodeControls[node.Id] = control;
        }

        UpdateLayout();
    }

    protected override void OnUpdateLayout(GraphLayout layout)
    {
        foreach (var (id, control) in _nodeControls)
        {
            if (!layout.Nodes.TryGetValue(id, out var placement))
                continue;

            LayoutContainer.SetPosition(control, placement.Position);
            control.SetSize = placement.Size;
        }
    }
}

