using Content.Client._RF.NPC.UI;
using Content.Shared._RF.NPC;
using Content.Shared._RF.NPC.Search;
using Content.Shared.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.NPC.Search.UI;

[GenerateTypedNameReferences]
public sealed partial class SearcherDebugTab : AiDevWindowTab
{
    public SearcherDebugTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(NpcSearchGraph graph)
    {
        NodeControls.Clear();

        GraphRoot.RemoveAllChildren();
        Layout = GraphLayoutBuilder.Build(graph, NodeSize);

        foreach (var node in graph.Nodes)
        {
            var control = new SearchQueryControl(node);
            control.OnKeyBindUp += args =>
            {
                if (args.Function == ContentKeyFunctions.MouseMiddle)
                    ToggleExpanded(node.Id);
            };

            GraphRoot.AddChild(control);
            NodeControls[node.Id] = control;
        }

        UpdateLayout();
    }
}

