using System.Linq;
using Content.Client._RF.NPC;
using Content.Shared._RF.World;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.GameplayState.Controls;

[GenerateTypedNameReferences]
public sealed partial class PopList : UIWidget
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly Dictionary<EntityUid, PopIcon> _icons = new();

    public PopList()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void AddPop(EntityUid uid)
    {
        if (_icons.ContainsKey(uid)
            || !_entityManager.EntityExists(uid))
            return;

        _entityManager.TryGetComponent(uid, out MetaDataComponent? meta);

        var icon = new PopIcon(uid, meta?.EntityName.Split(" ").First());
        _icons.Add(uid, icon);
        Icons.AddChild(icon);
    }

    public void Update()
    {
        var control = _entityManager.System<NpcControlSystem>();
        foreach (var (uid, icon) in _icons)
        {
            icon.Pressed = control.Selected.Contains(uid);
            icon.SetMarkerColor(control.Tasks.TryGetValue(uid, out var task) ? task.Color : Color.Transparent);
        }

        if (!_entityManager.TryGetComponent(_player.LocalEntity, out RimFortressPlayerComponent? player))
            return;

        foreach (var pop in player.Pops)
        {
            AddPop(pop);
        }
    }
}

