using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class DamageGroupInfo : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceCache _cache = default!;

    /// <summary>
    /// Path to RSI with icons of all damage types
    /// </summary>
    public string IconsRsiPath { get; set; } = "/Textures/Objects/Devices/health_analyzer.rsi";

    public DamageGroupInfo(
        ProtoId<DamageGroupPrototype> groupId,
        FixedPoint2 groupDamage,
        IReadOnlyDictionary<string, FixedPoint2> damageDict)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var group = _prototype.Index(groupId);

        var rsiPath = new ResPath(IconsRsiPath);
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, groupId.Id.ToLower());
        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;

        if (!rsi.TryGetState(rsiSprite.RsiState, out _))
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");

        Icon.Texture = _entity.System<SpriteSystem>().Frame0(rsiSprite);
        Title.Text = $"{group.LocalizedName}: {groupDamage}";

        foreach (var type in group.DamageTypes)
        {
            if (!damageDict.TryGetValue(type, out var amount) || amount <= 0)
                continue;

            DamageTypes.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-info-tab-damage-type",
                    ("type", _prototype.Index<DamageTypePrototype>(type).LocalizedName),
                    ("amount", amount)),
            });
        }
    }
}
