using System.Linq;
using System.Numerics;
using Content.Client.Cuffs;
using Content.Client.Examine;
using Content.Client.Hands.Systems;
using Content.Client.Inventory;
using Content.Client.Strip;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Hands.Controls;
using Content.Client.Verbs.UI;
using Content.Shared.Cuffs;
using Content.Shared.Cuffs.Components;
using Content.Shared.Hands.Components;
using Content.Shared.Input;
using Content.Shared.Inventory;
using Content.Shared.Inventory.VirtualItem;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class InventoryInfoTab : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private ClientInventorySystem _inventory = default!;
    private SharedCuffableSystem _cuffable = default!;
    private StrippableSystem _strippable = default!;
    private ExamineSystem _examine = default!;
    private HandsSystem _hands = default!;

    private readonly EntityUid _virtualHiddenEntity;

    private EntityUid? _uid;
    private bool _setup;
    private Vector2 _maxSlotPos;

    public const string HiddenPocketEntityId = "StrippingHiddenEntity";

    public int ButtonSeparation { get; set; } = 4;

    public InventoryInfoTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _virtualHiddenEntity = _entity.SpawnEntity(HiddenPocketEntityId, MapCoordinates.Nullspace);
    }

    private void UpdateInfo()
    {
        if (_uid != null)
            UpdateInfo(_uid.Value);
    }

    /*
     * All the code below is taken from StrippableBoundUserInterface,
     * with slight modifications as it only works with StrippingMenu,
     * which is a window, and I need to insert the inventory as part of the interface
     */
    public void UpdateInfo(EntityUid uid)
    {
        EnsureSetup();
        ClearButtons();

        _uid = uid;

        if (_entity.TryGetComponent<InventoryComponent>(uid, out var inv))
        {
            foreach (var slot in inv.Slots)
            {
                AddInventoryButton(uid, slot.Name, inv);
            }
        }

        if (_entity.TryGetComponent<HandsComponent>(uid, out var handsComp) && handsComp.CanBeStripped)
        {
            var ent = new Entity<HandsComponent>(uid, handsComp);

            // good ol hands shit code. there is a GuiHands comparer that does the same thing... but these are hands
            // and not gui hands... which are different...
            foreach (var (id, hand) in handsComp.Hands)
            {
                if (hand.Location != HandLocation.Right)
                    continue;

                AddHandButton(ent, id, hand);
            }

            foreach (var (id, hand) in handsComp.Hands)
            {
                if (hand.Location != HandLocation.Middle)
                    continue;

                AddHandButton(ent, id, hand);
            }

            foreach (var (id, hand) in handsComp.Hands)
            {
                if (hand.Location != HandLocation.Left)
                    continue;

                AddHandButton(ent, id, hand);
            }
        }
    }

    private void EnsureSetup()
    {
        if (_setup)
            return;

        _inventory = _entity.System<ClientInventorySystem>();
        _strippable = _entity.System<StrippableSystem>();
        _cuffable = _entity.System<CuffableSystem>();
        _examine = _entity.System<ExamineSystem>();
        _hands = _entity.System<HandsSystem>();

        _strippable.OnUiNeedsUpdate += UpdateInfo;

        _setup = true;
    }

    private void ClearButtons()
    {
        InventoryContainer.RemoveAllChildren();
        HandsContainer.RemoveAllChildren();
    }

    private void AddInventoryButton(EntityUid invUid, string slotId, InventoryComponent inv)
    {
        if (!_inventory.TryGetSlotContainer(invUid, slotId, out var container, out var slotDef, inv))
            return;

        var entity = container.ContainedEntity;

        // If this is a full pocket, obscure the real entity
        // this does not work for modified clients because they are still sent the real entity
        if (entity != null && _strippable.IsStripHidden(slotDef, _player.LocalEntity))
            entity = _virtualHiddenEntity;

        var button = new SlotButton(new ClientInventorySystem.SlotData(slotDef, container));
        button.Pressed += SlotPressed;

        InventoryContainer.AddChild(button);

        UpdateEntityIcon(button, entity);

        LayoutContainer.SetPosition(button, slotDef.StrippingWindowPos * (SlotControl.DefaultButtonSize + ButtonSeparation));

        if (slotDef.StrippingWindowPos.X > _maxSlotPos.X)
            _maxSlotPos.X = slotDef.StrippingWindowPos.X;
        if (slotDef.StrippingWindowPos.Y > _maxSlotPos.Y)
            _maxSlotPos.Y = slotDef.StrippingWindowPos.Y;

        UpdateLayoutSize();
    }

    private void AddHandButton(Entity<HandsComponent> ent, string handId, Hand hand)
    {
        var button = new HandButton(handId, hand.Location);

        button.Pressed += SlotPressed;

        var heldEntity = _hands.GetHeldItem(ent.AsNullable(), handId);
        if (_entity.TryGetComponent<VirtualItemComponent>(heldEntity, out var virt))
        {
            button.Blocked = true;
            if (_entity.TryGetComponent<CuffableComponent>(_uid, out var cuff) && _cuffable.GetAllCuffs(cuff).Contains(virt.BlockingEntity))
                button.BlockedRect.MouseFilter = MouseFilterMode.Ignore;
        }

        UpdateEntityIcon(button, heldEntity);
        HandsContainer.AddChild(button);
    }

    private void SlotPressed(GUIBoundKeyEventArgs ev, SlotControl slot)
    {
        if (slot.Entity == null)
            return;

        if (ev.Function == ContentKeyFunctions.ExamineEntity)
        {
            _examine.DoExamine(slot.Entity.Value);
            ev.Handle();
        }
        else if (ev.Function == EngineKeyFunctions.UseSecondary)
        {
            UserInterfaceManager.GetUIController<VerbMenuUIController>().OpenVerbMenu(slot.Entity.Value);
            ev.Handle();
        }
    }

    private void UpdateEntityIcon(SlotControl button, EntityUid? entity)
    {
        // Hovering, highlighting & storage are features of general hands & inv GUIs. This UI just re-uses these because I'm lazy.
        button.ClearHover();
        button.StorageButton.Visible = false;

        if (entity == null)
        {
            button.SetEntity(null);
            return;
        }

        EntityUid? viewEnt;
        if (_entity.TryGetComponent<VirtualItemComponent>(entity, out var virt))
            viewEnt = _entity.HasComponent<SpriteComponent>(virt.BlockingEntity) ? virt.BlockingEntity : null;
        else if (_entity.HasComponent<SpriteComponent>(entity))
            viewEnt = entity;
        else
            return;

        button.SetEntity(viewEnt);
    }

    private void UpdateLayoutSize()
    {
        InventoryContainer.SetSize = new(
            (_maxSlotPos.X + 1) * (SlotControl.DefaultButtonSize + ButtonSeparation),
            (_maxSlotPos.Y + 1) * (SlotControl.DefaultButtonSize + ButtonSeparation));
    }
}

