using Content.Shared._RF.NPC.Components;
using Content.Shared._RF.NPC.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class JobInfo : Control
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;

    public JobInfo(EntityUid uid, NpcJob data)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var npcJobs = _entity.System<NpcJobsSystem>();

        if (!_entity.TryGetComponent(_player.LocalEntity, out NpcJobsComponent? comp))
            return;

        if (data.Icon != null)
            Icon.Texture = _entity.System<SpriteSystem>().Frame0(data.Icon);

        Label.Text = $"{data.Name}";

        Priority.MaxValue = comp.MaxPriority;
        Priority.Priority = npcJobs.GetPriority(uid, data.Id);
        Priority.OnPriorityChanged += value =>
            npcJobs.SetJobPriority(uid, data.Id, value);
    }
}

