using Content.Client._RF.NPC;
using Content.Shared._RF.NPC;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class JobInfo : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public JobInfo(EntityUid uid, NpcJobData data)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var routineNpc = _entity.System<RoutineNpcTasksSystem>();

        if (data.IconPath != null)
            Icon.TexturePath = data.IconPath;

        Label.Text = $"{data.Name}";

        Priority.MaxValue = routineNpc.GetMaxPriority(uid);
        Priority.Priority = routineNpc.GetPriority(uid, data.Id);
        Priority.OnPriorityChanged += value =>
            routineNpc.ChangeJobPriority(uid, data.Id, value);
    }
}

