using System.Linq;
using Content.Client._RF.UserInterface.Controllers;
using Content.Shared._RF.NPC.Components;
using Content.Shared._RF.NPC.Systems;
using Content.Shared._RF.NPC.UtilityAi.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class JobsInfoTab : Control, IInfoTab
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private UtilityAiSystem _utilityAi = default!;
    private NpcJobsSystem _npcJobs = default!;

    private EntityUid? _uid;
    private bool _setup;

    public JobsInfoTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        JobsSettingsButton.OnPressed += _ => UserInterfaceManager
            .GetUIController<NpcJobsUiController>()
            .ToggleSettingsWindow();
    }

    private void EnsureSetup()
    {
        if (_setup)
            return;

        _utilityAi = _entity.System<UtilityAiSystem>();
        _npcJobs = _entity.System<NpcJobsSystem>();

        _npcJobs.OnJobChanged += _ =>
        {
            if (VisibleInTree && _uid != null)
                UpdateInfo(_uid.Value);
        };

        _setup = true;
    }

    public void UpdateInfo(EntityUid uid)
    {
        EnsureSetup();
        Container.RemoveAllChildren();

        _uid = uid;

        UpdateCurrentTask();

        if (!_entity.TryGetComponent(_player.LocalEntity, out NpcJobsComponent? comp))
            return;

        foreach (var job in comp.Jobs.OrderBy(x => x.Name))
        {
            Container.AddChild(new JobInfo(uid, job));
        }
    }

    private void UpdateCurrentTask()
    {
        if (_uid == null)
            return;

        var taskName = _utilityAi.TryGetCurrentGoal(_uid.Value, out var id) && _proto.TryIndex(id, out var task)
            ? $"[color={task.Color.ToHex()}][bold]{Loc.GetString(task.Name)}[/bold][/color]"
            : Loc.GetString("job-info-tab-task-none");

        CurrentTask.Text = $"{Loc.GetString("job-info-tab-current-task")}: {taskName}";
    }
}

