using System.Linq;
using Content.Client._RF.NPC;
using Content.Client._RF.UserInterface.Controllers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class JobsInfoTab : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private NpcControlSystem _control = default!;
    private RoutineNpcTasksSystem _routine = default!;

    private EntityUid? _uid;
    private bool _setup;

    public JobsInfoTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        JobsSettingsButton.OnPressed += _ => UserInterfaceManager
            .GetUIController<NpcJobsUiController>()
            .ToggleSettingsWindow();
    }

    private void EnsureSetup()
    {
        if (_setup)
            return;

        _control = _entity.System<NpcControlSystem>();
        _routine = _entity.System<RoutineNpcTasksSystem>();

        _control.OnTaskUpdated += uid =>
        {
            if (VisibleInTree && _uid == uid)
                UpdateCurrentTask();
        };

        _routine.OnJobChanged += _ =>
        {
            if (VisibleInTree && _uid != null)
                UpdateInfo(_uid.Value);
        };

        _setup = true;
    }

    public void UpdateInfo(EntityUid uid)
    {
        EnsureSetup();
        Container.RemoveAllChildren();

        _uid = uid;

        UpdateCurrentTask();

        foreach (var (_, data) in _routine.JobsData.OrderBy(x => x.Value.Name))
        {
            Container.AddChild(new JobInfo(uid, data));
        }
    }

    private void UpdateCurrentTask()
    {
        if (_uid == null)
            return;

        var taskName = _control.Tasks.TryGetValue(_uid.Value, out var task)
            ? $"[color={task.Color.ToHex()}][bold]{task.TaskName}[/bold][/color]"
            : Loc.GetString("job-info-tab-task-none");

        CurrentTask.Text = $"{Loc.GetString("job-info-tab-current-task")}: {taskName}";
    }
}

