using Content.Client._RF.Stylesheets;
using Content.Shared._RF.Socialization;
using Content.Shared._RF.Socialization.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class MoodInfoTab : Control, IInfoTab
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private SocializationSystem _socialization = default!;

    private EntityUid? _uid;
    private TimeSpan _nextUpdate;
    private bool _setup;

    /// <summary>
    /// How often the information will be updated
    /// </summary>
    private static readonly TimeSpan UpdateRate = TimeSpan.FromSeconds(1);

    public MoodInfoTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    private void EnsureSetup()
    {
        if (_setup)
            return;

        _setup = true;
        _socialization = _entity.System<SocializationSystem>();
    }

    public void UpdateInfo(EntityUid uid)
    {
        EnsureSetup();
        _uid = uid;

        var mood = _socialization.GetMood(uid);
        var color = mood switch
        {
            < 0 => StyleFortress.LightBad,
            > 0 => StyleFortress.Good,
            _ => StyleFortress.GraySilver,
        };

        Total.Text = Loc.GetString("mood-info-total", ("color", color), ("mood", mood));

        if (_entity.TryGetComponent(uid, out SocializationComponent? comp))
            Container.UpdateInfo(uid, comp.MoodEffects);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!VisibleInTree || _nextUpdate > _timing.CurTime || _uid == null)
            return;

        UpdateInfo(_uid.Value);
        _nextUpdate = _timing.CurTime + UpdateRate;
    }
}

