using System.Linq;
using Content.Shared._RF.Social.Components;
using Content.Shared._RF.Social.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class OpinionInfoTab : Control, IInfoTab
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private SocialSystem _social = default!;

    private EntityUid? _uid;
    private TimeSpan _nextUpdate;
    private bool _setup;

    /// <summary>
    /// How often the information will be updated
    /// </summary>
    private static readonly TimeSpan UpdateRate = TimeSpan.FromSeconds(1);

    private readonly Dictionary<EntityUid, OpinionInfoButton> _buttons = new();

    public OpinionInfoTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    private void EnsureSetup()
    {
        if (_setup)
            return;

        _setup = true;
        _social = _entity.System<SocialSystem>();
    }

    public void UpdateInfo(EntityUid uid)
    {
        EnsureSetup();

        if (_uid != uid)
        {
            _buttons.Clear();
            Container.RemoveAllChildren();
        }

        _uid = uid;

        var updated = false;
        var query = _entity.EntityQueryEnumerator<SocialComponent>();

        while (query.MoveNext(out var targetUid, out _))
        {
            if (targetUid == uid)
                continue;

            var effects = _social.GetOpinionEffects(uid, targetUid);

            if (_buttons.TryGetValue(targetUid, out var button))
            {
                if (button.Effects == effects)
                    continue;

                button.UpdateInfo(uid, targetUid, effects);
            }
            else
            {
                button = new OpinionInfoButton();
                button.UpdateInfo(uid, targetUid, effects);
                _buttons[targetUid] = button;

                Container.AddChild(button);
            }

            updated = true;
        }

        if (updated)
            SortButtons();
    }

    private void SortButtons()
    {
        var sortedChildren = Container.Children
            .Where(c => c is OpinionInfoButton)
            .Cast<OpinionInfoButton>()
            .OrderByDescending(x =>  x.Value)
            .ToList();

        for (var i = 0; i < sortedChildren.Count; i++)
        {
            var child = sortedChildren[i];

            if (child.GetPositionInParent() != i)
                child.SetPositionInParent(i);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!VisibleInTree || _nextUpdate > _timing.CurTime || _uid == null)
            return;

        UpdateInfo(_uid.Value);
        _nextUpdate = _timing.CurTime + UpdateRate;
    }
}

