using Content.Client._RF.Stylesheets;
using Content.Shared._RF.Social;
using Content.Shared._RF.Social.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class OpinionInfoButton : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public int Value { get; private set; }
    public Dictionary<ProtoId<SocialEffectPrototype>, TimeSpan?> Effects { get; private set; } = new();

    public OpinionInfoButton()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Button.OnToggled += _ =>
        {
            if (Effects.Count > 0)
                EffectsPanel.Visible = Button.Pressed;
        };
    }

    public void UpdateInfo(
        EntityUid uid,
        EntityUid targetUid,
        Dictionary<ProtoId<SocialEffectPrototype>, TimeSpan?> effects)
    {
        Effects = effects;
        Value = _entity
            .System<SocialSystem>()
            .GetOpinion(uid, targetUid);

        Button.ToggleMode = Effects.Count > 0;

        var name = _entity.GetComponent<MetaDataComponent>(targetUid).EntityName;

        var color = Value switch
        {
            < 0 => StyleFortress.LightBad,
            > 0 => StyleFortress.Good,
            _ => StyleFortress.GraySilver,
        };

        var sign = Value switch
        {
            > 0 => "+",
            < 0 => "–",
            _ => "",
        };

        Sprite.SetEntity(targetUid);
        Label.Text = $"[bold]{name}[/bold]";
        ValueLabel.Text = $"[bold][color={color.ToHex()}]{sign}{Math.Abs(Value)}[/color][/bold]";
        EffectsContainer.UpdateInfo(effects);
    }
}

