using Content.Client._RF.Skills;
using Content.Client.UserInterface.Controls;
using Content.Shared.Follower;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class PopInfoWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IEntityNetworkManager _net = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private EntityUid? _uid;

    public PopInfoWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        foreach (var child in TabContainer.Children)
        {
            if (child.Name == null)
                continue;

            TabContainer.SetTabTitle(
                child.GetPositionInParent(),
                Loc.GetString($"pop-info-{child.Name.ToLower()}-tab-title"));
        }

        TabContainer.OnTabChanged += OnTabChanged;

        FollowButton.OnPressed += _ =>
        {
            if (_entity.GetNetEntity(_uid) is { } uid)
                _net.SendSystemNetworkMessage(new FollowEntityRequest(uid));
        };
    }

    public void SetInfo(EntityUid uid)
    {
        if (!_entity.TryGetComponent(uid, out MetaDataComponent? meta)
            || !_entity.TryGetComponent(uid, out HumanoidProfileComponent? appearance))
            return;

        _uid = uid;
        var sex = appearance.Sex;

        NameLabel.Text = Loc.GetString("pop-info-summary",
            ("name", meta.EntityName),
            ("species", Loc.GetString(_prototype.Index(appearance.Species).Name)),
            ("sex", sex.ToString().ToLowerInvariant()),
            ("age", appearance.Age),
            ("profession", _entity.System<SkillsSystem>().SkillProfession(uid)));

        Sprite.SetEntity(uid);
        OnTabChanged(TabContainer.CurrentTab);
    }

    private void OnTabChanged(int index)
    {
        if (_uid != null && TabContainer.GetChild(index) is IInfoTab tab)
            tab.UpdateInfo(_uid.Value);
    }
}

public interface IInfoTab
{
    void UpdateInfo(EntityUid uid);
}
