using Content.Client._RF.Skills;
using Content.Client.UserInterface.Controls;
using Content.Shared.Follower;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class PopInfoWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IEntityNetworkManager _net = default!;

    private EntityUid? _uid;

    public PopInfoWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(Skills.GetPositionInParent(), Loc.GetString("pop-info-skills-tab-title"));
        TabContainer.OnTabChanged += OnTabChanged;

        FollowButton.OnPressed += _ =>
        {
            if (_entity.GetNetEntity(_uid) is { } uid)
                _net.SendSystemNetworkMessage(new FollowEntityRequest(uid));
        };
    }

    public void SetInfo(EntityUid uid)
    {
        if (!_entity.TryGetComponent(uid, out MetaDataComponent? meta)
            || !_entity.TryGetComponent(uid, out HumanoidAppearanceComponent? appearance))
            return;

        _uid = uid;

        NameLabel.Text = Loc.GetString("pop-info-summary",
            ("name", meta.EntityName),
            ("sex", appearance.Sex.ToString().ToLowerInvariant()),
            ("age", appearance.Age),
            ("profession", _entity.System<SkillsSystem>().SkillProfession(uid)));

        Sprite.SetEntity(uid);
        OnTabChanged(TabContainer.CurrentTab);
    }

    private void OnTabChanged(int index)
    {
        if (_uid == null)
            return;

        if (index == Skills.GetPositionInParent())
            Skills.UpdateInfo(_uid.Value);
    }
}

