using Content.Shared._RF.Skills.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class SkillsInfoTab : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public SkillsInfoTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateInfo(EntityUid uid)
    {
        Container.RemoveAllChildren();

        if (!_entity.TryGetComponent(uid, out SkillsComponent? skills))
            return;

        foreach (var data in skills.Skills)
        {
            var info = new SkillInfo(uid, data.Id);
            Container.AddChild(info);
        }
    }
}

