using Content.Client._RF.Stylesheets;
using Content.Client._RF.World;
using Content.Shared._RF.Social;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RF.Info.Controls;

[GenerateTypedNameReferences]
public sealed partial class SocializationEffectInfo : ContainerButton
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityManager _entity = default!;

    public const string OddRowStyleClass = "odd-row";
    public const string EvenRowStyleClass = "even-row";

    public ProtoId<SocialEffectPrototype> Proto { get; private set; }
    public int Value { get; private set; }
    public TimeSpan? EndAt { get; private set; }

    public SocializationEffectInfo()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateInfo(SocialEffectPrototype proto, int value, TimeSpan? endAt)
    {
        Proto = proto;
        Value = value;
        EndAt = endAt;

        ToolTip = proto.Description != null ? Loc.GetString(proto.Description) : null;

        var color = value switch
        {
            < 0 => StyleFortress.LightBad,
            > 0 => StyleFortress.Good,
            _ => StyleFortress.GraySilver,
        };

        var sign = Value switch
        {
            > 0 => "+",
            < 0 => "–",
            _ => "",
        };

        ValueLabel.Text = $"[bold][color={color.ToHex()}]{sign}{Math.Abs(value)}[/color][/bold]";
        Label.Text = Loc.GetString(proto.Name);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        TimeSpan? duration = null;

        if (EndAt != null)
            duration = _entity.System<RimFortressWorldSystem>().ToWorldTime(EndAt.Value - _timing.CurTime);

        if (duration == null)
        {
            EndAtLabel.Text = Loc.GetString("effect-never-end");
            return;
        }

        var days = (int) Math.Ceiling(duration.Value.TotalDays);
        var hours = (int) Math.Ceiling(duration.Value.TotalHours);
        var minutes = (int) duration.Value.TotalMinutes;

        if (days > 0)
            EndAtLabel.Text = Loc.GetString("effect-end-format-days", ("time", days));
        else if (hours > 0)
            EndAtLabel.Text = Loc.GetString("effect-end-format-hours", ("time", hours));
        else
            EndAtLabel.Text = Loc.GetString("effect-end-format-minutes", ("time", minutes));

        if (days > 0)
        {
            EndAtLabel.ToolTip = $"{Loc.GetString("effect-end-format-days", ("time", days))}" +
                                 $", {duration.Value.Hours:00}:{duration.Value.Minutes:00}:{duration.Value.Seconds:00}";
        }
        else
            EndAtLabel.ToolTip = $"{duration.Value.Hours:00}:{duration.Value.Minutes:00}:{duration.Value.Seconds:00}";
    }
}
