using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.Chat;

[GenerateTypedNameReferences]
public sealed partial class ChatMessagesBubble : PanelContainer
{
    public const string StyleClassChatMessagesBubble = "ChatMessagesBubble";

    private int _count;

    public int Count
    {
        get => _count;
        set
        {
            _count = value;
            Label.Text = value.ToString();

            Visible = value > 0;
        }
    }

    public ChatMessagesBubble()
    {
        RobustXamlLoader.Load(this);
    }
}

