using Content.Client.Resources;
using Content.Client.UserInterface.Systems.Chat;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.Chat;

[GenerateTypedNameReferences]
public sealed partial class FoldableChatBox : ChatBox
{
    [Dependency] private readonly IResourceCache _cache = default!;

    public FoldableChatBox()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var openTexture = _cache.GetTexture("/Textures/_RF/Interface/chevron-down-solid-full.svg.192dpi.png");
        var foldedTexture = _cache.GetTexture("/Textures/_RF/Interface/chevron-left-solid-full.svg.192dpi.png");

        ChatWindowPanel.Parent?.RemoveChild(ChatWindowPanel);
        Container.AddChild(ChatWindowPanel);

        ChatWindowPanel.Visible = false;

        ToggleButton.OnPressed += _ =>
        {
            ChatWindowPanel.Visible = !ChatWindowPanel.Visible;
            ToggleButton.Texture = ChatWindowPanel.Visible ? openTexture : foldedTexture;

            if (ChatWindowPanel.Visible)
                Bubble.Count = 0;
        };

        UserInterfaceManager.GetUIController<ChatUIController>().MessageAdded += _ =>
        {
            if (!ChatWindowPanel.Visible)
                Bubble.Count++;
        };
    }
}

