using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.Table;

[Virtual]
[GenerateTypedNameReferences]
public sealed partial class TableControl : Control
{
    private readonly List<TableRow> _rows = new();
    private float[] _colWidths = [];
    private float[] _rowHeights = [];
    private bool _layoutDirty;

    public int Rows => _rows.Count;
    public int Columns => _rows.Count == 0 ? 0 : _rows[0].Columns;

    public TableControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void ClearAll()
    {
        _rows.Clear();
        HeaderContainer.RemoveAllChildren();
        RowsContainer.RemoveAllChildren();
    }

    public void MarkLayoutDirty()
    {
        _layoutDirty = true;
        InvalidateMeasure();
        InvalidateArrange();
    }

    public TableRow CreateRow(int? index = null)
    {
        index ??= Rows;
        index = Math.Clamp(index.Value, 0, Rows);

        var row = new TableRow(this, index.Value);
        _rows.Insert(index.Value, row);

        for (var i = index.Value + 1; i < Rows; i++)
        {
            _rows[i].Index++;
        }

        if (index == Rows)
        {
            if (index == 0)
                HeaderContainer.AddChild(row);
            else
                RowsContainer.AddChild(row);
        }
        else
            Rebuild();

        MarkLayoutDirty();
        return row;
    }

    public TableRow CreateRow(List<Control> cells, int? index = null)
    {
        index ??= Rows;

        if (cells.Count != Columns && Columns > 0)
            throw new ArgumentException($"Wrong number of columns {cells.Count}, expected {Columns}");

        var row = CreateRow(index);

        if (row.Cells.Count == 0)
        {
            foreach (var control in cells)
            {
                var cell = row.InsertCell(row.Columns);
                cell.AddChild(control);
            }
        }
        else
        {
            for (var i = 0; i < cells.Count; i++)
            {
                row.Cells[i].AddChild(cells[i]);
            }
        }

        return row;
    }

    public List<TableCell> CreateColumn(int index)
    {
        index = Math.Clamp(index, 0, Columns);
        var cells = new List<TableCell>();

        foreach (var row in _rows)
        {
            cells.Add(row.InsertCell(index));
        }

        MarkLayoutDirty();
        return cells;
    }

    public TableCell GetCell(int row, int column)
    {
        if (row < 0 || row >= Rows)
            throw new ArgumentOutOfRangeException(nameof(row));

        if (column < 0 || column >= Columns)
            throw new ArgumentOutOfRangeException(nameof(column));

        return _rows[row].Cells[column];
    }

    private void Rebuild()
    {
        HeaderContainer.RemoveAllChildren();
        RowsContainer.RemoveAllChildren();

        for (var i = 0; i < Rows; i++)
        {
            if (i == 0)
                HeaderContainer.AddChild(_rows[i]);
            else
                RowsContainer.AddChild(_rows[i]);
        }

        MarkLayoutDirty();
    }

    private void RecalculateGridSizes()
    {
        if (Rows == 0 || Columns == 0)
        {
            _colWidths = [];
            _rowHeights = [];
            _layoutDirty = false;
            return;
        }

        foreach (var r in _rows)
        {
            foreach (var cell in r.Cells)
            {
                cell.MinSize = Vector2.Zero;
            }
        }

        foreach (var r in _rows)
        {
            foreach (var cell in r.Cells)
            {
                cell.Measure(new Vector2(float.PositiveInfinity, float.PositiveInfinity));
            }
        }

        _colWidths = new float[Columns];
        _rowHeights = new float[Rows];

        for (var c = 0; c < Columns; c++)
        {
            for (var r = 0; r < Rows; r++)
            {
                _colWidths[c] = Math.Max(_colWidths[c], GetCell(r, c).DesiredSize.X);
            }
        }

        for (var r = 0; r < Rows; r++)
        {
            for (var c = 0; c < Columns; c++)
            {
                _rowHeights[r] = Math.Max(_rowHeights[r], GetCell(r, c).DesiredSize.Y);
            }
        }

        for (var r = 0; r < Rows; r++)
        {
            for (var c = 0; c < Columns; c++)
            {
                GetCell(r, c).MinSize = new Vector2(_colWidths[c], _rowHeights[r]);
            }
        }

        _layoutDirty = false;
    }

    public float GetColumnWidth(int index)
        => index >= 0 && index < _colWidths.Length ? _colWidths[index] : 0f;

    public float GetRowHeight(int index)
        => index >= 0 && index < _rowHeights.Length ? _rowHeights[index] : 0f;

    public Vector2 GetCellSize(int row, int column)
        => new(GetColumnWidth(column), GetRowHeight(row));

    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        if (_layoutDirty)
            RecalculateGridSizes();

        return base.MeasureOverride(availableSize);
    }
}

