using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RF.UserInterface.Controls.Table;

[GenerateTypedNameReferences]
public sealed partial class TableRow : Control
{
    private readonly TableControl _table = default!;
    private int _index;

    public int Index
    {
        get => _index;
        set
        {
            _index = value;

            foreach (var cell in Cells)
            {
                cell.Row = _index;
            }
        }
    }

    public List<TableCell> Cells { get; private set; } = new();

    public int Columns => Cells.Count;

    public TableRow()
    {
        RobustXamlLoader.Load(this);
    }

    public TableRow(TableControl table, int index)
    {
        RobustXamlLoader.Load(this);
        Index = index;
        _table = table;

        while (Columns < table.Columns)
        {
            InsertCell(Columns);
        }
    }

    public TableCell InsertCell(int column)
    {
        column = Math.Clamp(column, 0, Columns);

        var cell = new TableCell(_table, column, Index);

        cell.Row = Index;
        cell.Column = column;
        Cells.Insert(column, cell);

        for (var i = column + 1; i < Columns; i++)
        {
            Cells[i].Column++;
        }

        if (column == Columns)
        {
            if (Columns != 0)
                Container.AddChild(new PanelContainer { StyleClasses = { StyleBase.ClassLowDivider }});

            Container.AddChild(cell);
        }
        else
            Rebuild();

        return cell;
    }

    public void Rebuild()
    {
        Container.RemoveAllChildren();

        for (var i = 0; i < Columns; i++)
        {
            if (i != 0)
                Container.AddChild(new PanelContainer { StyleClasses = { StyleBase.ClassLowDivider }});

            Container.AddChild(Cells[i]);
        }
    }
}

